### ISSUE TITLE
2.15.0 com.fasterxml.jackson.databind.JsonMappingException: String length (5046272) exceeds the maximum length (5000000)

### ISSUE THREAD

**Issue by mail4csm** [FasterXML/jackson-core#1001]
On very big json (~20MB), convertion (serialization) string to object is not possible, error is thrown:
com.fasterxml.jackson.databind.JsonMappingException: String length (5046272) exceeds the maximum length (5000000) ..
Conversion works on version: 2.14.2
Conversion does not work on version: 2.15.0

**Comment by pjfanning** [comment]
This is one the main features of the Jackson 2.15 release - an attempt to have Jackson fail if malicious input is provided.

Most users do not use such large text entries in their JSON.

You can increase the limits by creating a [StreamReadConstraints](https://javadoc.io/static/com.fasterxml.jackson.core/jackson-core/2.15.0/com/fasterxml/jackson/core/StreamReadConstraints.html) instance and configuring your ObjectMapper with it.

You can increase the string limit from 5 million to 10 million like this:

```
objectMapper.getFactory()
		.setStreamReadConstraints(StreamReadConstraints.builder().maxStringLength(10_000_000).build())
```

**Comment by mail4csm** [comment]
perfect

**Comment by denizk** [comment]
Just came across this ticket after upgrading to `2.16.1`.

I've tried the method to override the default StreamReadConstraints._maxNameLen value of `50_000` with 
```
objectMapper.factory.setStreamReadConstraints(StreamReadConstraints.builder().maxNameLength(100_000).build())
```

However, this does not adjust the StreamReadConstraints used in 
```
JsonFactory._rootCharSymbols = CharsToNameCanonicalizer.createRoot(this); 
``` 

which are initialised at JsonFactory construction time, so will end up with the defaults and inherit it to children used in JsonParsers when calling  `this._rootCharSymbols.makeChild()`

So, best to use the 2nd approach mentioned by @pjfanning in https://github.com/FasterXML/jackson-core/issues/1001#issuecomment-1527216221

**Comment by cowtowncoder** [comment]
@denizk Ok thank you for bringing this up. It is unfortunate. I will file an issue for this problem.

Second method would be preferred in general, but both should work.
