### ISSUE TITLE
Got `NegativeArraySizeException` when calling `writeValueAsString()`

### ISSUE THREAD

**Issue by klettier** [FasterXML/jackson-core#1012]
Hi,

I'm serializing an object containing `15M` values

- Jackson version: `2.14.2`

## Stack trace

```
java.lang.NegativeArraySizeException: -1649955036
	at java.base/java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:86)
	at java.base/java.lang.StringBuilder.<init>(StringBuilder.java:116)
	at com.fasterxml.jackson.core.util.TextBuffer.contentsAsString(TextBuffer.java:455)
	at com.fasterxml.jackson.core.io.SegmentedStringWriter.getAndClear(SegmentedStringWriter.java:85)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3875)
```

Looks like an `int` overflow somewhere in [TextBuffer](https://github.com/FasterXML/jackson-core/blob/9a42a673b7e495b586a358d8237a13d6b87c702a/src/main/java/com/fasterxml/jackson/core/util/TextBuffer.java#L454) 👀 

## Minimal test case that reproduce the issue

```kotlin
  data class MyData(
      @JsonProperty("foo")
      val foo: Collection<Item> = emptyList(),

      @JsonProperty("bar")
      val bar: Collection<Item> = emptyList(),
  )

  data class Item(
      @JsonProperty("id")
      val id: String,

      @JsonProperty("value")
      val value: String,
  )

  @Test
  fun overflow() {
      val report = MyData(
          foo = (1..5_000_000).map { Item(UUID.randomUUID().toString(), UUID.randomUUID().toString()) },
          bar = (1..10_000_000).map {
              Item(
                  "foo=${UUID.randomUUID()}bar=${UUID.randomUUID()},barbar=${UUID.randomUUID()}",
                  UUID.randomUUID().toString(),
              )
          },
      )

      jacksonObjectMapper().writeValueAsString(report)
  }
```

### Result

![image](https://user-images.githubusercontent.com/3425823/236057236-d7a06361-83cb-4806-a49a-d379aeafb803.png)

**Comment by pjfanning** [comment]
Can you provide a test case? - it would speed this along

**Comment by klettier** [comment]
Yes I'm working on it

**Comment by klettier** [comment]
Minimal Test case that reproduce the issue added

**Comment by pjfanning** [comment]
I debugged the test case and the issue is that the TextBuffer gets too big. StringBuilder will only support Integer.MAX_VALUE chars (approx 2Gb in utf-8 or ascii - 1 byte per char).

@cowtowncoder the `_segmentSize` in TextBuffer can turn negative when the int overflows. We could throw exceptions after any increments to `_segmentSize` if the value goes negative. 

There is little benefit to making _segmentSize a long because in the end `contentsAsString` and `contentsAsArray` can only support cases where the size is <= Integer.MAX_SIZE.

**Comment by pjfanning** [comment]
I modified my test to write to a `writeValue(OutputStream, value)` instead (I used a FileOutputStream) and that successfully handled the large JSON. Writing to a String is basically limited to 2 billion chars.

**Comment by cowtowncoder** [comment]
Ok, will merge the fix. Thank you @pjfanning for the fix, @klettier for reporting it!
