### ISSUE TITLE
Root cause for failing test for `testMangledIntsBytes()` in `ParserErrorHandlingTest`

### ISSUE THREAD

**Issue by harsha-99** [FasterXML/jackson-core#1035]
I was looking at the failing tests directory and was trying to debug the failing tests in `ParseErrorHandling105Test.java` file, I realised there was a similar test commented out in `ParserErrorHandlingTest.java` under package `com.fasterxml.jackson.core.read` in line 29 i.e. `_testMangledNumbersInt(MODE_DATA_INPUT);`
I saw a comment wondering how `_testMangledNumbersFloat(MODE_DATA_INPUT);` was working. 

With my investigation I found out that during `_testMangledNumbersIn()` execution,  `_verifyRootSpace()` in `line 1088` of `UTF8DataInputJsonParser.java`  gets called with `_nextByte = -1` and hence satisfies the condition in `line 1278` i.e. `if (ch <= INT_SPACE)` hence doesn't throw a missing WS error. Where as for `_testMangledNumbersFloat` we set the value as `_nextByte = c;` in `line 1257` and hence it would throw the exception. 

I hope this explains the root cause of the issue, happy to receive any feedback or suggestions. Apologies for my verbose explanation.

**Comment by cowtowncoder** [comment]
@harsha-99 Thank you for submitting this. I'll have a look!
