### ISSUE TITLE
On parsing skip the specified keywords!

### ISSUE THREAD

**Issue by dialYun** [FasterXML/jackson-core#1049]
We are working on a low-code platform, and some of the content is user-defined. The front-end json is transmitted to the back-end. We don't want to parse the part filled in by the user, because that part may not be a standard json, and this error will be reported: java.lang.RuntimeException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('c' (code 99)): was expecting comma to separate Object entries, such as key: events, how can we skip this key? I tried many ways, including: StdDeserializer! Hope you can give me an example, thanks!

Here is the json:{"id":"form_rjgf8d0vv049c","type":"form","props":{"visible":true,"classNames":[],"events":[],"labelPosition":"vertical","width":"100%","size":"middle","labelSpan":2,"disabled":false,"datasourcePool":[],"stylesheets":[{"title":"main","id":"main","code":""}],"utilsJs":[],"relations":[]},"children":[{"id":"input_o0dxx2zqf4elc","type":"input","props":{"visible":true,"classNames":[],"events":[{"event":"change","codeItem":{"code":"module.exports=function(params, ctx, block) {\n  const mjj = [{\"children\":[{\"children\":\"\",\"disabled\":false,\"id\":3,\"label\":\"seattle\",\"parentId\":2,\"value\":\"110100\"}],\"disabled\":false,\"id\":2,\"label\":\"seattle\",\"parentId\":0,\"value\":\"110000\"},{\"children\":[{\"children\":\"\",\"disabled\":false,\"id\":2204,\"label\":\"seattle\",\"parentId\":2203,\"value\":\"460100\"},{\"children\":\"\",\"disabled\":false,\"id\":2209,\"label\":\"seattle\",\"parentId\":2203,\"value\":\"460200\"},{\"children\":\"\",\"disabled\":false,\"id\":2214,\"label\":\"seattle\",\"parentId\":2203,\"value\":\"460300\"},{\"children\":\"\",\"disabled\":false,\"id\":3228,\"label\":\"seattle\",\"parentId\":2203,\"value\":\"83003\"}],\"disabled\":false,\"id\":2203,\"label\":\"seattle\",\"parentId\":0,\"value\":\"460000\"}]\n\n  console.log('mjjmjjmjjmjjmjjmjjmjjmjj',mjj)\n}","utils":[]}}],"dataBind":"input_o0dxx2zqf4elc","customDataBind":true,"label":"seattle","labelHidden":false,"labelCustomWidth":false,"labelWidth":2,"readonly":false,"required":false,"disabled":false,"allowClear":false,"validatorFunc":"","validateMode":"submit","placeholder":"","defaultValue":"","isAutoComplete":false,"options":[],"dataSourceFn":"","isPassword":false}}]}

**Comment by dialYun** [comment]
I agree with your point of view, but the user's input is always diverse. For example, the following string, jackson will misjudge the code entered by the user in codeItem. Is there any way to make jackson always think that the value in a key is Is it a string? Thanks again for your reply!

Example:
{"id":"form_rjgf8d0vv049c","type":"form","props":{"visible":true,"classNames":[],"events":[],"labelPosition":"vertical","width":"100%","size":"middle","labelSpan":2,"disabled":false,"datasourcePool":[],"stylesheets":[{"title":"main","id":"main","code":""}],"utilsJs":[],"relations":[]},"children":[{"id":"input_o0dxx2zqf4elc","type":"input","props":{"visible":true,"classNames":[],"events":[{"event":"change","codeItem":{"code":"module.exports=function(params, ctx, block) {\\n  const mjj = [{\\"children\\":[{\\"children\\":\\"\\",\\"disabled\\":false,\\"id\\":3,\\"label\\":\\"seattle\\",\\"parentId\\":2,\\"value\\":\\"110100\\"}],\\"disabled\\":false,\\"id\\":2,\\"label\\":\\"seattle\\",\\"parentId\\":0,\\"value\\":\\"110000\\"},{\\"children\\":[{\\"children\\":\\"\\",\\"disabled\\":false,\\"id\\":2204,\\"label\\":\\"seattle\\",\\"parentId\\":2203,\\"value\\":\\"460100\\"},{\\"children\\":\\"\\",\\"disabled\\":false,\\"id\\":2209,\\"label\\":\\"seattle\\",\\"parentId\\":2203,\\"value\\":\\"460200\\"},{\\"children\\":\\"\\",\\"disabled\\":false,\\"id\\":2214,\\"label\\":\\"seattle\\",\\"parentId\\":2203,\\"value\\":\\"460300\\"},{\\"children\\":\\"\\",\\"disabled\\":false,\\"id\\":3228,\\"label\\":\\"seattle\\",\\"parentId\\":2203,\\"value\\":\\"83003\\"}],\\"disabled\\":false,\\"id\\":2203,\\"label\\":\\"seattle\\",\\"parentId\\":0,\\"value\\":\\"460000\\"}]\\n\\n  console.log('mjjmjjmjjmjjmjjmjjmjjmjj',mjj)\\n}","utils":[]}}],"dataBind":"input_o0dxx2zqf4elc","customDataBind":true,"label":"input","labelHidden":false,"labelCustomWidth":false,"labelWidth":2,"readonly":false,"required":false,"disabled":false,"allowClear":false,"validatorFunc":"","validateMode":"submit","placeholder":"","defaultValue":"","isAutoComplete":false,"options":[],"dataSourceFn":"","isPassword":false}}]}

**Comment by pjfanning** [comment]
This is your problem - not a world problem. You can wrap and escape the user's input.

**Comment by dialYun** [comment]
ok, thanks for your suggestion!

**Comment by cowtowncoder** [comment]
No, that is not valid JSON and the system that produces JSON-like invalid content is broken. Fix that.

Note, too, that not properly escaping user-provided content is often a huge security risk, see SQL Injection attacks. Anyone just embedding content as-is is basically an attack vector themselves. User input must ALWAYS BE SANITIZED and/or ESCAPED before including in content.
