### ISSUE TITLE
Add configurable error report behavior via `ErrorReportConfiguration`

### ISSUE THREAD

**Issue by JooHyukKim** [FasterXML/jackson-core#1066]
(note: started from in [google groups discussion](https://groups.google.com/g/jackson-user/c/4rjcZ3s1pDE/m/rNfUomagAQAJ) and follow up of #1043 )

### Motivation

Currently there is not a user-friendly way to configure how error report is made. So when the issue is resolved, user would be able to perform following configurations.

- Configure maximum length of token to include in error messages
- Configure maximum length of raw content to include in error messages

### Modifications

This issue will be used to contain the sub-PRs that are broken down from the very original PR #1043. Currently planned ones are

- First, Add new `ErrorReportConfiguration` type with builder, unit test(s)
    - #1067 
- Retrofit `IOContext` with new `ErrorReportConfiguration`
   - #1068 
- Retrofit `ContentReferece`
    - #1070 
- Change `TSFBuilder` / `JsonFactory` to allow configuring and holding on to that config object
- Minor clean-up, JavaDoc etc...

**Comment by cowtowncoder** [comment]
Completed!
