### ISSUE TITLE
Feature Request - Add an option for strict document processing

### ISSUE THREAD

**Issue by yhojann-cl** [FasterXML/jackson-core#1073]
I've done some tests and found that the library handles corrupted json documents that are out of the standard and may also contain unadvised practices, for example, including garbage characters at the end of the document and duplicating keys.

I understand that the library overrides duplicate values but this can cause some performance issues and in some cases access to these keys may not be required, so it would be a good idea to have an optional setting that generates an error when the first duplicate is issued. a key on the same dimension of the tree. An example of this is in the transformation of a json document to a DTO object which will be used to process entities or DAO objects where duplicate keys are not necessary and cannot be transformed into arrays, for example, in the practical case of Java Spring Boot This library is used to transform the body content of an http request to a request object, but the http standard indicates that duplicate keys in a uri-formatted body should be treated as array but the jackson library overrides the same value in a single variable of type text. It is not that one or the other is wrong, but I do think that examples like this indicate that it will not always be a good idea to process duplicate keys in the same way and that is why I think an option is necessary to avoid this type of situation.

It would also be a good idea if there was an option so that the processing of a json document is strict, this means that it should not process content that ends with garbage content, regardless of whether it can be transformed or omitted, since it can cause problems in use. from memory.

Here is an example of everything I have explained: https://github.com/spring-projects/spring-boot/issues/36666

**Comment by cowtowncoder** [comment]
@yhojann-cl Did you do any research before filing this issue? There are settings that cover these aspects; @pjfanning pointed out one, but there's `StreamReadFeature.STRICT_DUPLICATE_DETECTION` for another.

Going forward I suggest you try to figure out what exists before filing new issues.

**Comment by cowtowncoder** [comment]
I don't see anything specific to work on here; not sure I feel there's enough to try to indicate some sort of "strict mode" given that the only missing thing would be enabling `FAIL_ON_TRAILING_TOKENS`.

Closing; can re-file with more specific request.
