### ISSUE TITLE
Speeding up Jackson via JNI

### ISSUE THREAD

**Issue by michaeleisel** [FasterXML/jackson-core#1080]
In my benchmarking of Jackson for my own JSON files, it seems to spend the majority of its time going character-by-character to see if it's hitting a structural character (ending quote of a string, non-whitespace to start the next token, etc.). This can be sped up substantially by leveraging existing native code parsers that are much faster at this, and in fact I've done that with the parser simdjson. During simdjson's parsing, it writes out all structural characters and their indexes to a buffer. By running that piece of simdjson and returning its buffer via the JNI, I've managed to substantially improve Jackson's speed. There ends up being only one JNI call, that of getting the buffer, and then the character-by-character process is replaced with just going through this buffer. In a sense, the buffer provides bytecode for how to create and set the correct Java objects, and the Java code just reads this bytecode to create the objects.

Extension

In its simplest form, this process would just allow skipping over non-structural characters. However, it could also be extended to substantially improve key-value lookups for the ObjectMapper. Currently, when a key is encountered in a JSON dictionary, a string is created from the key and a lookup is done. However, when iterating over the buffer, the native code could do its own hash map lookup (and avoid any sort of string creation) and convert from string into index for an array of instance variables. Then, that index is passed back in the bytecode rather than the key's string, and in Java it just looks up the variable for that index from an array.

I'm happy to open a PR with my work if there's interest. If there's not, I'll probably just make a fork of Jackson.

**Comment by pjfanning** [comment]
This is just my opinion - but Jackson is complicated enough already. There are a large number of existing Jackson users and libraries that use Jackson under the hood. A large proportion of these users get scared when they hear that we are radically changing Jackson. Using JNI is a complication that I would rather avoid.

As an example, there are already JSON parsers out there that benchmark better than Jackson. If gaining a little bit of extra performance is really the priority for a user, they could try those other libs. In many cases, you might be better off using a non-Java lib.

All of Jackson's code is FOSS. Someone could fork it and create their own great lib.

**Comment by pjfanning** [comment]
I notice there is also https://github.com/simdjson/simdjson-java.

**Comment by michaeleisel** [comment]
Yeah simdjson-java is interesting, but seems to be still under development and less feature-rich. I'm also not sure how to weigh the tradeoffs of using the experimental APIs and required compiler flags that simdjson-java does vs. using the JNI

**Comment by cowtowncoder** [comment]
I am bit surprised if scanning for markers actually speeds up decoding, given that for vast majority of things Jackson core parsers accumulate content (String/number values, Property names) as part of scanning; the main remaining thing that is scanned over is white space.

But assuming this is the case, I would second @pjfanning 's suggestion for implementing alternative `JsonParser` backend to show potential. Whether default jackson-core should include (or even default to) JNI-based implementation is a different discussion, but we can cross that bridge when we get there.

Also note that there are already multiple `JsonParser` implementations within Jackson-core: 2 for regular streaming input (one for `byte`-based input like `InputStream`, another for `char`-based like `Reader), one for async (non-blocking; byte-based) input.

**Comment by cowtowncoder** [comment]
No immediate action planned; but submitting PRs is always possible regardless of whether there is issue filed.

Closing.
