### ISSUE TITLE
@JsonProperty ignored when used in super-class constructor

### ISSUE THREAD

**Issue by Queatz** [FasterXML/jackson-core#1084]
I could not for the life of me figure out why my field was always deserializing as `null` (I'm using ArangoDB which uses Jackson internally.)  After learning a bit about Jackson I had a hunch that it was something to do with the property alias, which ultimately was the cause.

Fails:

```kotlin
@Serializable
class B : A()

@Serializable
open class A(
    @JsonProperty("_a")
    @JsonAlias("a")
    var a: String? = null
)
```

Gives: `UnrecognizedPropertyException: Unrecognized field "_a" (class com.queatz.B), not marked as ignorable (one known property: "a"])`

Moving the property out of the constructor makes everything okay:

```kotlin
@Serializable
class B : A()

@Serializable
open class A {
    @JsonProperty("_a")
    @JsonAlias("a")
    var a: String? = null
}
```

This correctly deserializes `_a`

**Comment by pjfanning** [comment]
This is not the right project. Could you move this to https://github.com/FasterXML/jackson-module-kotlin ?
