### ISSUE TITLE
Hash-pin workflow GitHub Actions 

### ISSUE THREAD

**Issue by pnacht** [FasterXML/jackson-core#1102]
Hey @cowtowncoder, I'm back with another security suggestion.

When developing with CI workflows, it's common to version-pin dependencies (i.e. `actions/checkout@v3`). Such major-version pins can be useful in that you get immediate access to the latest version of each Action. However, this also makes the project vulnerable should a broken or malicious release be published. However, version tags are mutable, so minor version tags aren't the best solution, since a malicious attacker could overwrite a version tag to point to a malicious or vulnerable commit instead.

Pinning workflow dependencies by hash ensures the dependency is immutable and its behavior is guaranteed.

Since jackson-core already has dependabot set up to monitor GitHub Actions, this won't change much on your end. These hashes will be automatically updated by dependabot.

I'll send a PR pinning the Actions along with this issue.

---

By the way, in case you aren't aware, Dependabot now supports [grouped updates](https://github.blog/2023-08-24-a-faster-way-to-manage-version-updates-with-dependabot/), such that you'll receive all version updates in a single PR, instead of one PR per Action (see [this example](https://github.com/pnacht/libarchive/pull/1)). Let me know if you want me to send a PR to make this change to dependabot as well.

**Comment by cowtowncoder** [comment]
As per my comments on PR, yeah, let's do it.
I am not a big fan of physical hashes for dependencies (they are machine-readable ids, not human-), but it makes sense here.

Also +1 for grouped updates.
