### ISSUE TITLE
JsonParser doesn't inherit objectCodec's StreamReadConstraints limits 2.15.2

### ISSUE THREAD

**Issue by ddellsperger** [FasterXML/jackson-core#1116]
This is likely related to #937 and #958 but I didn't want to open up the discussion on those tickets in order to not resurrect closed issues.

We're leveraging the `JsonParser` in some code where our input Json has varying lengths (potentially very large lengths), we've added support in our object mappers to override the StreamReadConstraints `_maxStringLen` to exceed the 20,000,000 character threshold (we're using the old value of `Integer.MAX_VALUE`) similar code here:
```java
ObjectMapper objectMapper = new ObjectMapper();
objectMapper.registerModule(new SimpleModule() {
    @Override
    public void setupModule(SetupContext context) {
        super.setupModule(context);
        context.getOwner().getFactory().setStreamReadConstraints(StreamReadConstraints
                .builder()
                .maxStringLength(Integer.MAX_VALUE)
                .build());
    }
});
```

We then leverage that object mapper when creating the `JsonFactory` with the following:
```java
JsonFactory factory = new MappingJsonFactory(objectMapper);
```

But when leveraging a json parser created by calling `createParser(InputStream)` it seems to not leverage the settings from that ObjectMapper (ObjectCodec):
```java
JsonParser parser = factory.createParser(inputStream);
```

When that parser parses (gets the next item from the object iterator) it throws an error based on the size of the input string:
```
Caused by: com.fasterxml.jackson.core.exc.StreamConstraintsException: String length (20051112) exceeds the maximum length (20000000)
```

It seems that with #856 it just uses a [default StreamReadConstraints instance](https://github.com/FasterXML/jackson-core/blob/74ca3ac34c37ff87ce0108d42d91d313e4222057/src/main/java/com/fasterxml/jackson/core/JsonParser.java#L518), but it seems like it should conditionally pull from the ObjectCodec if it's available.

Happy to provide a PR or try other things based on discussion here.

**Comment by pjfanning** [comment]
Why not create a JsonFactory and set the StreamReadConstraints on it? And then create an ObjectMapper using that JsonFactory?

https://javadoc.io/doc/com.fasterxml.jackson.core/jackson-databind/latest/com/fasterxml/jackson/databind/ObjectMapper.html

**Comment by ddellsperger** [comment]
It looks like the `overrideDefaultStreamReadConstraints` will work for us at a core application level, but that still doesn't help the issue if we want different constraints for each `JsonParser` instance, which the javadoc of that method seems to indicate should be possible (as you can't set it directly on the `JsonFactory` but have to set it in the `ObjectCodec` that you pass into the `JsonFactory` constructor)

> These defaults are only used when [JsonFactory](https://javadoc.io/static/com.fasterxml.jackson.core/jackson-core/2.15.2/com/fasterxml/jackson/core/JsonFactory.html) instances are not configured with their own StreamReadConstraints.

No matter what, any `StreamReadConstraints` object won't be referenced in any way by the `JsonParser` because it always pulls the `StreamReadConstraints.default()` version, so the only way to change that would be at the global level.

**Comment by pjfanning** [comment]
@ddellsperger  You will find unit tests in jackson-databind that create JsonFactory instances with custom StreamReadConstraints values and that use ObjectMappers that are set up to use the JsonFactory instance.

**Comment by ddellsperger** [comment]
@pjfanning we are parsing Json (from a file) not writing Json to a file or object, so the JsonMapper doesn't really help us here.  Again, the JsonParser itself doesn't support a custom stream read constraints setting intrinsically, which means any setting made at the JsonFactory level won't be applicable to the JsonParser itself.

**Comment by pjfanning** [comment]
@ddellsperger JsonMapper is just effectively a new name for ObjectMapper. JsonMapper/ObjectMapper can be used to parse and write JSON. Nothing has changed. I'm -1 on making the change you suggest and you can keep ignoring my suggestions.

**Comment by cowtowncoder** [comment]
Quick note: trying to change `StreamReadConstraints` dynamically via `JsonFactory` is not supported -- while there is a setter, it should be called during construction and initialization. And there is no support to change it on per-JsonParser basis.
Intent is, instead, that for different limits different `JsonFactory` instance is needed.

As to `MappingJsonFactory`... I don't know. Things can get quite hairy wrt back and forth calls.

I do however one question: why are you constructing `MappingJsonFactory`, instead of using `mapper.getFactory()` which is linked to `ObjectMapper` that "owns" it? Using that factory would use configured constraints.

**Comment by cowtowncoder** [comment]
I think the original usage of:

```
JsonFactory factory = new MappingJsonFactory(objectMapper);
```

is that wrong: constraints are not to be copied back and forth here.
Instead, underlying factory from the mapper should be used: it should already be linked.
If not, that's something else we could have a look.

Since I do not see anything to work on right now, closing this issue.
