### ISSUE TITLE
Change default `RecylerPool` implementation to `newLockFreePool` (from `threadLocalPool`)

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-core#1117]
With #1089 (and related) completed, Jackson 2.16 both allows for configuring alternate `RecyclerPool`s to use for buffer recycling and provides a set of alternatives, notably ones that do not use `ThreadLocal` for recycling.

To reduce likelihood of breakage, the default implementation for 2.16 remains ThreadLocal-based pool. This hopefully allows as to gather feedback, experiences by early adopters, on how alternative pools work (for example, Quarkus project is likely to experiment with alternatives). This, in turn, should let us decide on which alternative to use, along with global-vs-per-factory pools.
As the baseline, my icurrent thinking is that per-factory, unbounded/lock-free implementation might work well as the default.

**Comment by cowtowncoder** [comment]
Ok, to get discussion started, I will propose we will use:

* `JsonRecyclerPool.newLockFreePool()`

as the default. This will have following benefits:

* Per-factory instances to reduce chance of global contention
* Has low minimal memory usage

As with any choice this will not be the optimal choice for all use cases. I am ready to hear alternative suggestions.

**Comment by mariofusco** [comment]
Note that this is blocked by https://github.com/FasterXML/jackson-databind/issues/4321

**Comment by cowtowncoder** [comment]
Note: issue @mariofusco outlined (thanks!) has been resolved now, so the default pool implementation may be changed.
