### ISSUE TITLE
No Javadoc for 2.15 available

### ISSUE THREAD

**Issue by robtimus** [FasterXML/jackson-core#1119]
While updating one of my own libraries from Jackson 2.14 to 2.15, I found out that the Javadoc for version 2.15 is not present at https://fasterxml.github.io/jackson-core/javadoc/2.15/. https://fasterxml.github.io/jackson-core/javadoc/2.14/ works but for version 2.15 it gives a 404. It looks like this was never generated - the folder is missing from https://github.com/FasterXML/jackson-core/tree/gh-pages/docs/javadoc.

**Comment by pjfanning** [comment]
Have a look at the README - it has links to the new home for the javadoc.

https://javadoc.io/doc/com.fasterxml.jackson.core/jackson-core/latest/index.html
