### ISSUE TITLE
Make DEFAULT_MAX_STRING_LEN in StreamReadConstraints configurable

### ISSUE THREAD

**Issue by ranjanvishal-gmaildotcom** [FasterXML/jackson-core#1121]
In "com.fasterxml.jackson.core", in StreamReadConstraints there is a constraint of string length of 20M by DEFAULT_MAX_STRING_LEN variable. To handle larger text, we need this value to be a much larger value. We want this variable to be made configurable so that we can tweak it as per requirement.

This constraint was added in 2.15.0 release.

public class StreamReadConstraints
public static final int DEFAULT_MAX_STRING_LEN = 20_000_000;

Snippet of exception received:
com.fasterxml.jackson.core.exc.StreamConstraintsException: String length (20054016) exceeds the maximum length (20000000) at com.fasterxml.jackson.core.StreamReadConstraints.validateStringLength(StreamReadConstraints.java:324) at com.fasterxml.jackson.core.util.ReadConstrainedTextBuffer.validateStringLength(ReadConstrainedTextBuffer.java:27) at com.fasterxml.jackson.core.util.TextBuffer.finishCurrentSegment(TextBuffer.java:939) at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString2(UTF8StreamJsonParser.java:2584) at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString(UTF8StreamJsonParser.java:2529) at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.getTextCharacters(UTF8StreamJsonParser.java:487) at com.fasterxml.jackson.core.JsonGenerator._copyCurrentStringValue(JsonGenerator.java:2777) at com.fasterxml.jackson.core.JsonGenerator._copyCurrentContents(JsonGenerator.java:2668) at com.fasterxml.jackson.core.JsonGenerator.copyCurrentStructure(JsonGenerator.java:2619) at

**Comment by pjfanning** [comment]
It is configurable. Best set by creating a JsonFactory and setting your own StreamReadConstraints on it. You can create ObjectMappers using your configured JsonFactory. You can also change the global defaults by using https://javadoc.io/static/com.fasterxml.jackson.core/jackson-core/2.15.2/com/fasterxml/jackson/core/StreamReadConstraints.html#overrideDefaultStreamReadConstraints-com.fasterxml.jackson.core.StreamReadConstraints-
