### ISSUE TITLE
(3.0) Rename `tools.jackson.core.exc.WrappedIOException` as `...JacksonIOException`

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-core#1132]
(suggestion by @garretwilson )

Current type of `WrappedIOException` in Jackson 3.0 (`master`) is too generic; let's rename it as `JacksonIOException` instead.

**Comment by garretwilson** [comment]
For traceability, FasterXML/jackson-databind#4180 is the discussion in which the suggestion was made.

**Comment by cowtowncoder** [comment]
Also updated:

* jackson-databind
* jackson-dataformats-binary
* jackson-modules-base

and verified no issues with

* jackson-dataformats-text
* jackson-dataformat-xml

**Comment by pjfanning** [comment]
This change causes test failures. The JodaModule 3.0.0-SNAPSHOT is not yet compiled with the new changes. Until this happens and a new JodaModule 3.0.0-SNAPSHOT is published, this will continue.

**Comment by cowtowncoder** [comment]
Fixed `jackson-datatype-joda`. Also noticed I hadn't pushed actual changes to `jackson-dataformats-text`, did that now.
Will check JAX-RS/Jakarta-RS-provider packages.
