### ISSUE TITLE
JsonPointer.appendProperty(String) does not escape the property name

### ISSUE THREAD

**Issue by Mahoney** [FasterXML/jackson-core#1145]
The following code:

```java
JsonPointer
  .valueOf("/")
  .appendProperty("paths")
  .appendProperty("/things")
  .appendProperty("post")
  .appendProperty("requestBody")
  .appendProperty("content")
  .appendProperty("application/json")
  .appendProperty("schema")
```

should produce this json pointer:
`/paths/~1things/post/requestBody/content/application~1json/schema`

Instead it produces this json pointer:
`/paths/things/post/requestBody/content/application/json/schema`

As you can see, the `/` at the start of `/things` and the `/` in the middle of `application/json` are not escaped, producing a completely incorrect path.

(You also need to escape `~` correctly as per [RFC 69010](https://www.rfc-editor.org/rfc/rfc69010)

**Comment by Mahoney** [comment]
(Incidentally, wouldn't it make sense to have a `JsonPointer.ROOT` constant that evaluates to `JsonPointer.valueOf("/")`?)

**Comment by cowtowncoder** [comment]
@Mahoney Escaping part does look like a straight bug, yes.

As to `JsonPointer` for `""`: no, semantics are such that `"/"` is for matching root level property with "empty" name like:

```json
{ "" : 42 }
```

as opposed to representing root value itself.

**Comment by cowtowncoder** [comment]
Due to change in observed behavior, fixing in 2.17 for next minor release (2.17.0), cannot backport into 2.16.
