### ISSUE TITLE
JsonGenerator writeRawValue problem with surrogate UTF-8 characters

### ISSUE THREAD

**Issue by MarcinZukowski** [FasterXML/jackson-core#115]
We serialize data into a string (e.g. for logging), and then want to write it without additional conversions. Below is the code showcasing it. 

The problem is that if the string contains surrogate UTF-8 characters, writeRawValue fails with
  Incomplete surrogate pair: first char 0xde0c, second 0xd83d

I lookeded at the sources at 
  https://github.com/FasterXML/jackson-core/blob/master/src/main/java/com/fasterxml/jackson/core/json/UTF8JsonGenerator.java
I believe the issue is in  _outputRawMultiByteChar result being completely ignored, so the input cursor isn't moved, and the second surrogate character is being considered to be the first one...

Not sure if writeRawValue is supposed to handle surrogates properly, but looking at the code, it seems at least the intent was there.

Code reproducing the bug follows. What's the best way to resolve it?

``` java
import java.io.*;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.core.JsonFactory;
import com.fasterxml.jackson.core.JsonGenerator;

public class JBug {
    public static void main(String[] args) {
        try {
          FileOutputStream out = new FileOutputStream("bla.json");

          ObjectMapper mapper = new ObjectMapper();
          JsonFactory jsonFactory = new JsonFactory();
          JsonGenerator jsonGenerator = jsonFactory.createJsonGenerator(out);

          jsonGenerator.writeStartObject();
          jsonGenerator.writeFieldName("data");
          String s = "\ud83d\ude0c";  // surrogate character
          s = s + s;  // 2 of them
          // Separate serialization step, 
          // as we want to intercept the result value
          String ss = mapper.writeValueAsString(s);
          System.out.println(ss);
          // And now actually write it out
          jsonGenerator.writeRawValue(ss);
          jsonGenerator.writeEndObject();
          jsonGenerator.close();
        } catch (Exception e) {
                e.printStackTrace();
        }
  }
}
```

**Comment by devGuilherme** [comment]
I have this problem "com.fasterxml.jackson.core.JsonParseException: Invalid UTF-8 middle byte 0x22" cause by a special character "ç", what I have to do?

**Comment by cowtowncoder** [comment]
@devGuilherme Please file a new issue -- I don't like resurrecting closed ones, since they are problematic wrt release notes. It is a good idea to add a back reference (just add id prefixed by hash character `#`), but file a new one.

But also note that just because your error message has same words does not necessarily mean it is actually related. From your brief description I would rather guess you have invalid input, like Latin-1 (ISO-8859-1) encoded strings -- which are not valid JSON, as per JSON spec that only allows UTF encodings.
