### ISSUE TITLE
NPE in "FastDoubleParser", method "JavaBigDecimalParser.parseBigDecimal()"

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-core#1161]
(note: regression due to #1157)

Looks like there is an NPE in FDP, method `JavaBigDecimalParser#parseBigDecimal` for Strings of length 1000 (and seemingly even less).
I will do a PR with reproduction.

**Comment by wrandelshofer** [comment]
I made a fix and have released it as version 1.0.0 of fastdoubleparser.
https://github.com/wrandelshofer/FastDoubleParser/releases/tag/v1.0.0

Please let me know, if the fix works for you.

**Comment by pjfanning** [comment]
Thanks @wrandelshofer for the prompt fix - I'll try out the 1.0.0 release when it hits https://repo1.maven.org/maven2/ch/randelshofer/fastdoubleparser/ (maven central).

**Comment by cowtowncoder** [comment]
Fixed in 2.16 for 2.16.1 (and `2.17`); may be backported to 2.15 depending.
