### ISSUE TITLE
feature to allow trailing commas (non-compliant JSON)

### ISSUE THREAD

**Issue by cburroughs** [FasterXML/jackson-core#118]
Splitting off from #52 and originally at http://jira.codehaus.org/browse/JACKSON-618

Presumably a feature named: ALLOW_TRAILING_COMMA

If enabled the following would be valid and yield the same result:
- `[1,2,3,]    [1,2,3]`
- `{1:1,}       {1:1}`

**Comment by albertocavalcante** [comment]
I'm in a situation where a third party is sending a leading comma:

- `{,1:1} {1:1}`

Any chance already having a feature flag similar to the ALLOW_TRAILING COMMA? Or any tips on implementing this custom deserialization?

Thanks

**Comment by cowtowncoder** [comment]
@albertocavalcante There is `JsonReadFeature.ALLOW_MISSING_VALUES` (and deprecated `JsonParser.Feature.ALLOW_MISSING_VALUES`) which might work.
