### ISSUE TITLE
 Is calling BufferRecyclers.releaseBuffers() no longer necessary on contextDestroy?

### ISSUE THREAD

**Issue by danshome** [FasterXML/jackson-core#1181]
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

We had to add a call to BufferRecyclers.releaseBuffers(); in our contextDestroy method to avoid a memory leak on hot redeploy, but after upgrading to the 2.16.1 we are getting a message that BufferRecyclers is deprecated. Is calling BufferRecyclers.releaseBuffers() no longer necessary? 

### Version Information

2.16.1

### Reproduction

<-- Any of the following
1. Brief code sample/snippet: include here in preformatted/code section
2. Longer example stored somewhere else (diff repo, snippet), add a link
3. Textual explanation: include here
 -->
```java
// Your code here
```

**Comment by cowtowncoder** [comment]
Created #1202 which should remove need for `BufferRecyclers.releaseBuffers()`, when using one of newer pool implementations. Closing.
