### ISSUE TITLE
Enable Fast Floating-Point reading/writing by default in 3.0

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-core#1231]
For Jackson 2.x we have following features disabled by default:

* `StreamReadFeature.USE_FAST_DOUBLE_PARSER`
* `StreamReadFeature.USE_FAST_BIG_NUMBER_PARSER`
* `StreamWriteFeature.USE_FAST_DOUBLE_WRITER`

that is, for FP reading to use default JDK implementation and not one from FastDoubleParser (read) / Schubfach (write). This to minimize any chance of breakage, to require users to opt-in for optimized handling.

Since there hasn't been reports of issues during the time we've had (since 2.14, more than a year), it seems reasonable to assume things work well: so let's enable "fast FP" handling by default for 3.0.
We can still consider similar change for later 2.x, but let's start with 3.0.

**Comment by j3graham** [comment]
One thought on this change - as of Java 19, an implementation of the Schubfach algorithm is used in the JDK itself, and there have been more improvements since then. Perhaps keeping the default USE_FAST_DOUBLE_WRITER using the JDK should be considered. See https://bugs.openjdk.org/browse/JDK-4511638

**Comment by pjfanning** [comment]
@j3graham we did not change the write config for exactly the reason you describe.

You can see the v3 code here and its javadoc.

https://github.com/FasterXML/jackson-core/blob/master/src/main/java/tools/jackson/core/StreamWriteFeature.java#L115-L129

**Comment by cowtowncoder** [comment]
I will update description, good call out @j3graham , @pjfanning.
