### ISSUE TITLE
Migrate remaining test to JUnit 5

### ISSUE THREAD

**Issue by timo-a** [FasterXML/jackson-core#1239]
Since [this is going to take several PRs](https://github.com/FasterXML/jackson-core/pull/1237#issuecomment-1987357545), this issue is intended to coordinate them.

original PR: https://github.com/FasterXML/jackson-core/pull/1237

- Part 1: https://github.com/FasterXML/jackson-core/pull/1238 tests that don't extend or depend on BaseTest or its child classes
- Part 2: https://github.com/FasterXML/jackson-core/pull/1244 tests that extend AsyncTestBase
- Part 3: https://github.com/FasterXML/jackson-core/pull/1245 tests in core.read that extend BaseTest
- Part 4 https://github.com/FasterXML/jackson-core/pull/1246 core.io, core.json and failing
- Part 5 https://github.com/FasterXML/jackson-core/pull/1247 core.base64 to core.sym
- Part 6 https://github.com/FasterXML/jackson-core/pull/1248 remaining tests

**Comment by cowtowncoder** [comment]
First PR merged; looks like there are 125 cases of `BaseTest` being extended so likely target count.

May need 3 - 5 PRs depending on what works best. Since 2.18 branch only now starting, ok to target against 2.17.

**Comment by timo-a** [comment]
I guess we're done here, `junit-vintage-engine` is gone from the pom files of `master`, `2.17` and `2.28`.

**Comment by cowtowncoder** [comment]
Indeed! Thank you for doing this, @timo-a !
