### ISSUE TITLE
Rename shaded `ch.randelshofer:fastdoubleparser` classes to prevent use by downstream consumers

### ISSUE THREAD

**Issue by seadbrane** [FasterXML/jackson-core#1264]
The shaded ch.randelshofer:fastdoubleparser classes  are being used by at least one other open source project.  As the shaded version of these classes do not appear to be intentionally made available for consumers of jackson-core, it would be useful to either 1) not shade this dependency or to 2) randomize the package name and make it sufficiently obviously that these are not meant for general consumption.  

For 2, one option would be to embed jackson-core version number and other identifiers that indicated this was for internal jackson-core use only and/or that this is a shaded dependency.  

Such as:

```
com/fasterxml/jackson/core/internal/v2_18_0/fastdoubleparser/
```

And/or:

```
com/fasterxml/jackson/core/internal/v2_18_0/shaded/fastdoubleparser/
```

**Comment by pjfanning** [comment]
I would recommened the opposite - raise issues with anyone who is using the jackson shaded classes.

**Comment by seadbrane** [comment]
> I would recommened the opposite - raise issues with anyone who is using the jackson shaded classes.

This will do that as well and also minimize the possibility of other packages using the shaded code.

**Comment by cowtowncoder** [comment]
While I agree that trying to educate users would ideally suffice, I do think that making package name vary across releases will act as the "stick" to the "carrot" (of telling everyone the right way).

I did not realize that we had no indicator for "shaded" or "internal" as part of target package name (I usually add such a marker just for informational purposes) so even just adding that would be good. But version number seems like a nice addition.

I think this is preferable to changing FDP to regular dependency; there is value in being a 0-dependency package.
