### ISSUE TITLE
Deprecate `LockFreePool` implementation in 2.18 (remove from 3.0)

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-core#1271]
Due to reported issues wrt Lock-Free pool implementation (temporarily used as the default `RecyclerPool` for 2.17.0), its use seems dangerous. If we cannot solve (or at least severely mitigate) the problems, it seems necessary to deprecate this implementation, and remove from 3.0.

No decision is yet made but I created this issue so we can consider it.

**Comment by JooHyukKim** [comment]
(Just connecting things) Issue stemmed out from https://github.com/FasterXML/jackson-core/issues/1260#issuecomment-2067503269

**Comment by cowtowncoder** [comment]
Deprecated in 2.18; removed from 3.0 (master).
