### ISSUE TITLE
Add back Java 22 optimisation in fastdoubleparser

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-core#1277]
The pom.xml removes the Java 22 classes for fastdoubleparser. Maven Shade plugin settings. Will also need to add a relocation setting.

It should be safe to add them back now. Build tools have releases that support Java 22 format classes.

**Comment by cowtowncoder** [comment]
Let's do that for 2.18, however, to reduce risk for 2.17.1.
