### ISSUE TITLE
How to change default RecyclerPool for 2.17.0 ?

### ISSUE THREAD

**Issue by artemus717** [FasterXML/jackson-core#1293]
Maybe there are some memory leak issue with 2.17.0. We are running OpenSearch 2.14.0 which use jackson-core 2.17.0.
I want to try change default RecyclerPool to see if jvm heap will back to normal.

Thanks

**Comment by plokhotnyuk** [comment]
You can add `.recyclerPool(JsonRecyclerPools.threadLocalPool())` when building `JsonFactory` like [here](https://github.com/plokhotnyuk/jsoniter-scala/commit/1e63c528aee4019eef60a03f60d6ee118bb40fc7#diff-0c9c23a32e298e1b145eae6f31b4cc33b09d945b7459852f5104fd436eeec87aL32), but a better option is to upgrade to 2.17.1 or above.

**Comment by pjfanning** [comment]
relates to #1256

**Comment by artemus717** [comment]
> You can add `.recyclerPool(JsonRecyclerPools.threadLocalPool())` when building `JsonFactory` like [here](https://github.com/plokhotnyuk/jsoniter-scala/commit/1e63c528aee4019eef60a03f60d6ee118bb40fc7#diff-0c9c23a32e298e1b145eae6f31b4cc33b09d945b7459852f5104fd436eeec87aL32), but a better option is upgrading `jackson-core` to `2.17.1` or above.

did 2.17.1 not use lock free pool as default ?

**Comment by artemus717** [comment]
OK I changed to 2.17.1 in my OpenSearch cluster to see if it's OK.

Thanks
