### ISSUE TITLE
info required for compatible version with openjdk21

### ISSUE THREAD

**Issue by sahil3390** [FasterXML/jackson-core#1298]
Hello team,

Which version of below Jackson components are compatible with openjdk21:
Jackson-core
Jackson-databind
jackson-annotations
Jackson-dataformat-yaml

Regards,
Sahil

**Comment by pjfanning** [comment]
The java team try very very hard to keep compatibility across releases. This means that we don't need to expend massive effort to test with every possible Java version.

Try it out for yourself and get back if you find an issue.

**Comment by cowtowncoder** [comment]
To add to this: most components have CI with JDK 21 as one of JDKs used for running. All core (jackson-annotations, jackson-core, jackson-databind) work with JDK 21.
In fact there are no FasterXML Jackson components that would specifically NOT work on JDK 21.

Question usually is whether there are smaller issues running on JDK 21, edge cases, behavior differences. Not so much yes/no answer.
