### ISSUE TITLE
After Jackson serializes a large number of objects, the metadata space of the JVM cannot be freed

### ISSUE THREAD

**Issue by dylan-tao** [FasterXML/jackson-core#1321]
**Version：** 2.13.5

**Description：** After Jackson serializes a large number of objects, when the Classloader unloads the loaded class, Jackson refers to the serialized object and cannot free the JVM's metadata space

**Expectation：** When the classloader unloads a loaded class, it can explicitly manually release or unload the serialized class, allowing the JVM to automatically reclaim and release it when the meta space is full

**Comment by cowtowncoder** [comment]
`ObjectMapper` will cache serializers and deserializers, which will have to depend on classes being handled (via Reflection-accessed Methods, Fields etc).
There is no way around that; (de)serializer caching/reuse is an absolute must for performance reasons.

But as long as you drop reference to `ObjectMapper` (and possible `ObjectReader`s, `ObjectWriter`s), those references would go away.
Perhaps you can use Soft- (or was it Weak-) Reference for mapper if this is important thing to do.

**Comment by pjfanning** [comment]
@cowtowncoder @dylan-tao TypeFactory has a singleton instance that may hold onto Class references.

Its cache can be cleared explicitly using:
```
com.fasterxml.jackson.databind.type.TypeFactory.defaultInstance().clearCache();
```

**Comment by cowtowncoder** [comment]
Good point, @pjfanning. It's an unfortunate thing, global stateful (wrt caching) singleton :-(

**Comment by dylan-tao** [comment]
> @cowtowncoder @dylan-tao TypeFactory has a singleton instance that may hold onto Class references.
> 
> Its cache can be cleared explicitly using:
> 
> ```
> com.fasterxml.jackson.databind.type.TypeFactory.defaultInstance().clearCache();
> ```

Thanks, I'll test it and wait for my good news.

**Comment by dylan-tao** [comment]
> Good point, @pjfanning. It's an unfortunate thing, global stateful (wrt caching) singleton :-(



> @cowtowncoder @dylan-tao TypeFactory has a singleton instance that may hold onto Class references.
> 
> Its cache can be cleared explicitly using:
> 
> ```
> com.fasterxml.jackson.databind.type.TypeFactory.defaultInstance().clearCache();
> ```
Unfortunately, it still cannot be released. I found that the jackson cache in the following figure has not been released. Can you provide the cache release method in the information?
<img width="783" alt="企业微信截图_17219901112254" src="https://github.com/user-attachments/assets/624fb5ff-1643-4357-8d77-5e7f64fed669">
<img width="767" alt="企业微信截图_17219906612318" src="https://github.com/user-attachments/assets/15af65f1-fea5-421b-a646-e6279986b121">

**Comment by dylan-tao** [comment]
> > Good point, @pjfanning. It's an unfortunate thing, global stateful (wrt caching) singleton :-(
> 
> > @cowtowncoder @dylan-tao TypeFactory has a singleton instance that may hold onto Class references.
> > Its cache can be cleared explicitly using:
> > ```
> > com.fasterxml.jackson.databind.type.TypeFactory.defaultInstance().clearCache();
> > ```
> 
> Unfortunately, it still cannot be released. I found that the jackson cache in the following figure has not been released. Can you provide the cache release method in the information? <img alt="企业微信截图_17219901112254" width="783" src="https://private-user-images.githubusercontent.com/13051685/352505584-624fb5ff-1643-4357-8d77-5e7f64fed669.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5OTE0OTUsIm5iZiI6MTcyMTk5MTE5NSwicGF0aCI6Ii8xMzA1MTY4NS8zNTI1MDU1ODQtNjI0ZmI1ZmYtMTY0My00MzU3LThkNzctNWU3ZjY0ZmVkNjY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDEwNTMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjMGEwYmIyMjZjZDgxZjA1OTVjYTgxOTZlZDU2ZDg1NjExYTA2YWQ0YmYxNmU5YThkZjdjOTc1YjA0NjNkZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-2XUyxr0CAHm6YoesGBGW6jGreAoDSxNCwoPVzswYXY"> <img alt="企业微信截图_17219906612318" width="767" src="https://private-user-images.githubusercontent.com/13051685/352505625-15af65f1-fea5-421b-a646-e6279986b121.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5OTE0OTUsIm5iZiI6MTcyMTk5MTE5NSwicGF0aCI6Ii8xMzA1MTY4NS8zNTI1MDU2MjUtMTVhZjY1ZjEtZmVhNS00MjFiLWE2NDYtZTYyNzk5ODZiMTIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDEwNTMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3YTZlZjg1MjJlNTZiNGM2NzYxMTZlOTI4NGFkYzhhMzM5ZmJjNTVhOTVmMzkxNDZmNzFmM2RhM2NlODEwNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NbMkLNR5M-5h2wjfoq7bbtCLKULKqGpFEfZSX_WiYr4">

If you want to view it in real time, I provide the log of the stack, and import and analyze the following files through [Eclipse Memory Analyzer](https://eclipse.dev/mat/downloads.php) to see the relevant jackson reference information in the figure above.

Heap File：
Eclipse Memory Analyzer：https://eclipse.dev/mat/downloads.php

**Comment by pjfanning** [comment]
Would you not consider using microservices? If having the overhead of a couple of classes in memory is a really big worry, I think you really need to be reconsidering your architecture.

**Comment by pjfanning** [comment]
The ReadOnlyClassToSerializerMap instance lifecycle should closely match the SerializerCache lifecycle and the SerializerCache should be GCable after you dereference the ObjectMapper instance that it relates to.

**Comment by cowtowncoder** [comment]
Yes, the remaining retention is wrt Serializer caching & makes sense since there are typically many more serialized value types (as it's the exact runtime type vs statically declared for deserialization).
And to drop those caches it is necessary to drop `ObjectMapper` (and `ObjectWriter`s created from one, if any, but they are usually one-offs being light-weight).

**Comment by dylan-tao** [comment]
@pjfanning @cowtowncoder  yeah solved, solution read and write locks control the lifecycle of an ObjectMapper instance, class descriptions and instance references will be recycled, thanks！

**Comment by cowtowncoder** [comment]
Created https://github.com/FasterXML/jackson-databind/issues/4659 to address this for Jackson 3.0 -- `TypeFactory` life-cycle should be bound to individual `ObjectMapper` to avoid having to trigger clearCaches` on global default `TypeFactory` instance.
