### ISSUE TITLE
estimated release date for version 2.18

### ISSUE THREAD

**Issue by vther** [FasterXML/jackson-core#1324]
I would like to use this feature #1310   to fix a urgen security issue in my project, so I want to know when 2.18 will be released. 
Thanks for the reply.

**Comment by cowtowncoder** [comment]
Please don't file issues for asking questions: mailing lists are for that. Or, discussion on `jackson` repo.

As to 2.18.0, hoping to get RC1 out by end of August (2 weeks), then 2-4 weeks after, 2.18.0 final. If all goes well. So sometime in September 2024, I hope.
