### ISSUE TITLE
Update wiki section for INCLUDE_SOURCE_IN_LOCATION to reflect its default value change

### ISSUE THREAD

**Issue by izeye** [FasterXML/jackson-core#1330]
It would be nice to update [the wiki section for the `INCLUDE_SOURCE_IN_LOCATION`](https://github.com/FasterXML/jackson-core/wiki/StreamReadFeatures#misc-other) to reflect its default value change made in https://github.com/FasterXML/jackson-core/issues/991.

**Comment by cowtowncoder** [comment]
Tried improving Wiki slightly: LMK how it looks.

**Comment by izeye** [comment]
@cowtowncoder Looks good to me. Thanks!

**Comment by cowtowncoder** [comment]
@izeye great! And thanks for pointing outing the missing piece.
