### ISSUE TITLE
Missing `JsonFactory` "provides" SPI with JPMS in `jackson-core` module

### ISSUE THREAD

**Issue by rashtao** [FasterXML/jackson-core#1340]
SPI does not work in Java projects using JPMS, since `module-info.java` does not contains any `provides` directive.

To reproduce, I created a Java project with:
- `module-info.java`
  ```java
  module foo {
      requires com.fasterxml.jackson.core;
      uses com.fasterxml.jackson.core.JsonFactory;
  }
  ```
- `main`
  ```java
  public static void main(String[] args) {
        Optional<JsonFactory> jf = ServiceLoader.load(JsonFactory.class).findFirst();
        System.out.println(jf.isPresent()); // --> false
  }
  ```

**Comment by cowtowncoder** [comment]
Interesting, I thought `provides` was included as format modules do that.

My main/only concern is that in this case it'd be something like

```
provides com.fasterxml.jackson.core.JsonFactory with
        com.fasterxml.jackson.core.JsonFactory;
```

which I am not sure works as expected (`JsonFactory` is only sub-classed by format module implementations in 2.x, basic `JsonFactory` implements JSON support)

**Comment by cowtowncoder** [comment]
@rashtao Would it be possible for you to locally build from `2.18` branch, with modified `src/moditect/module-info.java` to add "provides" directive, and check if that'd work? I can make PR, change, but woudl need someone to validate proposed fix.

**Comment by rashtao** [comment]
Hi @cowtowncoder ,
I have manually checked that the changes work when building from `2.18`. Thanks!

**Comment by cowtowncoder** [comment]
Thank you for confirming @rashtao ! I hope to release 2.18.0 by end of week.

**Comment by GedMarc** [comment]
Unrelated to https://github.com/FasterXML/jackson-databind/issues/4727
