### ISSUE TITLE
JsonGenerator.writeNumber(BigDecimal bd) truncates/round off the value

### ISSUE THREAD

**Issue by ghost** [FasterXML/jackson-core#161]
I am using FasterXml/Jackson-core-2.2.0 and Jackson-databind jars to generate JSON document from the Java data structure (Kind of Map).

Initially I have encountered this issue (rounding 13699.80999999999950000000 to 13699.81) when writing values of type BigDecimal using JsonGenerator.writeNumber(BigDecimal value) .

Sample snippet from my code

{{{
else if(value.getClass().equals(BigDecimal.class))
{
BigDecimal bdValue = new BigDecimal(value.toString());
generator.writeString(bdValue.toPlainString());
}
}}}

and i am getting following result

{{{
{
"w_bigDec": "13699.80999999999950000000"
}
}}}

I need (Expected result) to remove quotes surrounded by the bigDecimal value like 
{
"w_bigDec": 13699.80999999999950000000
}

Then i tried,
BigDecimal bdValue = new BigDecimal(value.toString());
generator.writeString(bdValue.toPlainString());

but, still facing issue of getting value in JSON doc enclosed in quote ("13699.80999999999950000000").

Is there any open issue while writing a BigDecimal value in Json document...?
What is the best/recommended way to deal with this problem?

**Comment by babu-bhaia** [comment]
I am also having the same issue. 1.70 is written as 1.7. I am dealing with money here and always want to maintain 2 decimal places.

**Comment by cowtowncoder** [comment]
@babu-bhaia Please do not add comments on continuing problems on closed issues. If you have problem that persists with new versions (2.9), please file a new issue with full reproduction. Also
