### ISSUE TITLE
Add 'JsonGenerator.writeString(Reader r, int charLength)'

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-core#17]
Current 'writeString()' method requires text value to be passed in its entirety. This may not work well with larger payloads; so we should an alternative method where one can define source for text, used for incremental/streaming read+write.
In addition to Reader, it should be possible to indicate exact number of bytes to include; this because some formats (not JSON however!) require such information to be written before data, or used for initializing write. It should be possible to pass marker value -1 to indicate "not known": not all generators are required to support it, however.

If length is indicated, it is an error for Reader to provide less data (more is ok; generator just will not read anything beyond indicated amount).

**Comment by terziele** [comment]
#309

**Comment by cowtowncoder** [comment]
Thank you for contributing this! I hope to look into it soon, but at this point I have bit of a backlog with issues so it may take couple of days. But I wanted to add a note to know I am aware of this PR.

**Comment by terziele** [comment]
>But I wanted to add a note to know I am aware of this PR.
Sorry didn't understand the last thing, can you explain me what do you mean?

**Comment by cowtowncoder** [comment]
Another quick note: I plan on merging this after `2.8.2` gets released, and I can change master to be `2.9.0-SNAPSHOT``. At that point adding new features is possible, and this can go in. Thank you for your patience!

**Comment by uhhhh2** [comment]
I have an idea for a fix at https://github.com/uhhhh2/jackson-core . How does it look so far? Where would be a good place to create a unit test?

**Comment by cowtowncoder** [comment]
@uhhhh2 Please create a PR if you have a solution that you think works.

**Comment by uhhhh2** [comment]
#353

**Comment by cowtowncoder** [comment]
Merged, to be included in 2.9.0.

@uhhhh2 Thank you contributing this!
