### ISSUE TITLE
ObjectMapper.valueToTree inconsistent with eg. ObjectMapper.writeValueAsString

### ISSUE THREAD

**Issue by tvkampen** [FasterXML/jackson-core#175]
It looks like that `ObjectMapper.valueToTree` ignores enabled features, and in general outputs something very different than methods which actually produce JSON, such as `ObjectMapper.writeValueAsString`.

For example, when serializing a `BigDecimal` with value `100`, the methods which produce JSON will write a value of `100`, whereas the `valueToTree` method will always write `1E+2`. Even when the `WRITE_BIGDECIMAL_AS_PLAIN` feature is enabled (although even when that feature is _disabled_, the `writeValueAsString` writes `100`, _not_ `1E+2`).

Simple JUnit test case which proves this:

```java
public class JacksonTreeTest {

    @Test
    public void testValueToTreeInconsistency() throws Exception {
        ObjectMapper objectMapper = new ObjectMapper().enable(SerializationFeature.WRITE_BIGDECIMAL_AS_PLAIN);

        BigDecimal bigDecimal = new BigDecimal(100);
        JsonNode valueToTree = objectMapper.valueToTree(bigDecimal);

        String string = objectMapper.writeValueAsString(bigDecimal);
        JsonNode readTree = objectMapper.readTree(string);
        
        Assert.assertEquals(readTree, valueToTree);
    }
}
```

**Comment by tvkampen** [comment]
Well, the `readTree` was only used to have two `JsonNode` objects to compare, but is not strictly necessary for this particular unit test, to prove the output is invalid. This will do, too:

```java
@Test
public void testValueToTreeInconsistency() throws Exception {
    ObjectMapper objectMapper = new ObjectMapper().enable(SerializationFeature.WRITE_BIGDECIMAL_AS_PLAIN);

    BigDecimal bigDecimal = new BigDecimal(100);
    JsonNode valueToTree = objectMapper.valueToTree(bigDecimal);

    Assert.assertEquals("100", valueToTree.asText());
}
```

Which results in:
```
org.junit.ComparisonFailure: 
Expected :100
Actual   :1E+2
```

If instead `objectMapper.writeValueAsString(bigDecimal);` is used, it will pass (as that outputs `100` correctly).

This is using Jackson 2.5.0-rc1 through Maven:

```xml
<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-core</artifactId>
    <version>2.5.0-rc1</version>
</dependency>

<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-databind</artifactId>
    <version>2.5.0-rc1</version>
</dependency>
```

**Comment by cowtowncoder** [comment]
Ok thank you -- I will try to see what gives. Equality is tricky part all in all (multiple levels of rules); and the fact that JSON token `100` would be read as `int` (or, more generally, one textual representation goes to just one internal one, with given settings), but multiple number types can be serialized as `100` makes it unlikely that it is possible to retain exact type round-trip.

But I think there is also a simpler problem to solve here to improve things.

**Comment by cowtowncoder** [comment]
Ah! The reason I could not reproduce this was that I had:

```java
        ObjectMapper mapper = new ObjectMapper()
                .enable(JsonGenerator.Feature.WRITE_BIGDECIMAL_AS_PLAIN);
```

instead of your test that used

```java
new ObjectMapper().enable(SerializationFeature.WRITE_BIGDECIMAL_AS_PLAIN);
```

and this makes the difference. I'll try to see if I can resolve the problem with this feature, but it is worth noting it is actually deprecated in 2.5, since `JsonParser.Feature` and `JsonGenerator.Feature` flag configuration is now better supported. So I would recommend using `JsonGenerator.Feature.WRITE_BIGDECIMAL_AS_PLAIN` instead, if you can upgrade to 2.5.0 (which was just released couple of days ago).

**Comment by cowtowncoder** [comment]
Unfortunately the fix for 2.4 is not straight-forward; and the reason for deprecating `SerializationFeature` was partly due to it being difficult to ensure it gets properly propagated.

I will mark this as fixed, considering work-around of using `JsonGenerator.Feature.WRITE_BIGDECIMAL_AS_PLAIN`.

**Comment by tvkampen** [comment]
@cowtowncoder I am interested to see what test case you used specifically, if not the one I provided? I ran my test using Jackson `2.5.0` and `JsonGenerator.Feature.WRITE_BIGDECIMAL_AS_PLAIN` (instead of the now deprecated `SerializationFeature`), and my test still fails:

```java
@Test
public void testValueToTreeInconsistency() throws Exception {
    ObjectMapper objectMapper = new ObjectMapper().enable(JsonGenerator.Feature.WRITE_BIGDECIMAL_AS_PLAIN);

    BigDecimal bigDecimal = new BigDecimal(100);
    JsonNode valueToTree = objectMapper.valueToTree(bigDecimal);

    Assert.assertEquals("100", valueToTree.asText());
}
```

```
org.junit.ComparisonFailure: 
Expected :100
Actual   :1E+2
```

So it seems to me this is still an issue: the feature `JsonGenerator.Feature.WRITE_BIGDECIMAL_AS_PLAIN` is ignored when using `ObjectMapper#valueToTree`.

But perhaps I made an error in this test?

**Comment by cowtowncoder** [comment]
Test I added earlier is

src/test/java/com/fasterxml/jackson/databind/node/TestNumberNodes.java

and it passes for me. However, I notice you are using `valueToTree.asText()`. This probably fails because it has no access to generator you configure. In general, node.toString() is only useful for debugging and not for anything else.
