### ISSUE TITLE
Jackson-2.5 is not backwards compatible with Jackson-2.4

### ISSUE THREAD

**Issue by ansell** [FasterXML/jackson-core#178]
The fix for issue #166 resulted in non-backwards compatible code.

Specifically the following line compiles in Jackson-2.4 but fails in 2.5:

Lf2SpacesIndenter indenter = Lf2SpacesIndenter.instance.withLinefeed("\n")

Is it possible to reinstate that method signature (ie, don't just inherit it from DefaultIndenter) to provide backwards compatibility between 2.5 and 2.4?

**Comment by cowtowncoder** [comment]
Yes. Intention is not to change publicly visible API, so this is accidental incompatibility.

**Comment by ansell** [comment]
Thanks!
