### ISSUE TITLE
Eclipse Addon for JSONView?

### ISSUE THREAD

**Issue by renatoaraujoc** [FasterXML/jackson-core#180]
Hello,

Wouldn't it be a good idea to make an addon for Eclipse where we could view the effects of JSONView when we annotate our POJOS? The addon would scan a target project or maybe a project's package (containing annotated pojos (?))

Lets suppose we use the API Doc's example where "Public extends ExtendedPublic extends Private", we annotate a POJO called "Car", field by field and we'd use the addon to tell us exactly what fields will be serialized when we use the Public.class view or the ExtendedPublic.class view and so on.

This would make development so easier!

With best regards,

Renato Carneiro

**Comment by cowtowncoder** [comment]
Hi Renato. I think this sounds like a good idea to suggest on user or developer mailing list.
Sounds like it could be a useful addition.

**Comment by renatoaraujoc** [comment]
I have no idea how to access those mailing lists... I'm sorry for this...

**Comment by cowtowncoder** [comment]
No problem; they are regular Google groups, linked to from main Jackson portal project (https://github.com/FasterXML/jackson)

* https://groups.google.com/forum/#!forum/jackson-user
* https://groups.google.com/forum/#!forum/jackson-dev

But Github doesn't have enough organization to make it very easy to find all relevant information.
