### ISSUE TITLE
WRITE_NUMBERS_AS_STRINGS disables WRITE_BIGDECIMAL_AS_PLAIN

### ISSUE THREAD

**Issue by drekka** [FasterXML/jackson-core#184]
I need to have WRITE_BIGDECIMAL_AS_PLAIN on to ensure that numbers come out in the correct format. But I also need to have WRITE_NUMBERS_AS_STRINGS so that client software does not use floats. 

The bug is that when WRITE_NUMBERS_AS_STRINGS is on, it disables WRITE_BIGDECIMAL_AS_PLAIN rendering results like "1.25E+4" instead of "12500"

We need to have WRITE_NUMBERS_AS_STRINGS respect the WRITE_BIGDECIMAL_AS_PLAIN settings.

**Comment by cowtowncoder** [comment]
Thank you for reporting this -- will be fixed in 2.5.2.

**Comment by drekka** [comment]
Thanks.
