### ISSUE TITLE
Allow filtering content written via `JsonGenerator` by specifying `JsonPointer`

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-core#185]
(similar to #137, different direction)

For many dynamic use cases it would be nice to be able to only include a subset (subtree) of content that  is being written, so that, for example, a `JsonPointer` defines portion of a POJO is included in the output actually generated. While it would be more efficient to try to select subset before generation ability to define subsets dynamically make it more convenient to separate out parts.

**Comment by cowtowncoder** [comment]
Implemented, by adding new package `com.fasterxml.jackson.core.filter` and classes:

* `TokenFilter` for specifying filtering criteria; `JsonPointerBasedFilter` as a sample implementation
* `FilteringGeneratorDelegate` for actual generator that uses specified filtering strategy (`TokenFilter`)

**Comment by tlrx** [comment]
Awesome! :)
