### ISSUE TITLE
Longest collision chain in symbol table exceeds maximum length routinely in non-malicious code

### ISSUE THREAD

**Issue by mazzaferri** [FasterXML/jackson-core#187]
`BytesToNameCanonicalizer` since 2.4.x specifies a maximum collision chain length of 100 on the basis of the code comment that says:

> longest chain we have been able to produce without malicious intent has been 10

However, my non-malicious production code appears to routinely violate the maximum length. 

My project that serialises and deserialises classes containing `Map<Integer,T>` members for various `T`. Currently one of these maps contains more than 100k entries, where the Integers are entity IDs that are incremental starting from a small value and near-contiguous (e.g. much like a database auto-increment column after many inserts and some deletes). Deserialising this Map frequently causes the "Longest collision chain in symbol table ... exceeds maximum length" exception to be thrown by a `BytesToNameCanonicalizer` instance with jackson 2.4.4, but not with 2.3.x which had the higher limit. (I speculate that the higher limit would be routinely exceeded with large maps, but I have not tried it.) The exception is not deterministic presumably due at a minimum to the time-varying seed in the canonicalizer.

I have simplified this case to a test program that (de-)serialises a wrapper class that contains a single `Map<Integer,String>` instance. The program can synthesise a JSON string representing the wrapper class with an arbitrary map size using contiguous integer values for the map keys and a constant string for the map values, or directly load a JSON file. The program repeats the deserialisation operation with a fresh ObjectMapper and keeps simple stats on how many failures have occurred, as well as logging progress and the size of the symbol table reported in any exception's messages. It is compiled for a JDK1.6 target and executed under JDK1.8. I can supply the test program, but I don't see any way to attach it on the issue creation page.

The failure rate varies with the size of the map and can be noisy on repeated identical tests (presumably due to the time-varying seed - sometimes a test that often has a significant failure rate will run for several minutes without any failures). The exceptions I first observed were thrown for five digit keys which appear to be using a different hash than shorter keys, so I tested with generated JSON using keys starting at 1 and also at 10,001 which seems to make a large difference.

Some sample results (single test run per result, at least 10,000 deserialisation iterations):

Map size|Failure rate (initial key=10001)|Failure rate (initial key=1)
--------|------------|---------------
250,000|73%|10%
100,000|63%|16%
75,000|56%|6.7%
50,000|49%|0.6%
40,000|22%|0.4%
35,000|18%|0.16%
34,000|14%|0.15%
33,000|7.5%|0.02%
32,000|3.3%|&cong; 0.004%
31,000|&cong; 0.05%|
30,000|&cong; 0.03%|None in 100,000 iterations
29,500|&cong; 0.01%|

The symbol table size reported in the exception message does not seem directly related to the map size. The smallest one observed (from a limited sample of reports) was less than 9300 entries.

I presume Jackson should be able to reliably (de-)serialise large maps (even much larger than this), even if they employ (near-)sequential integer keys?

It would probably suffice for my current purposes if I could set the "fail on DOS" flag in the canonicaliser to false, but I'm not aware of a way to achieve that. Is the only workaround to turn off canonicalisation altogether?

**Comment by cowtowncoder** [comment]
Ah. Yes, the intent is definitely not to hit this limit on real use.

I think the simplest way to solve your problem might be to simply disable canonicalization of JSON Object field names. It can be done by

    jsonFactory.disable(JsonFactory.Feature.CANONICALIZE_FIELD_NAMES);

and the reason this probably makes sense is that you won't get much benefit from canonicalization (or from `String.intern()`, but that is only applied if canonicalization is used).

Alternatively if keys do repeat to some degree, it is also possible to prevent exception from being thrown, by disaling `JsonFactory.Feature.FAIL_ON_SYMBOL_HASH_OVERFLOW` (added in 2.4).

It does sound like limit could/should be raised, perhaps; and it is also possible that hash shuffling is not working as well as it should. Limits 
It would be interesting to see how things work with 2.6.0-SNAPSHOT, as symbol handling is rewritten and should avoid collisions better.

I would be interested in doing some testing locally; I think the only thing I need would be a way to regenerate integer/long ids you are using?

**Comment by mazzaferri** [comment]
Thanks Tatu.

I can send the stripped down version of the original map if it would help to see those IDs, but the test IDs should be sufficient. In tests so far they are simply sequential integers starting at either 1 or 10001, e.g.

```json
{
  "map" : {
    "1" : "abcde",
    "2" : "abcde",
    "3" : "abcde",
    "4" : "abcde",
    "5" : "abcde",
    "6" : "abcde",
    "7" : "abcde",
    "8" : "abcde",
    "9" : "abcde",
    "10" : "abcde",
    "11" : "abcde",
    "12" : "abcde",
```
...

and

```json
{
  "map" : {
    "10001" : "abcde",
    "10002" : "abcde",
    "10003" : "abcde",
    "10004" : "abcde",
    "10005" : "abcde",
    "10006" : "abcde",
```
...

In the real JSON the same integer ID will often appear in several different maps contained by the outermost object, so canonicalisation should be helping provided it works across those different maps. I'll try disabling `FAIL_ON_SYMBOL_HASH_OVERFLOW`.

**Comment by cowtowncoder** [comment]
Ok. For what it's worth, I tested collision with generated ids, but there was always a short String prefix, maybe that made difference. Actually I suspect this might be a weakness in hashing for 5-8 byte long names, something I noticed with 2.6 rewrite...

**Comment by cowtowncoder** [comment]
Ok: I patched things up a bit for 2.5, so beside disabling interning (which I think you may still want to do, depending) it should not be necessary to disable collision check.
Two main changes:

1. Increase max limit from 100 to 200 (still arbitrary, I know)
2. Improve hashing for the problem case (of 5-8 byte symbols), using shifting that produced shortest max-collision length

On plus side these should be safe changes, so I plan on including these for 2.5.2. I will also investigate situation with `master` (2.6.0-SNAPSHOT), to see how the new symbol table works. It does not have similar overflow detection, as the whole spillover area is shared. But it will suffer similarly from high collision rate, so I want to try to avoid excessive collision chains.

**Comment by mazzaferri** [comment]
Thanks Tatu.

**Comment by rrthomas** [comment]
I just hit this issue; just wanted to thank you both @mazzaferri and @cowtowncoder for working on this and providing both workarounds and a potential fix.

**Comment by cowtowncoder** [comment]
@rrthomas glad that this would useful. I am hoping to release 2.5.2 soon (there is one other important fix related to caching of custom (Map/List) deserializers), and just want to verify that both fixes are complete.

**Comment by rrthomas** [comment]
It may interest some users to know that the workaround specified above does not work for SMILE until version 2.5.1, as before then the SMILE parser did not use the new Feature-based JsonFactory constructor. (This had me scratching my head and running a debugger for a while to figure out!)

**Comment by cowtowncoder** [comment]
@rrthomas Good point, yes.

For what it is worth, 2.5.2 release is now getting out to Maven central and should be available. Scala module is not yet out (but will be soon), other components by FasterXML are.
