### ISSUE TITLE
UTF8JsonGenerator writes _charBuffer without populating it with values.

### ISSUE THREAD

**Issue by feczo** [FasterXML/jackson-core#194]
there is an issue with UTF8JsonGenerator class in jackson-core-2.6.0-rc1.jar.
The line 431 writes _charBuffer without populating it with values.

**Comment by cowtowncoder** [comment]
Yes, good catch. Looks like there was a gap in test coverage; I added a test to catch this case (it was a regression from 2.5, due to refactoring).

**Comment by feczo** [comment]
Thank you for the prompt action here!
