### ISSUE TITLE
Bug in 2.6.0-rc1

### ISSUE THREAD

**Issue by mkadan** [FasterXML/jackson-core#197]
Compared to 2.5.3 the following code is missing:

UTF8JsonGenerator.java:writeString:431

        // yes: good.
        text.getChars(0, len, _charBuffer, 0);

that makes serialization set long strings to a sequence of \u0000 instead of an actual text

**Comment by cowtowncoder** [comment]
Thank you for reporting this.

Yes, I think this is same as #194: fixed in master, will be in 2.6.0-rc2. I also improved unit tests to ensure this codepath is covered (it was assumed to have been, wasn't).
