### ISSUE TITLE
Javadoc fonts broken

### ISSUE THREAD

**Issue by Murmur** [FasterXML/jackson-core#200]
See this javadoc page, it goes well until all text fonts are resized.
http://fasterxml.github.io/jackson-core/javadoc/2.5/com/fasterxml/jackson/core/JsonGenerator.html#getCurrentValue%28%29

**Comment by cowtowncoder** [comment]
I suspect this would be due to a missing or mismatched HTML tag within javadoc.
Current version in `master` and `2.5` branch do seem to have properly closed `<code>` tag; perhaps 2.5.0 had two open tags?

**Comment by cowtowncoder** [comment]
I think code tag is properly closed now for 2.6.
