### ISSUE TITLE
Add ability to navigate with a JsonPointer in a JsonParser

### ISSUE THREAD

**Issue by marshallpierce** [FasterXML/jackson-core#201]
I'm mixing streaming mode and databinding so that I can deserialize only the parts of a document that I care about. It would be nice to be able to give a JsonPointer to a JsonParser rather than manually walking through the tokens to get to where I need to be.

**Comment by cowtowncoder** [comment]
Good idea.

Note that #137 is sort of related, although not quite the same.

**Comment by cowtowncoder** [comment]
I think that combination of `FilteringParserDelegate`, and databind level `mapper.at(...)`/`objectReader.at(...)` should suffice for now.
If additional/alternative mechanisms desired, may be re-filed with more concrete ideas of how to go about it.
