### ISSUE TITLE
can_override_access_modifiers & Mix-ins: bug on private class implementing public interface

### ISSUE THREAD

**Issue by fromi** [FasterXML/jackson-core#202]
Hi,

I switched "can_override_access_modifiers" to false on my project (security reasons).
I have a mix-in annotation:
```java
import com.fasterxml.jackson.annotation.JsonProperty;
import org.springframework.data.domain.Page;

import java.util.List;

public interface PageMixIn<T> extends Page<T> {
    @Override
    @JsonProperty
    long getTotalElements();


    @Override
    @JsonProperty
    List<T> getContent();
}
```
Let's focus on `getContent()`: this method is exposed by public interface [`Page`](https://github.com/spring-projects/spring-data-commons/blob/501f0c84932a2a92788b7f101bc34455e1152421/src/main/java/org/springframework/data/domain/Page.java). However, at runtime, I am serializing a [`PageImpl`](https://github.com/spring-projects/spring-data-commons/blob/3a2dc3d1d4cf041b59ec8e9c045307c9322c2c1f/src/main/java/org/springframework/data/domain/PageImpl.java). It is a public class, but it extends [`Chunk`](https://github.com/spring-projects/spring-data-commons/blob/master/src/main/java/org/springframework/data/domain/Chunk.java).
Chunk implements `getContent()`, but Chunk is a package protected class, and Jackson produce this message:
```
Could not write content :
Class com.fasterxml.jackson.databind.ser.BeanPropertyWriter
can not access a member of class org.springframework.data.domain.Chunk with modifiers \"public\"
(through reference chain: org.springframework.data.domain.PageImpl[\"content\"])
```
There are no reason to prevent access to this method, as it is exposed by a public interface. The fact that it is implemented by a package protected abstract class is not relevant.

As a workaround, I replaced my Mix-in by a custom serializer.
Have a nice day!

**Comment by cowtowncoder** [comment]
What is needed here is a reproducible test case. Physical limitations to access are indeed defined by actual physical method, and interface declaration is irrelevant. Logical visibility rules on the other hand are based on declaration in use, so for deserialization it may be based on interface.

But error message itself suggests physical access problem; and it is not possible to say anything about what triggers it with given partial information.

Another thing is that this bug actually would belong under

https://github.com/FasterXML/jackson-databind/issues

and not `jackson-core`, as this package only contains streaming parser and generator classes. But for now that is ok, and it is more important to be able to reproduce the issue.

Also: which version of Jackson is this with?

**Comment by fromi** [comment]
Hi, it's Jackson 2.4.5. I will try to create a unit test case, but I don't have time for that right now (it is not a blocker issue anyway). I encountered the problem in a Spring Boot project which is not open source.

**Comment by cowtowncoder** [comment]
One note on problem: being define in package-access protected class actually may be problematic: unlike protected (and even private) methods, non-accessible classes' access protections may not be changed, and methods sort of inherit this access.

**Comment by cowtowncoder** [comment]
Will close for now; if this can be reproduced it should be filed for `jackson-databind`
