### ISSUE TITLE
Typo of function name com.fasterxml.jackson.core.Version.isUknownVersion()

### ISSUE THREAD

**Issue by timrau** [FasterXML/jackson-core#211]
The name of function `com.fasterxml.jackson.core.Version.isUknownVersion()` is incorrectly spelled.
It should be `isUnknownVersion()`.

**Comment by cowtowncoder** [comment]
Yes, so it seems. Surprising no one noticed this before...

**Comment by cowtowncoder** [comment]
Added properly spelled variant, `isUnknownVersion()`, deprecated existing one. Can not really remove at this point, in case someone is calling that method; may be removed from 3.0, eventually.
Thanks!
