### ISSUE TITLE
ObjectMapper.copy() does not preserve _registeredModuleTypes

### ISSUE THREAD

**Issue by lorrin** [FasterXML/jackson-core#215]
Observed in debugger tracing through https://github.com/dropwizard/dropwizard/blob/15e561d70eb5b66ce9aa35620e8c7a4ea28b1d5b/dropwizard-configuration/src/main/java/io/dropwizard/configuration/ConfigurationFactory.java#L69

**Comment by cowtowncoder** [comment]
Moved to https://github.com/FasterXML/jackson-databind/issues/922
