### ISSUE TITLE
Problem with `singletonMap` (and set, list) not retaining its type

### ISSUE THREAD

**Issue by fzakaria** [FasterXML/jackson-core#218]
I have a jackson annotated class with a Map<String,Object> parameter.

It is being set to a SingletonMap

{"attributes":{"@class":"java.util.Collections$SingletonMap","PARAMETER_INPUT":{"@class":"com.github.fzakaria.sample.wf.SimpleParameterWorkflow$WorkflowParameter","name":"INPUT","time":"2015-09-19T14:47:23.491Z[America/Los_Angeles]","count":343}}}

Jackson cannot seem to build a SingletonMap (no default constructor).
Is there a way to instruct Jackson to exclude TypeInfo for all Collection interfaces (non-concrete)

**Comment by cowtowncoder** [comment]
Unfortunately this is not enough to reproduce the issue -- how are you enabling type info serialization? Are you using default typing perhaps? If so, you can create a custom handler for determining which classes type information is to be included for, instead of using the default implementation (with one of its 4 settings).

**Comment by fzakaria** [comment]
this.mapper = new ObjectMapper();
        mapper.registerModule(new JodaModule());
        mapper.registerModule(new Jdk8Module());

        //ignoring unknown properties makes us more robust to changes in the schema
        mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
        mapper.configure(SerializationFeature.FAIL_ON_EMPTY_BEANS, false);
        //Jackson deserializes normally as UTC however we want to retain timestamps.
        mapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
        mapper.configure(SerializationFeature.WRITE_DATES_WITH_ZONE_ID, true);
        // This will allow including type information all non-final types.  This allows correct
        // serialization/deserialization of generic collections, for example List<MyType>.
       mapper.enableDefaultTyping(ObjectMapper.DefaultTyping.OBJECT_AND_NON_CONCRETE,JsonTypeInfo.As.PROPERTY);


There are two problems here:

1 - Jackson cannot deserialize a singletonMap due to an exception regarding no suitable constructor found

2 - Deserializing a singletonMap means I am not able to modify the bean afterwards; similarly would be deserializing the type of ImmutableMap. I can see that might be desirable in some situations however in the case where you'd like to modify the deserialized bean it is not.
Considering that arrays and maps are native JSON types, it would be great if there was the ability to add type information for everything except native JSON types (which already seems to be done for Java primitives such as int, bool etc..)

**Comment by cowtowncoder** [comment]
You will need to implement your own handler for default typing, and register it via `ObjectMapper.setDefaultTyping(TypeResolverBuilder<?> b);`.
This allows you to tailor the exact rules you want. One thing to note is that it must be based on information known via `JavaType`, since there is no real way to know for certain what kind of JSON construct will be used. In practice you can use methods like `type.isCollectionLikeType()` (which includes JDK `List`s, arrays, as well as more exotic collections like Scala collections) to do what you want.

Existing default typing choices are limited and it is quite difficult to come up with an extensive enough list to cover different permutations -- there are definitely edge cases where they do not work, like yours.

**Comment by fzakaria** [comment]
1 ) Fair enough that it is impossible to cover the complete set of use cases. The fact that there is omitted type information for primitives of the JSON notation though seems to align with the edge case of omitting it for JSON collections (arrays and dictionaries) in my opinion.

2) I think a bug should still be open for the singletonMap as it is a java.util.collection and I would expect all native JDK collections to be serializable/deserializable?

http://docs.oracle.com/javase/7/docs/api/java/util/Collections.html#singletonMap(K,%20V)

**Comment by fzakaria** [comment]
I can take a peek myself at the source later today and see if I can find a suitable fix for a PR

**Comment by cowtowncoder** [comment]
@fzakaria I agree that singleton map should be serializable, and deserializable back as `Map`. As far as I know, this is the case. But I'll go ahead and add an explicit test just to be sure.

But when trying to add type information handling is tricky; if it can be handled, great, but if it requires dependencies to actual implementation class info (from JDK), then that may or may not be supportable.

As to default set of `DefaultTyping` values: unfortunately (for this case) semantics of existing choices need to remain solid, and any changes are likely to cause issues for existing users (well, possible; hard to say how likely).
I am open to adding a new value there, however, if you could suggest clear semantics, perhaps based on one of existing values, augmented with "and not for any Map or Collection types"?

**Comment by fzakaria** [comment]
Here some additional relevant information and a test case:

I fond that I am able to serialize/deserialize singletonMap only when it is the top level bean and it failed for nested beans with the following error

*Can not construct instance of java.util.Collections$SingletonMap, problem: No default constructor found*

Here is a failing Spock test (please excuse me if you don't know groovy/spock)

    class FailingJacksonSingletonMap extends Specification {

    def static mapper = new ObjectMapper();

    static {
    mapper.registerModule(new JodaModule());
    mapper.registerModule(new Jdk8Module());

    //ignoring unknown properties makes us more robust to changes in the schema
    mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
    mapper.configure(SerializationFeature.FAIL_ON_EMPTY_BEANS, false);
    //Jackson deserializes normally as UTC however we want to retain timestamps.
    mapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
    mapper.configure(SerializationFeature.WRITE_DATES_WITH_ZONE_ID, true);
    // This will allow including type information all non-final types.  This allows correct
    // serialization/deserialization of generic collections, for example List<MyType>.
    mapper.enableDefaultTyping(ObjectMapper.DefaultTyping.OBJECT_AND_NON_CONCRETE,JsonTypeInfo.As.PROPERTY);
    }

    def "serialize & deserialize nested singletonMap"() {
        when:
            def str = mapper.writeValueAsString(input)
            def output = mapper.readValue(str, HashMap.class)
        then:
            input == output
        where:
            input|_
            [singletonMap : Collections.singletonMap("test","test")]| _
    }

**Comment by fzakaria** [comment]
Finally as a recommendation for DefaultTyping how about

        
/**
* Value that means that default typing will be used for all non-concrete 
* types which are not native (natural) to the JSON format.
* Example of such types include: (String, Boolean, Integer, Double, Map, List)
NON_NATIVE

**Comment by fzakaria** [comment]
Btw, just so that semantics remain the same, singletonMap should remain as singletonMap (which is an immutable collection). The bug seems to be related to the fact that it is a nested type. Support for deserializing them seems to be present otherwise (and I see code for it in the API)
http://fasterxml.github.io/jackson-jr/javadoc/2.4/com/fasterxml/jackson/jr/ob/impl/MapBuilder.html

**Comment by cowtowncoder** [comment]
@fzakaria Problem with SingletonMap is that it is not a public JDK type -- actual implementation may be anything, as far as I understand, and since it is not public, one can not refer to it (via import statement).
While it can be instantiated via `Collections`, it seems dangerous to have to rely on class name; and it is a special case.

As to `NON_NATIVE`, I assume you are basically hoping for "only add types to custom POJOs", but there is really no way to detect that reliably.

**Comment by cowtowncoder** [comment]
Actually come to think of that, a bigger practical problem with singleton maps is that there is no way to construct it the way collections are constructed normally: by creating an instance and adding. Instead, singletons must be created via static methods. That would require a dedicated deserializer, which while doable in theory seems bit excessive.

One thing that I would probably prefer is to claim a more typical collection type, like simple `ArrayList`.
Given that actual implementation class is not standardized, I think this gets into level of detail that Jackson can not really handle.

**Comment by cowtowncoder** [comment]
One additional note: this bug belongs under `jackson-databind`, not core (which is just for streaming reading/writing). That's ok for now, but makes it easier to miss.

**Comment by cowtowncoder** [comment]
Will close due to misplacement; may be re-filed at `jackson-databind`.
