### ISSUE TITLE
Attempting to set a custom date within a bean serializer no longer works on 2.6.x.

### ISSUE THREAD

**Issue by nosachamos** [FasterXML/jackson-core#224]
In one of my apps a custom bean serializer needs to change the date format used to serialize it's content during runtime. This is done like so:

```
public void serialize(ResponseWrapper responseWrapper, JsonGenerator jgen,
        SerializerProvider provider) throws IOException, JsonProcessingException {
    	
ObjectCodec codec = jgen.getCodec();
ObjectMapper mapper;
if (codec instanceof ObjectMapper) {
  mapper = (ObjectMapper)codec;  		
} else {
  // this should never happen
  throw new IllegalStateException("Object codec is not of expected type.");
}

DateFormat sdf = ...

ObjectMapper configuredMapper = mapper.copy();
configuredMapper.setDateFormat(sdf);

jgen.setCodec(configuredMapper);

jgen.writeStartObject();
jgen.writeObjectField(fieldName, body);
jgen.writeEndObject();

...
}
```

That `body` object is a Map with string keys which contains a Date value that needs to be serialized according to the given custom date format configured on the `ObjectMapper` we set as the codec. 

It worked fine on 2.5.1 and 2.5.4, but after upgrading to 2.6.2 it no longer works. I debugged this, and the SerializerProvider has the correct config in it, which contains the correct date format. However, the  DateSerializer used to serialize the value has a null _customFormat field which is never configured to use the date format in the SerializerProvider's config.

**Comment by cowtowncoder** [comment]
This project is for the streaming parser/generator, and the problem is actually with databinding (although invoked via `JsonGenerator`, so the issue should be filed under

https://github.com/FasterXML/jackson-databind/issues

I would transfer it, but I don't think github has a way to do that from UI. Would it be possible for you to recreate this issue over `jackson-databind` project?

**Comment by nosachamos** [comment]
@cowtowncoder absolutely! I'm recreating it there right now. Thanks for the heads up!

**Comment by nosachamos** [comment]
@cowtowncoder Done, https://github.com/FasterXML/jackson-databind/issues/968

Thanks!
