### ISSUE TITLE
support nested property filters

### ISSUE THREAD

**Issue by krishna81m** [FasterXML/jackson-core#230]
Problem: If there is a class say Person

```
class Person {
   string name;
   int age;
   Address address;
   
   .. getters and setters
}
```
How do we dynamically filter specific nested properties: name, address.state, address.zipcode reusing the same object mapper/writer.

One way is to follow the Spring integration to use property filter https://jira.spring.io/browse/SPR-12586. However, nested property filters are not supported. This is because of the way Jackson integration works. This is a very common use case to get only the fields clients are interested in runtime.

There are a few implementations already available that are slow because they lookup the jgen root context to build the nested path every time a property is checked if it can be filtered. These implementations also won't work without explicitly adding JsonFilter annotation on all classes that will be filtered:
https://github.com/PressAssociation/partial-response/tree/master/filter-json-jackson
https://github.com/Antibrumm/jackson-antpathfilter
https://github.com/narusas/SpringMvcJacksonFilter

The following won't work without @JsonFilter("antPathFilter") on all classes

```
objectMapper.addMixIn(Object.class, AntPathFilterMixin.class);
filter = new SimpleFilterProvider()
			.addFilter("antPathFilter",
					new AntPathPropertyFilter("nestedObj", "nestedObj.nestedProperty")
jacksonValue.setFilters(filter);
```

One work around is to explicitly set the same @JsonFilter("antPathFilter") on all classes that are nested, which did not make any sense to me. What if I wanted to support multiple filters at the same time tomorrow?

I also ended up writing my own implementation that is fast and that uses SimplePropertyFilter per class built on the nested properties. 

**The problem really is the way Jackson APIs requests a filter for current property without any context on the current class owning that property.**

https://github.com/krishna81m/jackson-nested-prop-filter

**Comment by krishna81m** [comment]
Related ticket: https://jira.spring.io/browse/SPR-13622

**Comment by cowtowncoder** [comment]
This issue does not belong here as filters are implemented by `jackson-databind`; `jackson-core` only implements streaming `JsonParser`, and not databind level property filtering.
You may want to refile this for `jackson-databind`, along with bit more detail on what changes you would  want to see, from perspective of how the filter association should behave.

**Comment by krishna81m** [comment]
Makes sense, closing this ticket to create one for jackson-databind

**Comment by heruan** [comment]
Can you please provide a link to the `jackson-databind` issue? Thank you!
