### ISSUE TITLE
Adding properties to a HashMap using JsonAnySetter; no longer getting key deserialization

### ISSUE THREAD

**Issue by MichaelRFairhurst** [FasterXML/jackson-core#231]
I previously was deserializing the following fields via JSON

    private Map<CityStateCountrySplitter, Metrics> cityMetrics;
    private Map<Integer, Metric> dmaCodeMetrics;
    private Map<String, Metric> interestMetrics;

But suddenly the maps we were getting from this third party included some new fields:

    {"dmaCodeMetrics":{123:{...},456:{...},...,"raw_count":55},...}

So I moved over to use a new object that defines that new field plus @JsonAnySetter 

    // old class
    private Breakdown<CityStateCountrySplitter> cityMetrics;
    private Breakdown<Integer> dmaCodeMetrics;
    private Breakdown<String> interestMetrics;

    // Breakdown.java
    private int raw_count;
    private Map<T, Metrics> metrics;

    @JsonAnySetter
    public void addBreakdownPoint(T key, Metrics value) {
        metrics.add(key, value);
    }

At first everything seemed to work. @JsonAnySetter figures out to deserialize my value as a Metrics object, and deserialization doesn't throw any exceptions. But jackson always passes a String into 'key'. Thanks to erasure, it happily accepts the wrong data, until I go to use it where I get class cast exceptions.

Not sure if you would call this a feature request or a bug. If its a feature request or if the bug will take a while to get fixed, I'll need a workaround, and I'm still not sure what is best to do. My first thought is to try and reify the types. Ie

    public class Breakdown<T> {
        public Breakdown(T classType) {
             this.classType = classType;
        }

        @JsonAnySetter
        public void addBreakdownPoint(String key, Metrics value) {
             metrics.add(T.newInstance(key), value);
        }

but jackson requires a no-arg constructor.

The only other alternative that comes to mind is to make my POJO stringly typed everywhere and convert things on the way out. Stringly typed coding is not my preference.

Are there any workarounds anyone can suggest for me in the meantime?

**Comment by cowtowncoder** [comment]
Could you please re-file this for `jackson-databind`, since `jackson-core` only deals with streaming parser/generator? I would move it, but github does not appear to have functionality to do that unfortunately.

Also, could you indicate Jackson version you have verified the problem against (assuming 2.6.3).

**Comment by cowtowncoder** [comment]
One other thing: would it be possible to have a more complete example, ideally self-contained unit test, but if not, at least POJO with fields. The reason being that generic type handling strongly depends on resolution.

**Comment by MichaelRFairhurst** [comment]
Sorry for the delay. Can do!
