### ISSUE TITLE
Jackson custom parsing error

### ISSUE THREAD

**Issue by xnull** [FasterXML/jackson-core#233]
Hi, I found an error. Or is it feature?
Jackson doesn't parse "result" field:
```
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.module.SimpleModule;
import org.junit.Test;

import java.io.IOException;

import static org.junit.Assert.assertTrue;

public class JacksonTest {

    @Test
    public void testTest() throws Exception {
        String json = "{\"data\": {\"customField\": \"custom data\"}, \"result\": true}";

        MyGenericMessage<MyWeirdObject> obj = JsonUtil.objectMapper.readValue(json, new TypeReference<MyGenericMessage<MyWeirdObject>>() {
        });

        assertTrue(obj.result);
    }

    public static class JsonUtil {
        private static final ObjectMapper objectMapper = build();

        private static ObjectMapper build() {
            SimpleModule module = new SimpleModule();
            module.addDeserializer(MyWeirdObject.class, new MyDeserializer());

            ObjectMapper mapper = new ObjectMapper();
            mapper.registerModule(module);

            return mapper;
        }
    }

    public static class MyDeserializer  extends JsonDeserializer<MyWeirdObject> {
        @Override
        public MyWeirdObject deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException {
            jp.nextValue();

            MyWeirdObject obj = new MyWeirdObject();
            obj.name = jp.getValueAsString();
            return obj;
        }
    }

    public static class MyGenericMessage<T> {
        public boolean result;
        public T data;
    }

    public static class MyWeirdObject {
        public String name;
    }
}
```

**Comment by cowtowncoder** [comment]
Looks like your `MyDeserializer` is written incorrectly, as it is not checking the current value but is blindly calling "nextValue()", and most likely advancing it to the next property. If value is always expected to be a String, just drop that `nextValue()`. But code should probably verify the token type, in case someone passes it some other JSON value, like Object or Array; if so, code that just assumes String will not work correctly, nor indicate the problem.

**Comment by xnull** [comment]
Hi, you are right but I am talking about "result" field not about "data" field. MyDeserializer would be:
```
@Override
        public MyWeirdObject deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException {
            return null;
        }
```
The question is: why boolean field ("result") wasn't parsed?

**Comment by xnull** [comment]
I didn't get any parsing errors and I hadn't any troubles with a deserializer

**Comment by cowtowncoder** [comment]
First: there is just a single parser offset, so advancing stream earlier would cause missing of contents of following field. There would be no immediate error as framework does not try to keep limits of what deserializers may consume -- if you write custom deserializers, you need to know what you are doing.

As to `MyDeserializer`, it would work for case of scalar JSON types that have just one token, but would fail if content had JSON Object or Array; contents would not be consumed. So it should call `skipChildren()` to be safe, or verify that current token is not array/object.

At this point you really should try debugging this yourself to verify what tokens are seen at what point; you are using a custom deserializer that has a problem that I pointed out.
