### ISSUE TITLE
Problem in Android Studio when building with gradle Duplicate Files error

### ISSUE THREAD

**Issue by firetrap** [FasterXML/jackson-core#240]
The problem it's all your core libs have the same META-INF/LICENSE and META-INF/NOTICE files and the gradle can't handle the same file name. So if possible why not add a prefix to the filename?

Example: META-INF/CORE-NOTICE and META-INF/DATABIND-NOTICE etc etc...

We android devs love your work but it's a pain to be always adding special config params to the multiple Build.gradle files present in some projects.

Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/LICENSE
	File1: C:\Users\firetrap\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-core\2.5.5\d0b416837b2b3907f298db2f785e9012b6881515\jackson-core-2.5.5.jar
	File2: C:\Users\firetrap\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-annotations\2.5.0\a2a55a3375bc1cef830ca426d68d2ea22961190e\jackson-annotations-2.5.0.jar
	File3: C:\Users\firetrap\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-databind\2.5.5\b08c3194166a230e60f56ac98bcd5cab5ee39d65\jackson-databind-2.5.5.jar

**Comment by cowtowncoder** [comment]
I think this is up to android tools to fix; I do not want to deviate from common naming practice here.

**Comment by firetrap** [comment]
I understand but it's not a problem from android but a limitation from the
Gradle build system I use a lot the Jackson libs and when the project it's
Gradle I already know I will struggle with some of this problems.

But thanks for all of your work and had the time to answer me.

Regards, firetrap

**Comment by cowtowncoder** [comment]
@firetrap I should rephrase what I meant -- I would like to find a way to help with this situation. But I would hope there is a way to do that without having to use distinct names for these metadata entries, which are expected to be specific ones for other tooling chains to work.
But I do not know quite what that would be.

The reason I assumed this is Android tooling issue is that there were earlier problems which we resolved, related to location of these resources. Specifically there are/were severe performance issues when including non-class-file entries outside of META-INF. But perhaps this is not related.

So, anyway, I am open to suggestions for alternatives to help situation here.

**Comment by firetrap** [comment]
Honestly i agree with you, you're following the good practices and should keep it, it's bad that the Gradle team can't figure out a fix or good alternative to fix the problem. Keep the good work ;)

**Comment by nallwhy** [comment]
Is there anyway to solve this problem?
I'm using Android Studio 2.0 Preview 4 and have tried to add the code below, but it doesn't works.
```
android {
  ...
  packagingOptions {
    exclude 'META-INF/LICENSE.txt'
    exclude 'META-INF/NOTICE.txt'
  }
  ...
}
```

**Comment by cowtowncoder** [comment]
@nallwhy correct: no `.txt` suffix is used: it's "META-INF/LICENSE" and "META-INF/NOTICE".

**Comment by 6franek** [comment]
@cowtowncoder How does this solution relate to the Apache-2.0 license, which says that one must add the license file to each copy of the distributed program which contains a library on the basis of this license?

**Comment by cowtowncoder** [comment]
@6franek I think that whatever is done with other libraries with Apache license is acceptable to us. Perhaps you can drop the license from jar, and include equivalent information in file/resource/gui page that is more convenient for you to package?

Basically we do not care about specifics ("letter" of the license) as much as the intent ("spirit" of the license) -- licensing should be noted somewhere, and if the default mechanism does not work, then other inclusion mechanisms are acceptable.

**Comment by 6franek** [comment]
@cowtowncoder I am developing a commercial application in which I use another open-source library (under MIT license), which uses your library. I haven't found any other solution yet, that's why I would like to be 100% sure that I am not violating your copyrights.

**Comment by cowtowncoder** [comment]
@6franek Correct: while inclusion of license would be ideal, if it can not be done due to collision we would be happy with some other reasonable alternative. Even if is something very simple like a text filed name `LICENSE` in main level of jar, listing jars along with licenses. That is, text file you create and add as part of build, not something build system has to create.

**Comment by cowtowncoder** [comment]
Not much that can be done here, closing.

**Comment by TugbaGonultas** [comment]
@nallwhy I tried to edit packagingOptions, but anything didn't change. I am using to Android 3.0. Can you give a idea?

**Comment by AjuanM** [comment]
les mando una captura sobre el problema que han puesto 
les dejare un enlace http://prntscr.com/hts0r6 es una captura estoy utilizando Android Studio 2.2.3
saludos desde Perú

**Comment by NabAziz** [comment]
packagingOptions {
        exclude 'META-INF/proguard/coroutines.pro'
        }
