### ISSUE TITLE
VersionUtil.versionFor() unexpectedly return null instead of Version.unknownVersion() stated in JavaDoc

### ISSUE THREAD

**Issue by sammyhk** [FasterXML/jackson-core#248]
As titled, after commit of 88c296c67391f6dea4c1581caa82d801c5d94535 , it unexpectedly return `null` instead of `Version.unknownVersion()` which cause our application broken after upgrade from 2.4.x to 2.6.x.

**Comment by cowtowncoder** [comment]
Thank you for reporting this. Looks like unintended consequence of refactoring; will fix.
