### ISSUE TITLE
Add functionality for canonical serialization of JSON floating-point numbers, for ES6 (and V8) compatibility

### ISSUE THREAD

**Issue by cyberphone** [FasterXML/jackson-core#252]
Related:
https://github.com/Microsoft/ChakraCore/issues/149

**Comment by cowtowncoder** [comment]
I would need bit more explanation of what exactly this means. I am not against alternate modes for interoperability, but would want to know what is requested.

**Comment by cyberphone** [comment]
It means that formatting a JS Number should adhere to ES6/V8.  Java's default Double.toString() does not.  The use-case for this is creating clear text JSON signatures that also can work in a browser.

The link to "Chakra" provides detailed information on the use case.

**Comment by cowtowncoder** [comment]
@cyberphone Ok, let's hope someone has an itch and wants to work on that, based on information provided.

**Comment by cowtowncoder** [comment]
I don't think anyone is working on this, or has plans. Closing.
