### ISSUE TITLE
`BytesToNameCanonicalizer` does not exist

### ISSUE THREAD

**Issue by Veske** [FasterXML/jackson-core#256]
I upgraded a project from jackson 2.4.4 to 2.7.1.  The older version had a class BytesToNameCanonicalizer that was used. The version 2.7.1 does not have it anymore. 

Was the class removed at some point of development and if so then are there any alternatives?

**Comment by cowtowncoder** [comment]
@Veske yes, it was replaced by `ByteQuadsCanonicalizer`, added in 2.6 (and `CharsToNameCanonicalizer`).
