### ISSUE TITLE
JSON String is not parsing properly by org.codehaus.jackson.map.ObjectMapper

### ISSUE THREAD

**Issue by NagarjunaManda** [FasterXML/jackson-core#270]
Issue:-  Below JSON is valid json but when validating with ObjectMapper through JAVA, it is giving any error like not a valid JSON.

   JAVA Code:-

                ObjectMapper objectMapper = new ObjectMapper();
		JsonNode node = objectMapper.readTree(json);

PFB JSON String below which we have used for our testing.

{
    "cust_code" : "CUC",
    "name" : "Host_coll",
    "description" : "Host Collection",
    "type" : "windows",
    "collections" : [ 
        {
            "data_type" : "siem",
            "collection_methods" : [ 
                {
                    "collection_method" : "wmi",
                    "inputs" : [ 
                        {
                            "name" : "severity",
                            "type" : "text",
                            "value" : [ 
                                "Success", 
                                "Error", 
                                "Audit Success"
                            ]
                        }, 
                        {
                            "name" : "facilities",
                            "type" : "text",
                            "value" : [ 
                                "System", 
                                "Directory Service", 
                                "ISA Server"
                            ]
                        }
                    ],
                    "scheduler" : {
                        "frequency" : {
                            "value" : "30",
                            "unit" : "minute"
                        }
                    }
                }, 
                {
                    "collection_method" : "api",
                    "inputs" : [ 
                        {
                            "name" : "severity",
                            "type" : "text",
                            "value" : [ 
                                "Success", 
                                "Error", 
                                "Audit Success"
                            ]
                        }, 
                        {
                            "name" : "facilities",
                            "type" : "text",
                            "value" : [ 
                                "System", 
                                "Directory Service", 
                                "ISA Server"
                            ]
                        }
                    ],
                    "scheduler" : {
                        "frequency" : {
                            "value" : "30",
                            "unit" : "minute"
                        }
                    }
                }, 
                {
                    "collection_method" : "subscription",
                    "inputs" : [ 
                        {
                            "name" : "severity",
                            "type" : "text",
                            "value" : [ 
                                "Success", 
                                "Error", 
                                "Audit Success"
                            ]
                        }, 
                        {
                            "name" : "facilities",
                            "type" : "text",
                            "value" : [ 
                                "System", 
                                "Directory Service", 
                                "ISA Server"
                            ]
                        }
                    ],
                    "scheduler" : {
                        "frequency" : {
                            "value" : "30",
                            "unit" : "minute"
                        }
                    }
                }, 
                {
                    "collection_method" : "syslog",
                    "inputs" : [ 
                        {
                            "name" : "severity",
                            "type" : "text",
                            "value" : [ 
                                "error"
                            ]
                        }
                    ]
                }, 
                {
                    "collection_method" : "file",
                    "inputs" : [ 
                        {
                            "name" : "severity",
                            "type" : "text",
                            "value" : [ 
                                "warning"
                            ]
                        }
                    ],
                    "scheduler" : {
                        "frequency" : {
                            "value" : "20",
                            "unit" : "minute"
                        }
                    }
                }, 
                {
                    "collection_method" : "database",
                    "scheduler" : {
                        "frequency" : {
                            "value" : "50",
                            "unit" : "minute"
                        }
                    }
                }
            ]
        }, 
        {
            "data_type" : "users",
            "collection_methods" : [ 
                {
                    "collection_method" : "ad",
                    "scheduler" : {
                        "frequency" : {
                            "value" : "2",
                            "unit" : "hour"
                        }
                    }
                }
            ]
        }, 
        {
            "data_type" : "vulnerability",
            "collection_methods" : [ 
                {
                    "collection_method" : "nessus",
                    "scheduler" : {
                        "frequency" : {
                            "value" : "2",
                            "unit" : "hour"
                        },
                        "timerange" : [ 
                            "Monday 09:00 - Monday 18:00", 
                            "Tuesday 09:00 - Tuesday 18:00"
                        ]
                    }
                }
            ]
        }
    ]
}

**Comment by cowtowncoder** [comment]
Um, what exactly is the problem? Validating how? With what objects? Do you get an exception; and if so, what is the message?

Also note that if you `org.codehaus.jackson`, you are using version 1.x, which is not supported any more (this issue tracker is for Jackson 2.x).

**Comment by NagarjunaManda** [comment]
Thank you for your reply..


**I am converting json string to jackson Node using Object Mapper.**

JAVA Code:-

            ObjectMapper objectMapper = new ObjectMapper();
    JsonNode node = objectMapper.readTree(json);


version of  ** jackson jar is: 1.x **

Here is the exception while parsing the json with jackson api..


org.codehaus.jackson.JsonParseException: Unexpected character ('M' (code 77)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
at [Source: java.io.StringReader@25c2a9e3; line: 1, column: 2]
org.codehaus.jackson.JsonParser._constructError(JsonParser.java:1432)
org.codehaus.jackson.impl.JsonParserMinimalBase._reportError(JsonParserMinimalBase.java:385)
org.codehaus.jackson.impl.JsonParserMinimalBase._reportUnexpectedChar(JsonParserMinimalBase.java:306)
org.codehaus.jackson.impl.ReaderBasedParser._handleUnexpectedValue(ReaderBasedParser.java:1192)
org.codehaus.jackson.impl.ReaderBasedParser.nextToken(ReaderBasedParser.java:479)
org.codehaus.jackson.map.ObjectMapper._initForReading(ObjectMapper.java:2761)
org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2709)
org.codehaus.jackson.map.ObjectMapper.readTree(ObjectMapper.java:1533)
ei

**Comment by cowtowncoder** [comment]
Look at your JSON, it is invalid, as exception indicates. JSON you includes is different from whatever you are giving it.

**Comment by NagarjunaManda** [comment]
Hey.. It is valid json.. Cau you please validate this json with other api's...I have checked with other json api's...

I think it is bug in jackson jar is: 1.x.. I am using jackson jar is: 1.x api..

**Comment by cowtowncoder** [comment]
@NagarjunaManda At this point I see no reason to assume json you feed is anything but invalid -- if you want to prove it is not, you'd need to provide a reproducible unit test. Cut and pasting alleged content is not useful as there are many ways in which you may end up with something different from what the real contents are.
