### ISSUE TITLE
Support JSON pointer expressions starting with hash symbol

### ISSUE THREAD

**Issue by afayes** [FasterXML/jackson-core#272]
JSON pointer expressions can start with a hash e.g.
#/foo   
see spec at the top of page 6 at https://tools.ietf.org/html/rfc6901

However if you try:
JsonPointer.compile("#/foo")

You will get:
java.lang.IllegalArgumentException: Invalid input: JSON Pointer expression must start with '/': "#/foo"

**Comment by cowtowncoder** [comment]
That refers to "URI Fragment Identifier Representation", not pointer expression itself.
So while it is true that that URI Fragments may (and do) start with hash signs, JSON Pointer expression do not.
I think current behavior is correct, and users should not try to feed URI fragments in. If necessary, drop the leading hash sign.

**Comment by afayes** [comment]
Some JSON schema documents beingtheir JSON pointers with a hash sign, for example see http://spacetelescope.github.io/understanding-json-schema/structuring.html

Our application is processing JSON schema documents that have a hash at the beginning of JSON pointers

**Comment by cowtowncoder** [comment]
@afayes then those pointer fragments need to be cleansed by removing hash, before usage.
Document you linked to does make the error of claiming these are Json Pointer expressions; they are fragments, with empty context. Jackson has no way of using any other context than the current node, and thereby very little use for fragment notation.

**Comment by afayes** [comment]
@cowtowncoder  Thank you for your response.

The JSON pointer specification at https://tools.ietf.org/html/rfc6901
gives 2 ways JSON pointers can be represented:

page 4:
5.  JSON String Representation
A JSON Pointer can be represented in a JSON string value
examples are on page 4 e.g. "/foo"

and page 5:
6.  URI Fragment Identifier Representation
A JSON Pointer can be represented in a URI fragment identifier
examples are on page 6 e.g.   #/foo   

From what I understand from the spec the URI Fragment Identifier Representation beginning with a hash is valid. The hash character would refer to the root of the document.

Apologies If I am misunderstanding specification.

**Comment by afayes** [comment]
@cowtowncoder Thanks for your response

**Comment by afayes** [comment]
I remove my previous comment as I realised it was incorrect.
