### ISSUE TITLE
JSON Deserialisation with Abstract Class

### ISSUE THREAD

**Issue by ivanstojkovicapps** [FasterXML/jackson-core#274]
Hi,

i am trying following example:

```
class Zoo  
{  
  public Collection<Animal> animals;  
}  

@JsonTypeInfo(
use = JsonTypeInfo.Id.NAME,
include = JsonTypeInfo.As.PROPERTY,
property = "type")
@JsonSubTypes({
@JsonSubTypes.Type(value = Dog.class, name = "dog"),
@JsonSubTypes.Type(value = Cat.class, name = "cat"),
})
@XmlAccessorType(value = XmlAccessType.FIELD)
@XmlRootElement(name="Animal",namespace=WSSupport.NAMESPACE)
@XmlType(name="Animal",namespace=WSSupport.NAMESPACE)
@XmlSeeAlso({
  Dog.class,
  Cat.class
})
public abstract class Animal {

}

@XmlAccessorType(value = XmlAccessType.FIELD)
@XmlRootElement(name="Cat",namespace=WSSupport.NAMESPACE)
@XmlType(name="Cat",namespace=WSSupport.NAMESPACE)
@JsonTypeName("cat")
public class Cat extends Animal {
	String miauType;
}

@XmlAccessorType(value = XmlAccessType.FIELD)
@XmlRootElement(name="Dog",namespace=WSSupport.NAMESPACE)
@XmlType(name="Dog",namespace=WSSupport.NAMESPACE)
@JsonTypeName("dog")
public class Dog extends Animal {
	String barkType;
}

```
With following JSON i get the ERROR:
`{
  "animals": [
    {
      "type": "dog",
      "barkType": "BAAARK"
    },
    {
      "type": "cat",
      "miauType": "MIIIIAU"
    }
  ]
}`

> org.codehaus.jackson.map.JsonMappingException: Can not construct instance of at.dataphone.logis3.rest.Animal, problem: abstract types can only be instantiated with additional type information at [Source: org.apache.catalina.connector.CoyoteInputStream@5b653116; line: 1, column: 13] (through reference chain: Zoo["animals"])

I am using jackson 2.4.1
Is this possible at all?

**Comment by cowtowncoder** [comment]
Please ask usage questions on mailing lists.

But as to your problem, make sure you are not accidentally mixing jackson 1.x and jackson 2.x classes: your `ObjectMapper` seems to be Jackson 1.x; maybe you are using jackson 2.x annotations which are not recognized by jackson 1 code (and vice versa).

**Comment by ivanstojkovicapps** [comment]
Hi,

i have jackson-core-2.6.3, jackson-annotations-2.6.3, jackson-jaxrs-base-2.6.3, jackson-core-asl-1.9.2, jackson-jaxrs-1.9.2, jackson-mapper-asl-1.9.2, jackson-xc-1.9.12

do you mean those are mixed?

**Comment by cowtowncoder** [comment]
@ivanstojkovicapps Only you can tell that. They live in different Java packages, so you have to make sure code and annotations match. It is not unusual to have both versions of Jackson in classpath (some libraries may use Jackson 1.x, others 2.x) as they can peacefully co-exist. But you can not mix and match for specific usage.
