### ISSUE TITLE
I use jackson transfer json string to obj , why version 2.4.6 is faster than 2.7.3 ?

### ISSUE THREAD

**Issue by beangou** [FasterXML/jackson-core#278]
first, compared with gson and fastjson, jackson performs fastest if I loop a large number of times(more than 100000). 
It's really great, so I choose jackson. However, I have a question: It seems that version 2.4.6 is faster than 2.7.3, why? Or I have sth wrong?

## These are the test results

loop times: 100000
v_2.7.3       &nbsp;&nbsp;         v_2.4.6
21859ms        20109ms
20016ms        19399ms
20390ms        18785ms

loop times: 300000
v_2.7.3      &nbsp; &nbsp;         v_2.4.6
60337ms        57806ms
60181ms        57575ms
63130ms        58569ms

**Comment by cowtowncoder** [comment]
@beangou I have not observed 2.7 to be very different, performance-wise, than 2.4. Difference (assuming results are valid) are relatively small here, 5-10%. That's almost within margin of error for JVM performance testing.

I use this benchmark:

https://github.com/FasterXML/jackson-benchmarks

which uses `jmh` framework. There are minor differences in results; some use cases have gotten slightly faster, others slightly slower.
There are different branches for different versions, although oldest one is 2.5. But there are results for 2.4. For json handling I have:

```
2.4.4.

c.f.j.p.j.JsonStdReadVanilla.readPojoMediaItem        thrpt        95   361094.770     4526.797    ops/s
c.f.j.p.j.JsonStdWriteVanilla.writePojoMediaItem        thrpt        95   595532.873     4795.981    ops/s

2.7.3

c.f.j.p.json.JsonStdReadVanilla.readPojoMediaItem          thrpt  150  360386.894 ± 2195.134  ops/s
c.f.j.p.json.JsonStdWriteVanilla.writePojoMediaItem          thrpt  150  590387.317 ±  2370.415  ops/s
```

which are basically identical. This is using simple POJO from `jvm-serializers` benchmark.

Keep in mind that measurement methodology matters a lot: you can not just run something for N times without handling things like warmup (JVM has lots of setup overhead in general; does just-in-time compilation, optimizes). If you want useful numbers, at least use warmup period of multiple seconds, and run test long enough (20 seconds test time is fine).

If you want to see if there is anything else going on in tests, perhaps you can share your test code?
