### ISSUE TITLE
JavaWriteContext#writeFieldName incorrectly handling sibling nodes

### ISSUE THREAD

**Issue by mohitchugh** [FasterXML/jackson-core#289]
For an example JSON like this - 

`{
    "a": {
    },
    "b": {
        "c": "cval"
    }
}`

when writeFieldName is called for node 'b', the _currentName is not updated as the _gotName value is already set to true (because of the earlier processing done for 'a'. This means that later down the line, when I try to do a context.getParent().getCurrentName(), I get 'a' back, instead of 'b'. 

This is a problem for me as I'm trying to get reconstruct the full-path of the node in a filter, based on which I decide whether or not to include the node in the output.

I have submitted a PR with a tentative fix that worked for me in the hope that it is the generic fix (or at least helps illustrate the issue).

https://github.com/FasterXML/jackson-core/pull/288

I am also curious to know when you are planning to upload a new version at 
http://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-core

Thanks.

**Comment by cowtowncoder** [comment]
@mohitchugh that does sound like a problem. Is this with Jackson 2.7.4?

New version are released with varying interval; for 2.7.5 it may take a few weeks more. At the same time I am hoping to release the first release candidate of 2.8.0 within a week or two.

**Comment by mohitchugh** [comment]
Yes. The problem exists with 2.7.4 and the latest master.

**Comment by mohitchugh** [comment]
Also see - https://github.com/FasterXML/jackson-databind/pull/1252 (which is PR that adds a couple of failing tests to illustrate the issue)

**Comment by cowtowncoder** [comment]
Fixed at `TokenBuffer` as per commit. Thank you for your help here!

**Comment by mohitchugh-okta** [comment]
Thanks for your prompt fix for the issue! Would you have any more information on when an official release will be out with this fix? I'll plan my project work accordingly. Thanks again.

**Comment by cowtowncoder** [comment]
@mohitchugh-okta 2.8.0.rc1 was just released, so there's hope that official `2.8.0` should get released before end of June 2016.

**Comment by cowtowncoder** [comment]
Also: will get 2.7.5 out before official 2.8.0. But as I said, `2.8.0.rc1` is out if you can use it.

**Comment by mohitchugh-okta** [comment]
Thanks! I'll try out 2.8.0.rc1.
