### ISSUE TITLE
Jackson + Bean validation (JSR-303)

### ISSUE THREAD

**Issue by senty** [FasterXML/jackson-core#302]
Hi guys,

is possible to perform basic validation ? For example max-length on string :

    public class MyBean {
       private String name;

       @JsonGetter("name")
       @Min(value = 100)
       public String getTheName() {
          return name;
       }
   }

So this call :
`mapper.readValue(jsonString, MyBean.class)`
would throw error in case thaht **name** is longer than 100 characters ?
Can be jackson (un)marshalling combined with **JSR-303** ?

Thank you very much !

**Comment by cowtowncoder** [comment]
@senty this is not a bug, so please use mailing list at 

https://groups.google.com/forum/#!search/jackson-users

for questions.

**Comment by nitishborade** [comment]
@cowtowncoder Is this integrated into the lastest version of Jackson, as per your comment in the above link 
*I will not add direct JSR-303 support in Jackson... And, to the degree feasible, can integrate with processing so that to user it may look like it was fully integrated.*
