### ISSUE TITLE
inconsistent data types returned by ObjectMapper at compile time and runtime

### ISSUE THREAD

**Issue by koosha--** [FasterXML/jackson-core#303]
I'm using the `readValue()` method of `ObjectMapper` on a JSON string to get a hash map of strings:

```
HashMap<String, String> jsonHash = mapper.readValue(jsonString, HashMap.class);
```
In my `jsonString` variable, I have a boolean value:
```
{
  ...
  "success":"true"
  ...
}
```
The problem is that the type of `jsonHash.get("success")` is not String but it is Boolean at runtime while it is String at compile time. This has caused all kinds of compatibility issues and prevents me from checking its value in an `if` condition and has driven me mad.

Please let me know how I can work around this issue. And, if it is a bug (which must be), please consider fixing it.

Thank you.

**Comment by cowtowncoder** [comment]
I am not 100% sure I understand without actual test to show your assumptions, but:

1. If you give `HashMap.class` as argument without type parameters, it is taken as roughly similar to `HashMap<Object,Object>`, and value types should correspond to JSON type.
2. If value is "true", as JSON String, then with type you are giving, it should return as `String` instance.
3. If value is `true`, as JSON Boolean, it should be expressed as Java `Boolean`

if you want some other mapping, you need to specify generic typing. For example, if you want to force conversion to Java String, you'd need to use something ke:

    HashMap<String,String> jsonHash = mapper.readValue(jsonString,
       new TypeReference<HashMap<String,String>>() {} );

**Comment by koosha--** [comment]
Thank you for your help.

The value is indeed `true` (not `"true"`) and your trick works. However, I am not sure if the observed behavior of `readValue()` in the absence of `TypeReference` is expected since the type is already specified on the left-hand side.

**Comment by cowtowncoder** [comment]
@koosha unfortunately left-hand side is just compile-time syntactic sugar and not available to runtime code. Any code generated would be for result `readValue()` call.
There are some good explanations on how Java type erasure and generic types work; problem is not limited to Jackson usage.

I hope you can get things working as expected here.
