### ISSUE TITLE
Provide a way to reduce verbosity on error messages

### ISSUE THREAD

**Issue by carlosjgp** [FasterXML/jackson-core#316]
When sending incomplete, no closing curl brace ("}"), Json body I got
` {
  "status": 400,
  "message": "Invalid json body - Unexpected end-of-input: expected close marker for Object (start marker at [Source: java.io.PushbackInputStream@697e7db5; line: 1, column: 1]).",
  "type": "JSON_VALIDATION",
  "errors": null
}`

As suggestion, the "Unexpected...." description can be optional and linked to the logging level.

**Comment by cowtowncoder** [comment]
I think the actual error message is composed by a framework (Spring Boot, DropWizard or such?): Jackson only provides "Unexpected end-of-input .... [location]" part. Jackson also does not do any logging. So not quite sure what could or should be improved here.

**Comment by carlosjgp** [comment]
The issue is that in production we don't want the user to be aware of the implementation, classes or libraries

After review the code looks like "the problem" is related to how this line resolves the json object start position.
https://github.com/FasterXML/jackson-core/blob/master/src/main/java/com/fasterxml/jackson/core/base/ParserBase.java#L538

which prints a JsonLocation object
https://github.com/FasterXML/jackson-core/blob/d0172cddcec336b5cc8a55817c1f16cf726a9755/src/main/java/com/fasterxml/jackson/core/JsonLocation.java#L93
`[Source: java.io.PushbackInputStream@1509e1b; line: 1, column: 1]`

This is the complete trace
https://gist.github.com/carlosjgp/2c3e7851c8b975be5505e2c7885afeda

**Comment by cowtowncoder** [comment]
@carlosjgp I still do not quite understand what you asking here. Yes, location information is included.
But it's not printed; information is included within exception that is thrown. Something else (code that catches tje exception) may then choose to log it. So if you want that suppressed, it seems that that part of handling needs to be changed, not the underlying parser that includes relevant information.

**Comment by carlosjgp** [comment]
In my case the exception message would be perfect if it doesn't contains references to the class or java at all.
`Invalid json body - Unexpected end-of-input: expected close marker for Object (start marker at line: 1, column: 1).`

instead of

`Invalid json body - Unexpected end-of-input: expected close marker for Object (start marker at [Source: java.io.PushbackInputStream@697e7db5; line: 1, column: 1]).`

The other option is, as you have mention, the other option is manage this exceptions to avoid showing any details of our implementation.

Is really needed to print the source and square braces?

**Comment by cowtowncoder** [comment]
@carlosjgp For most users this is by far the most useful part of the exception -- location where the problem resides. But as I have said multiple times, Jackson does print anything: it is whatever catches exception that prints out what it wants; and if information is not needed, should not use `exception.toString()` for dumping it all out.
