### ISSUE TITLE
Regression bug on json deserialisation since 2.7.x or 2.8.x (not in 2.6.x) when using some generic in yours objects

### ISSUE THREAD

**Issue by alexandrenavarro** [FasterXML/jackson-core#331]
Regression bug on json deserialisation since 2.7.x or 2.8.x (not in 2.6.x) when using some generic in yours objects.

A com.fasterxml.jackson.databind.JsonMappingException is thrown with incorrect mappings.
I tried to understant why but I didn't succeed.

I give you a sample with a unit test which works in 2.6.7 but not in 2.8.4 (not in any version >= 2.7.0) .
Don't hesitate to contact me if it is not clear.

[jackson-bug-generic-sample.zip](https://github.com/FasterXML/jackson-core/files/584080/jackson-bug-generic-sample.zip)

**Comment by cowtowncoder** [comment]
Thank you for reporting this. Issue tracker to use would actually be https://github.com/FasterXML/jackson-databind/issues, but I can have a look first.

**Comment by cowtowncoder** [comment]
Moved to https://github.com/FasterXML/jackson-databind/issues/1449
