### ISSUE TITLE
Spring Integration

### ISSUE THREAD

**Issue by svatos-jirka** [FasterXML/jackson-core#336]
Hi,

could you add short table to readme (first page), which contains spring version and suitable version of jackson (codehause or fasterxml). It is really classpath/mismatch version nightmare.

Thanks, Jiri

**Comment by cowtowncoder** [comment]
@svatos-jirka I have no idea; this sounds more like something that Spring project could do.

But if you or anyone else wants to contribute documentation I would be happy add that to wiki of the repo (wiki since it's easier to give direct access than README), as a separate Spring compatibility page.
