### ISSUE TITLE
Explicit property is not deserialized when parent has shadowing fields (with Proguard - dangerous) 

### ISSUE THREAD

**Issue by ndori** [FasterXML/jackson-core#339]
Hi,
I'm an android developer and I'm using Proguard and Jackson in my production app.

I came across a bug which was amplified by Proguard obstruction. 

I'll give you the full example so you can check it.

    public class MainActivity extends AppCompatActivity { @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
        try {
            A a = objectMapper.readValue("{\n" +
                    "  \"Type\": \"B\",\n" +
                    "  \"Hello\": \"hello\",\n" +
                    "  \"World\": \"world\",\n" +
                    "  \"Other\": \"other\"\n" +
                    "}", A.class);
            Log.e("debug", "a.getStr()=" + a.getStr() + " a.getOther()=" + a.getOther());
            Log.e("debug", " is instaceof b:" + (a instanceof B));
        } catch (Exception e) {
            Log.e("debug", "error", e);
        }

    }

    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "Type",defaultImpl = A.class, visible = false)
    @JsonSubTypes({
            @JsonSubTypes.Type(value = B.class, name = "B")
    })
    public static class A {
        @JsonProperty("Hello")
        private String str;

        public String getStr() {
            return this.str;
        }

        @JsonProperty("Other")
        private String other;

        public String getOther() {
            return other;
        }
    }

    public static class B extends A {
        @JsonProperty("World")
        public String str;
    }}

I used logs for easy debugging, 
In this scenario a.getStr() will return "null". I would expect it to be "hello".

This is not the expected behaviour, shadowing is allowed (even if discharged) by java,
if we will remove the  FAIL_ON_UNKNOWN_PROPERTIES line it will throw an error as it did not managed to deserialize "Hello"

This problem is a real one, and that because most of android developers use ProGuard.

In my original code, there was no shadowing, there was a "hello" field in class A, and a "world" field in class B.
However proguard changed both of their names to "a", and that because it is valid in Java and should not cause any problem.

So you can understand how this issue can become very real, moreover as proguard is not usually used in debug flavor this problem will be really hard to find and fix.

My workaround was to change the "hello" to be a protected field, this way proguard will give them different names, but this can actually happen with every private field!

Another workaround might be to explicitly tell proguard to keep all the classes that uses Jackson as is, but for my taste it is a bad workaround that will force one to constantly update the proguard config file.

I will be happy to add any other information you might need.

Tnx, Nitzan

**Comment by cowtowncoder** [comment]
Could you please re-file this at `jackson-databind`, as `jackson-core` repository only deals with low-level streaming api, and issue would be in higher level databinding package.

**Comment by ndori** [comment]
I'll try, didn't noticed where I've put it
