### ISSUE TITLE
ObjectNode random insert

### ISSUE THREAD

**Issue by atorstling** [FasterXML/jackson-core#341]
Hello! I see that ObjectNode is implemented with LinkedHashMap. ObjectNode also considers insertion order of properies when printing and calling equals. I would therefore like to ask for random insert support. I'm trying to apply recorded changes to an ObjectNode, but cannot insert any field in a particular spot.

**Comment by cowtowncoder** [comment]
ObjectNode does not consider insertion order for equality; entries are compared considering the fact that actual order (as indicated by serialization) is arbitrary and not semantically meaningful.
So this should already work as expected.

**Comment by cowtowncoder** [comment]
I think it works as expected; if not, a test case would be needed.
Also note that this really belongs under `jackson-databind`; but that only matters if this issue is active.
Closing until then.

**Comment by atorstling** [comment]
Hi! Yes, go ahead and close. I have to reproduce my case, there seems to be more going on than I initially though. I'll reopen if i can reproduce.
