### ISSUE TITLE
java.lang.NegativeArraySizeException at com.fasterxml.jackson.core.util.ByteArrayBuilder.toByteArray(ByteArrayBuilder.java:142)

### ISSUE THREAD

**Issue by sharminazam** [FasterXML/jackson-core#351]
I am getting this Exception
java.lang.NegativeArraySizeException
        at com.fasterxml.jackson.core.util.ByteArrayBuilder.toByteArray(ByteArrayBuilder.java:142)
        at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsBytes(ObjectMapper.java:2239)
...
which is coming from  this line:
 byte[] result = new byte[totalLen];
The reason may be the below value is probably too big for an int. And probably narrowing conversion from long to int caused a sign flip because higher order bits are discarded.

 int totalLen = _pastLen + _currBlockPtr;

**Comment by cowtowncoder** [comment]
@sharminazam sounds plausible. But I would really need a reproduction of some kind here -- also note that size of `byte[]` is limited to about 2 gigs, since array indexes are `int`s. So while exception message is clearly wrong -- and I'd be happy to improve it -- this may be a bigger problem for your use case, if result size does exceed that limit.

**Comment by sharminazam** [comment]
We are handling very big JSONs. So the assumption is that JSON can't allocate byte[] bigger that 2 GB if using jackson?

**Comment by cowtowncoder** [comment]
@sharminazam not assumption but hard limitation by Java language and JVM. See for example here:

https://www.quora.com/What-is-the-maximum-size-of-the-array-in-Java

There is no limitation in size by Jackson, and it has been used for processing multi-gigabyte size content.
But surely you would not want to keep a gigabyte sized output in memory, buffered as a byte array, but write it to some storage? I mean what would be the benefit of such buffering.
Instead, streaming processing (handling just a part of input at any given time, writing out incrementally) makes more sense for bigger content.

**Comment by sharminazam** [comment]
Thanks for the reference about array size. I understand holding gigabyte size of array in memory does not make much sense. Just have some limitations for legacy code. Anyway, I will explore the option of stream processing .

**Comment by cowtowncoder** [comment]
@sharminazam ok. Yes, I understand. Simple buffering is often expected, and in many cases makes sense as well. But there often comes a point when processing more data when it becomes necessary to start thinking about alternatives.

I'll think about if and how to improve messaging, however. I think it'd be better to give different error message...
