### ISSUE TITLE
JsonParserSequence#skipChildren() throws exception when current delegate is TokenBuffer.Parser with "incomplete" JSON

### ISSUE THREAD

**Issue by MichaelSims** [FasterXML/jackson-core#372]
`JsonParserSequence` subclasses `JsonParserDelegate` but does not override `skipChildren()`. The default implementation of this just calls current delegate's `skipChildren()` method, which bypasses `JsonParserSequence#nextToken()`. When the current delegate is a `TokenBuffer.Parser `and the buffer contains "unbalanced" JSON (i.e. an incomplete JSON object where the number of start object tokens is more than the number of end object tokens), this violates an invariant of `ParserMinimalBase#skipChildren()` and results in an exception like the following:

```
java.lang.RuntimeException: Internal error: this code path should never get executed
	at com.fasterxml.jackson.core.util.VersionUtil.throwInternal(VersionUtil.java:179)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._throwInternal(ParserMinimalBase.java:566)
	at com.fasterxml.jackson.databind.util.TokenBuffer$Parser._handleEOF(TokenBuffer.java:1662)
	at com.fasterxml.jackson.core.base.ParserMinimalBase.skipChildren(ParserMinimalBase.java:156)
	at com.fasterxml.jackson.core.util.JsonParserDelegate.skipChildren(JsonParserDelegate.java:222)
```
One possible fix for this is to have `JsonParserSequence` override `skipChildren()` in much the same way `FilteringParserDelegate` does, so that its `nextToken()` logic is not bypassed. I can submit a PR if this would be helpful, just let me know.

Thanks!

**Comment by cowtowncoder** [comment]
@MichaelSims yes I think such patch would make sense. I think sequence implementation is not very well tested (compared to, say, `TokenBuffer`) since it is not internally used for anything.

**Comment by MichaelSims** [comment]
Hi, thanks for looking into it. I attempted to add a unit test to demonstrate the problem and verify the fix, but since TokenBuffer.Parser is not part of this module that made it difficult. I tried to contrive a similar scenario but it seems none of the JsonParser implementations in core tolerate an incomplete JSON document as TokenBuffer.Parser does. I'm happy to rework and add a test if you have any suggestions for how to demonstrate the issue using only classes in this module.

**Comment by cowtowncoder** [comment]
@MichaelSims I'd be fine reproducing this from `jackson-databind` too, despite flaw really residing here, if that would make this easier. Core and databind are quite closely coupled in many ways so I am not too worried about discrepancy here. Whether issue should reside here or over in the other repo is another part; I think leaving this issue here is acceptable as well (since that will make sense wrt release notes).

**Comment by MichaelSims** [comment]
Test added in:
https://github.com/FasterXML/jackson-databind/pull/1618

If there's another way I should go about this (different organization or naming) please let me know. Thanks!
