### ISSUE TITLE
readValue crashes with null pointer when bytes[] is passed null

### ISSUE THREAD

**Issue by abhimaanmadhav** [FasterXML/jackson-core#377]

**Comment by abhimaanmadhav** [comment]
java.lang.NullPointerException: Attempt to get length of null array
test.max W/System.err:     at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:844)
test.max W/System.err:     at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2872)
test.max W/System.err:     at test.max.network.ParserUtil.parse(ParserUtil.java:32)
test.max W/System.err:     at test.max.api.service.network.HttpRequestHandler.onSuccessResponse(HttpRequestHandler.java:118)
test.max W/System.err:     at test.max.api.service.network.HttpRequestHandler.onResponse(HttpRequestHandler.java:59)
test.max W/System.err:     at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
test.max W/System.err:     at android.os.Handler.handleCallback(Handler.java:751)
test.maxW/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
test.max W/System.err:     at android.os.Looper.loop(Looper.java:154)
test.max W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6692)
com.test.max W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
com.test.maxW/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
com.test.max W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by cowtowncoder** [comment]
And this is not right because... ? Should `null` byte array be accepted, or what would be the preferred handling?

**Comment by abhimaanmadhav** [comment]
I agree this can be handled by the user using the library project. But i prefer defensive programming in which the library never crashes.

**Comment by cowtowncoder** [comment]
@abhimaanmadhav Throwing exception is not crashing; and for invalid input, exception should be thrown. So what do you think would be better way to handle this case? Different exception, message... ?
