### ISSUE TITLE
Inheritance with inner classes serialized with wrong type information

### ISSUE THREAD

**Issue by frbo42** [FasterXML/jackson-core#384]
As I have to serialize / deserialize a class hierarchy, I experimented with the following tutorial (http://www.baeldung.com/jackson-inheritance). It occurred to me that the serialization is not correct when using inner classes.

I add my test class which shows that the serialization writes the wrong java type in the json string.
'JacksonHierarchyTest$Vehicle' instead of 'JacksonHierarchyTest$Car'

```java
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.Test;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import static org.hamcrest.CoreMatchers.instanceOf;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertThat;

public class JacksonHierarchyTest {

    @Test
    public void hierarchy() throws IOException {
        ObjectMapper mapper = new ObjectMapper();
        mapper.enableDefaultTyping();

        Fleet fleet = initVehicle();

        String serializedFleet = mapper.writeValueAsString(fleet);

        System.out.println(serializedFleet);

        Fleet deserializedFleet = mapper.readValue(serializedFleet, Fleet.class);

        assertThat(deserializedFleet.getVehicles().get(0), instanceOf(Car.class));
        assertThat(deserializedFleet.getVehicles().get(1), instanceOf(Truck.class));

        assertEquals(fleet, deserializedFleet);
    }

    private Fleet initVehicle() {
        Car car = new Car("Mercedes-Benz", "S500", 5, 250.0);
        Truck truck = new Truck("Isuzu", "NQR", 7500.0);

        List<Vehicle> vehicles = new ArrayList<>();
        vehicles.add(car);
        vehicles.add(truck);

        Fleet serializedFleet = new Fleet();
        serializedFleet.setVehicles(vehicles);
        return serializedFleet;
    }

    public static class Fleet {
        private List<Vehicle> vehicles;

        public List<Vehicle> getVehicles() {
            return vehicles;
        }

        public void setVehicles(List<Vehicle> vehicles) {
            this.vehicles = vehicles;
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            Fleet fleet = (Fleet) o;
            return Objects.equals(vehicles, fleet.vehicles);
        }

        @Override
        public int hashCode() {
            return Objects.hash(vehicles);
        }
    }

    public static abstract class Vehicle {
        private String make;
        private String model;

        protected Vehicle(String make, String model) {
            this.make = make;
            this.model = model;
        }

        public Vehicle() {
        }

        public String getMake() {
            return make;
        }

        public void setMake(String make) {
            this.make = make;
        }

        public String getModel() {
            return model;
        }

        public void setModel(String model) {
            this.model = model;
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (!(o instanceof Vehicle)) return false;
            Vehicle vehicle = (Vehicle) o;
            return Objects.equals(make, vehicle.make) &&
                    Objects.equals(model, vehicle.model);
        }

        @Override
        public int hashCode() {
            return Objects.hash(make, model);
        }
    }

    public class Car extends Vehicle {
        private int seatingCapacity;
        private double topSpeed;

        public Car(String make, String model, int seatingCapacity, double topSpeed) {
            super(make, model);
            this.seatingCapacity = seatingCapacity;
            this.topSpeed = topSpeed;
        }

        public Car() {
        }

        public int getSeatingCapacity() {
            return seatingCapacity;
        }

        public void setSeatingCapacity(int seatingCapacity) {
            this.seatingCapacity = seatingCapacity;
        }

        public double getTopSpeed() {
            return topSpeed;
        }

        public void setTopSpeed(double topSpeed) {
            this.topSpeed = topSpeed;
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            if (!super.equals(o)) return false;
            Car car = (Car) o;
            return seatingCapacity == car.seatingCapacity &&
                    Double.compare(car.topSpeed, topSpeed) == 0;
        }

        @Override
        public int hashCode() {
            return Objects.hash(super.hashCode(), seatingCapacity, topSpeed);
        }
    }

    public class Truck extends Vehicle {
        private double payloadCapacity;

        public Truck(String make, String model, double payloadCapacity) {
            super(make, model);
            this.payloadCapacity = payloadCapacity;
        }

        public Truck() {
        }

        public double getPayloadCapacity() {
            return payloadCapacity;
        }

        public void setPayloadCapacity(double payloadCapacity) {
            this.payloadCapacity = payloadCapacity;
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            if (!super.equals(o)) return false;
            Truck truck = (Truck) o;
            return Double.compare(truck.payloadCapacity, payloadCapacity) == 0;
        }

        @Override
        public int hashCode() {
            return Objects.hash(super.hashCode(), payloadCapacity);
        }
    }
}
```

**Comment by cowtowncoder** [comment]
Ok, first things first:

* This issue belongs under `jackson-databind` (since it is about databinding, not streaming API)
* Version tested needs to be included: ideally it'd be tested with the latest stable version (2.8.9), but at least needs to be latest patch version of minor version in question (2.4.6, not, say, 2.4.1).

**Comment by cowtowncoder** [comment]
Test passes with 2.8.9 and 2.9.0.pr4, so I can not quite reproduce the issue at this point.

**Comment by frbo42** [comment]
I tried it with Jackson 2.8.7 on a Ubuntu with java : Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

**Comment by cowtowncoder** [comment]
@frbo42 what is the error or assertion failure you see?

**Comment by frbo42** [comment]
Here is the full stacktrace

`/home/dev/development/java/jdk1.8.0_121/bin/java -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:37625,suspend=y,server=n -ea -Didea.test.cyclic.buffer.size=1048576 -Dfile.encoding=UTF-8 -classpath /home/dev/development/ide/idea-IU-171.3780.107/lib/idea_rt.jar:/home/dev/development/ide/idea-IU-171.3780.107/plugins/junit/lib/junit-rt.jar:/home/dev/development/java/jdk1.8.0_121/jre/lib/charsets.jar:/home/dev/development/java/jdk1.8.0_121/jre/lib/deploy.jar:/home/dev/development/java/jdk1.8.0_121/jre/lib/ext/cldrdata.jar:/home/dev/development/java/jdk1.8.0_121/jre/lib/ext/dnsns.jar:/home/dev/development/java/jdk1.8.0_121/jre/lib/ext/jaccess.jar:/home/dev/development/java/jdk1.8.0_121/jre/lib/ext/jfxrt.jar:/home/dev/development/java/jdk1.8.0_121/jre/lib/ext/localedata.jar:/home/dev/development/java/jdk1.8.0_121/jre/lib/ext/nashorn.jar:/home/dev/development/java/jdk1.8.0_121/jre/lib/ext/sunec.jar:/home/dev/development/java/jdk1.8.0_121/jre/lib/ext/sunjce_provider.jar:/home/dev/development/java/jdk1.8.0_121/jre/lib/ext/sunpkcs11.jar:/home/dev/development/java/jdk1.8.0_121/jre/lib/ext/zipfs.jar:/home/dev/development/java/jdk1.8.0_121/jre/lib/javaws.jar:/home/dev/development/java/jdk1.8.0_121/jre/lib/jce.jar:/home/dev/development/java/jdk1.8.0_121/jre/lib/jfr.jar:/home/dev/development/java/jdk1.8.0_121/jre/lib/jfxswt.jar:/home/dev/development/java/jdk1.8.0_121/jre/lib/jsse.jar:/home/dev/development/java/jdk1.8.0_121/jre/lib/management-agent.jar:/home/dev/development/java/jdk1.8.0_121/jre/lib/plugin.jar:/home/dev/development/java/jdk1.8.0_121/jre/lib/resources.jar:/home/dev/development/java/jdk1.8.0_121/jre/lib/rt.jar:/home/dev/development/projects/log/target/test-classes:/home/dev/development/projects/log/target/classes:/home/dev/development/maven/repository/org/springframework/boot/spring-boot-starter-web/1.5.4.RELEASE/spring-boot-starter-web-1.5.4.RELEASE.jar:/home/dev/development/maven/repository/org/springframework/boot/spring-boot-starter/1.5.4.RELEASE/spring-boot-starter-1.5.4.RELEASE.jar:/home/dev/development/maven/repository/org/springframework/boot/spring-boot/1.5.4.RELEASE/spring-boot-1.5.4.RELEASE.jar:/home/dev/development/maven/repository/org/springframework/boot/spring-boot-autoconfigure/1.5.4.RELEASE/spring-boot-autoconfigure-1.5.4.RELEASE.jar:/home/dev/development/maven/repository/org/springframework/boot/spring-boot-starter-logging/1.5.4.RELEASE/spring-boot-starter-logging-1.5.4.RELEASE.jar:/home/dev/development/maven/repository/ch/qos/logback/logback-classic/1.1.11/logback-classic-1.1.11.jar:/home/dev/development/maven/repository/ch/qos/logback/logback-core/1.1.11/logback-core-1.1.11.jar:/home/dev/development/maven/repository/org/slf4j/jcl-over-slf4j/1.7.25/jcl-over-slf4j-1.7.25.jar:/home/dev/development/maven/repository/org/slf4j/jul-to-slf4j/1.7.25/jul-to-slf4j-1.7.25.jar:/home/dev/development/maven/repository/org/slf4j/log4j-over-slf4j/1.7.25/log4j-over-slf4j-1.7.25.jar:/home/dev/development/maven/repository/org/yaml/snakeyaml/1.17/snakeyaml-1.17.jar:/home/dev/development/maven/repository/org/springframework/boot/spring-boot-starter-tomcat/1.5.4.RELEASE/spring-boot-starter-tomcat-1.5.4.RELEASE.jar:/home/dev/development/maven/repository/org/apache/tomcat/embed/tomcat-embed-core/8.5.15/tomcat-embed-core-8.5.15.jar:/home/dev/development/maven/repository/org/apache/tomcat/embed/tomcat-embed-el/8.5.15/tomcat-embed-el-8.5.15.jar:/home/dev/development/maven/repository/org/apache/tomcat/embed/tomcat-embed-websocket/8.5.15/tomcat-embed-websocket-8.5.15.jar:/home/dev/development/maven/repository/org/hibernate/hibernate-validator/5.3.5.Final/hibernate-validator-5.3.5.Final.jar:/home/dev/development/maven/repository/javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final.jar:/home/dev/development/maven/repository/org/jboss/logging/jboss-logging/3.3.1.Final/jboss-logging-3.3.1.Final.jar:/home/dev/development/maven/repository/com/fasterxml/classmate/1.3.3/classmate-1.3.3.jar:/home/dev/development/maven/repository/com/fasterxml/jackson/core/jackson-databind/2.8.9/jackson-databind-2.8.9.jar:/home/dev/development/maven/repository/com/fasterxml/jackson/core/jackson-annotations/2.8.0/jackson-annotations-2.8.0.jar:/home/dev/development/maven/repository/com/fasterxml/jackson/core/jackson-core/2.8.9/jackson-core-2.8.9.jar:/home/dev/development/maven/repository/org/springframework/spring-web/4.3.9.RELEASE/spring-web-4.3.9.RELEASE.jar:/home/dev/development/maven/repository/org/springframework/spring-aop/4.3.9.RELEASE/spring-aop-4.3.9.RELEASE.jar:/home/dev/development/maven/repository/org/springframework/spring-beans/4.3.9.RELEASE/spring-beans-4.3.9.RELEASE.jar:/home/dev/development/maven/repository/org/springframework/spring-context/4.3.9.RELEASE/spring-context-4.3.9.RELEASE.jar:/home/dev/development/maven/repository/org/springframework/spring-webmvc/4.3.9.RELEASE/spring-webmvc-4.3.9.RELEASE.jar:/home/dev/development/maven/repository/org/springframework/spring-expression/4.3.9.RELEASE/spring-expression-4.3.9.RELEASE.jar:/home/dev/development/maven/repository/org/springframework/boot/spring-boot-starter-test/1.5.4.RELEASE/spring-boot-starter-test-1.5.4.RELEASE.jar:/home/dev/development/maven/repository/org/springframework/boot/spring-boot-test/1.5.4.RELEASE/spring-boot-test-1.5.4.RELEASE.jar:/home/dev/development/maven/repository/org/springframework/boot/spring-boot-test-autoconfigure/1.5.4.RELEASE/spring-boot-test-autoconfigure-1.5.4.RELEASE.jar:/home/dev/development/maven/repository/com/jayway/jsonpath/json-path/2.2.0/json-path-2.2.0.jar:/home/dev/development/maven/repository/net/minidev/json-smart/2.2.1/json-smart-2.2.1.jar:/home/dev/development/maven/repository/net/minidev/accessors-smart/1.1/accessors-smart-1.1.jar:/home/dev/development/maven/repository/org/ow2/asm/asm/5.0.3/asm-5.0.3.jar:/home/dev/development/maven/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar:/home/dev/development/maven/repository/junit/junit/4.12/junit-4.12.jar:/home/dev/development/maven/repository/org/assertj/assertj-core/2.6.0/assertj-core-2.6.0.jar:/home/dev/development/maven/repository/org/mockito/mockito-core/1.10.19/mockito-core-1.10.19.jar:/home/dev/development/maven/repository/org/objenesis/objenesis/2.1/objenesis-2.1.jar:/home/dev/development/maven/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/home/dev/development/maven/repository/org/hamcrest/hamcrest-library/1.3/hamcrest-library-1.3.jar:/home/dev/development/maven/repository/org/skyscreamer/jsonassert/1.4.0/jsonassert-1.4.0.jar:/home/dev/development/maven/repository/com/vaadin/external/google/android-json/0.0.20131108.vaadin1/android-json-0.0.20131108.vaadin1.jar:/home/dev/development/maven/repository/org/springframework/spring-core/4.3.9.RELEASE/spring-core-4.3.9.RELEASE.jar:/home/dev/development/maven/repository/org/springframework/spring-test/4.3.9.RELEASE/spring-test-4.3.9.RELEASE.jar com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 org.fb.jackson.JacksonHierarchyTest
Connected to the target VM, address: '127.0.0.1:37625', transport: 'socket'
{"vehicles":["java.util.ArrayList",[["org.fb.jackson.JacksonHierarchyTest$Vehicle",{"make":"Mercedes-Benz","model":"S500","seatingCapacity":5,"topSpeed":250.0}],["org.fb.jackson.JacksonHierarchyTest$Vehicle",{"make":"Isuzu","model":"NQR","payloadCapacity":7500.0}]]]}

Disconnected from the target VM, address: '127.0.0.1:37625', transport: 'socket'

com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of org.fb.jackson.JacksonHierarchyTest$Vehicle: abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: {"vehicles":["java.util.ArrayList",[["org.fb.jackson.JacksonHierarchyTest$Vehicle",{"make":"Mercedes-Benz","model":"S500","seatingCapacity":5,"topSpeed":250.0}],["org.fb.jackson.JacksonHierarchyTest$Vehicle",{"make":"Isuzu","model":"NQR","payloadCapacity":7500.0}]]]}; line: 1, column: 84] (through reference chain: org.fb.jackson.JacksonHierarchyTest$Fleet["vehicles"]->java.util.ArrayList[0])

	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270)
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1456)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1012)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserialize(AbstractDeserializer.java:216)
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer._deserialize(AsArrayTypeDeserializer.java:116)
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer.deserializeTypedFromObject(AsArrayTypeDeserializer.java:61)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:209)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:289)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:259)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer._deserialize(AsArrayTypeDeserializer.java:116)
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer.deserializeTypedFromArray(AsArrayTypeDeserializer.java:53)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserializeWithType(CollectionDeserializer.java:320)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:502)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:104)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3814)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2858)
	at org.fb.jackson.JacksonHierarchyTest.hierarchy(JacksonHierarchyTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


Process finished with exit code 255
`

**Comment by cowtowncoder** [comment]
So this:

```
com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of org.fb.jackson.JacksonHierarchyTest$Vehicle: abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: {"vehicles":["java.util.ArrayList",[["org.fb.jackson.JacksonHierarchyTest$Vehicle",{"make":"Mercedes-Benz","model":"S500","seatingCapacity":5,"topSpeed":250.0}],["org.fb.jackson.JacksonHierarchyTest$Vehicle",{"make":"Isuzu","model":"NQR","payloadCapacity":7500.0}]]]}; line: 1, column: 84] (through reference chain: org.fb.jackson.JacksonHierarchyTest$Fleet["vehicles"]->java.util.ArrayList[0])
```

**Comment by cowtowncoder** [comment]
Well. All I can say is that test passes for me, and JSON written is as expected:

```json
{
  "vehicles" : [ "java.util.ArrayList", [ [ "com.fasterxml.jackson.failing.Core384Test$Car", {
    "make" : "Mercedes-Benz",
    "model" : "S500",
    "seatingCapacity" : 5,
    "topSpeed" : 250.0
  } ], [ "com.fasterxml.jackson.failing.Core384Test$Truck", {
    "make" : "Isuzu",
    "model" : "NQR",
    "payloadCapacity" : 7500.0
  } ] ] ]
}
```

One thing you can try is to double check version you are using: there is method `version()` in many Jackson components (including `ObjectMapper`) which gives you version number.
This can help in cases where you somehow have multiple Jackson versions in classpath: this is quite a common problem. It can occur when some other library uses shaded (repackaged) version, for example; and sometimes deployments via things like Docker accidentally copy (and often explode) multiple instances.

Anyway: I am not able to reproduce this with latest versions -- 2.8.9, 2.9.0.pr4.
I will try an older version (2.7.9) if that could help.

**Comment by frbo42** [comment]
@cowtowncoder thank you for spending so much time in solving this problem.
It is not critical for me anyway, I just moved the inner classes to top level :)

**Comment by cowtowncoder** [comment]
@frbo42 Oh! That may well be the difference -- inner classes MUST be `static` (and I did change that for test), since otherwise they require "implicit this pointer" and, well, things get complicated.
It's fine to serialize such classes (since they are in valid state), but deserialization only works in limited cases (basically, only "parent" class can contain reference: if so, deserialization works) -- and I would not be surprised that polymorphic handling does not work.

So: you can try adding `static` in there. And I can try my test case by removing `static`: perhaps error messaging could use improvements.

**Comment by cowtowncoder** [comment]
Doh. And only now fully realized that title did even mention "inner class".

Perhaps there's something additionally wrong, wrt actual type id to use.

**Comment by cowtowncoder** [comment]
Interesting. Turns out this is an actual feature... `ClassNameIdResolver` (responsible for converting between `Class` and external JSON String) explicitly check for non-static inner classes, and has comment:

```
            /* Other special handling may be needed for inner classes, [JACKSON-584].
             * The best way to handle would be to find 'hidden' constructor; pass parent
             * value etc (which is actually done for non-anonymous static classes!),
             * but that is just not possible due to various things. So, we will instead
             * try to generalize type into something we will be more likely to be able
             * construct.
             */
```

(and here [JACKSON-584] refers to Jackson 1.x bug tracker issue -- alas, that was at Codehaus so issue is long gone now)

I do not remember details here, but suspect this may have been for one of JDK's helper types (like empty/singleton Lists).

Now... not sure what, if anything, should be done here. As per comment, it is tricky; although removing/disabling special handling would at least give more useful error message on deserialization.

Will leave open for now, in case I might find the original problem I was solving back then (it's all my code, I just do not recall details).
