### ISSUE TITLE
Add Automatic-Module-Name for JDK9 interoperability

### ISSUE THREAD

**Issue by zyxist** [FasterXML/jackson-core#397]
Hello! JDK9 introduces a new manifest entry `Automatic-Module-Name` that allows specifying the stable automatic module name for forward compatibility with Jigsaw.

It would be nice to specify the module name explicitly (something like `com.fasterxml.jackson.core`, I suppose), rather than rely on the default generator that creates the name from the JAR archive name.

The other Jackson projects should be updated as well.

**Comment by cowtowncoder** [comment]
That sounds reasonable, and should not require use of JDK 9 (which is a requirement for quite a while now).
Now, I haven't followed up on how module system works etc, but it should be possible to learn more about it.  I assume (for example) that each jar should get its separate module name?

One follow-up question: would the default name of `${maven.group.id}.${maven.artifact.id}` perhaps make sense? It could be added in a parent pom (`jackson-parent`), and only overridden in cases where it makes sense.

**Comment by aseovic** [comment]
Would it be possible to add Automatic-Module-Name to non-core modules as well?

**Comment by cowtowncoder** [comment]
@aseovic Sure, that is the plan. I was hoping to test this first with core components, but assuming it works it should be rolled out eventually to all modules. Approach taken is indeed to use default name, and that should work for all modules I think.

Help with PRs would help.
