### ISSUE TITLE
jackson 2.9.0 support for Java 6?

### ISSUE THREAD

**Issue by caigaopei** [FasterXML/jackson-core#398]

**Comment by cowtowncoder** [comment]
This is not a fucking support forum. For question USE THE GODDAMN MAILING LISTS.

**Comment by cowtowncoder** [comment]
Release notes also help:

https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9

(sometimes need to look at previous ones via https://github.com/FasterXML/jackson/wiki/Jackson-Releases)
