### ISSUE TITLE
Consider tracking how many bytes have been written in addition to how many are buffered

### ISSUE THREAD

**Issue by rockwotj** [FasterXML/jackson-core#409]
For a JSONGenerator there seems to be the ability to get the number of bytes in the current buffer, but not the ability to see how many have been flushed from the buffer. It would be useful to do this as to prevent us from serializing more than a certain amount to the output stream.

**Comment by cowtowncoder** [comment]
In theory `JsonLocation` should track number of bytes written, total, including both current buffer and flushed blocks. So it should be possible to get this information from `JsonGenerator`.

One possibly interesting idea could be allowing a hook for flushing (either before or after) which would allow some level of limiting, although this is something easy to do with wrapping of `OutputStream`, which can be achieved by registering "output decorator" (see `setOutputDecorator`) on `JsonFactory`.

**Comment by rockwotj** [comment]
Actually the method of using `setOutputDecorator` is actually a better solution than what I was proposing. Thanks!
