### ISSUE TITLE
Make a string serialized as number

### ISSUE THREAD

**Issue by spandananitdgp** [FasterXML/jackson-core#412]
I have a class with a string attribute. But, when I serialize it I want it to be a number.

public class Foo {
        private String id;
}

When I serialize an object with id = "4.1", I want the JSON to be:

{
    "id" : 4.1
}

How can I achieve this? I tried using @JsonFormat(shape = JsonFormat.Shape.NUMBER), but no luck.

**Comment by cowtowncoder** [comment]
In future, please ask usage question on mailing lists (https://groups.google.com/forum/#!forum/jackson-user).

But as to this question, there is no functionality to do such coercion declaratively.
You may want to either write a simple custom serializer (and attach it via annotation, like `@JsonSerialize(using=MySerializer.class)`), or have different accessor that returns number to serialize.
