### ISSUE TITLE
2.9.2 compile failed on android studio 3.0 rc1 with android.enableD8 enable

### ISSUE THREAD

**Issue by mymbrooks** [FasterXML/jackson-core#417]
My environment:
Windows 10 1709 x64
Android Studio 3.0 rc1
Gradle 4.2.1

gradle.properties:
android.enableD8=true

Error:com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\Brooks\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-databind\2.9.2\1d8d8cb7cf26920ba57fb61fa56da88cc123b21f\jackson-databind-2.9.2.jar
Error:com.android.builder.dexing.DexArchiveBuilderException: java.lang.RuntimeException: java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
Error:java.lang.RuntimeException: java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
Error:java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
Error:Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\Brooks\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-databind\2.9.2\1d8d8cb7cf26920ba57fb61fa56da88cc123b21f\jackson-databind-2.9.2.jar

**Comment by mymbrooks** [comment]
Android Studio 3.1 Canary 1 has fixed this bug, it's not jackons's problem, please close.

**Comment by bbincybbaby** [comment]
i have same bug in android studio 3.0 stable version

**Comment by milky-la** [comment]
I ran into this in 3.0 too. Upgraded to 3.1 (RC atm) and the build error is gone.
