### ISSUE TITLE
parser.getParsingContext().getCurrentValue() strange behaviours

### ISSUE THREAD

**Issue by deblockt** [FasterXML/jackson-core#420]
I have create a custom deserializer, who use default deserializer.
The goal of my custom deserializer is to deserialize jsonApi format. 

This work like this : 

``` scala
def deserialize(p: JsonParser, ctxt: DeserializationContext): Any = {
    val codec = p.getCodec()
    val node: JsonNode = codec.readTree(p) // read all json api format

    // read some object like data, id, etc..

    val attributes = rootNode.get("attributes")
    if (attributes == null) {
      throw ctxt.mappingException("missing attributes field")
    }
    
    // create a new entity to store json api input on final object (in my case is OU class)
    val jsonApiEntity = jsonApiDataBean.dataBeanClass.newInstance()
    
    // now I want to parse attributes who contains intresing data 
    // to do that I use the default deserializer (BeanDeserializer)
    val attributesParser = codec.treeAsTokens(attributes)
    attributesParser.nextToken()
    // I use the "into object" deserializer function to populate my object
    defaultDeserializer.deserialize(attributesParser, ctxt, jsonApiEntity)
   
    // and do some other things
}
```

All work fine for simple objects.

but I have a more complex object who need a custom deserializer for one property.

``` scala
class OU() extends Serializable {
   var code: String = _

  @JsonSerialize(using = classOf[TranslationSerializer])
  var translations: List[OULocalizedAttribute] = Nil

  var defaultOpeningHours: util.List[OUOpeningHour] = _
}
```

On this deserializer I want access at the current deserialized object. I have done somthing like this.

``` scala
class TranslationDeserializer() extends JsonDeserializer[List[_ <: LocalizedAttribute]] {
    override def deserialize(parser: JsonParser, context: DeserializationContext): List[_ <: LocalizedAttribute] = {
       val currentDeserializedObject = parser.getParsingContext().getCurrentValue()
   }
}
```

I try to parse this json, all is ok : 
``` json
{
  "data": {
    "attributes": {
      "code": "my new code",
      "translations": {},
      "defaultOpeningHours": []
    },
    "type": "organizationalUnit"
  }
}`
```

`currentDeserializedObject` contains `OU` who are currently deserialized.

Otherwise, if I try to parse this : 
``` json
{
  "data": {
    "attributes": {
      "code": "my new code",
      "defaultOpeningHours": [],
      "translations": {}
    },
    "type": "organizationalUnit"
  }
}`
```

`currentDeserializedObject` contains a list of OUOpeningHour. This is because `CollectionDeserializer` set `currentValue` with the deserialized list. So on my deserializer `currentValue` contains last deserialized value. 
I don't have any possibility to get currently deserailized object "OU" because on `TranslationDeserializer` the `parser.getParsingContext().getParent()` is null.

I don't have found any possibility to set a child/parent context when I call `codec.treeAsTokens(attributes)`.

There are a possibility to create a new child context when call `treeAsTokens`? I think this method should allow to create a new ParsingContext who have current ParsingContext as parent.

**Comment by cowtowncoder** [comment]
Which version of Jackson are you using?

I suspect what happens is that Tree-backed `JsonParser` does not set up context hierarchy properly. I think `TokenBuffer` was improved for 2.9 to do it properly, but tree-backed probably not. If so it would be good to improve handling to create seamless hierarchy there -- it is not trivially easy to do, but useful and necessary for cases like these.

**Comment by deblockt** [comment]
I use 2.8.10 version. I can't try with 2.9 vesion now

To fix this issue, I have extend `TreeTraversingParser` to allow to set a parent context.
I have done something like this : 
``` scala
  class WithParentTreeTraversingParser(n: JsonNode, codec: ObjectCodec, parentContext: JsonStreamContext)  extends TreeTraversingParser(n, codec) {

    val _parsingContext = new WithParentStreamContext(this._nodeCursor, parentContext)

    override def getParsingContext: JsonStreamContext = this._parsingContext
  }

  class WithParentStreamContext(streamContext: JsonStreamContext, parentContext: JsonStreamContext) extends JsonStreamContext {

    var _currentValue: AnyRef = _

    _type = -1

    override def setCurrentValue(v: AnyRef): Unit = this._currentValue = v
    override def getCurrentValue(): AnyRef = this._currentValue

    override def getParent(): JsonStreamContext = parentContext

    override def getCurrentName(): String = streamContext.getCurrentName()
    override def typeDesc(): String = streamContext.typeDesc()
  }
```

And instead of call `codec.treeAsTokens(attributes)` I do `new WithParentTreeTraversingParser(attributes, codec, p.getParsingContext())`

Thats works. 

The `TreeTraversingParser` can not be simply extended to allow parent parameter

**Comment by cowtowncoder** [comment]
I am not sure simply assigning parent context is safe, in general case, but the basic idea would be sound.
So, yes, `TreeTraversingParser` should allow passing of parent context, and make things work as if there was just one consistent context for processing.
But this is not necessarily trivial to do, and we need tests to ensure it does work.

Issue actually belongs under `jackson-databind` because it is not implemented in streaming API level. I'll file a new issue there, link to this one for background.

**Comment by cowtowncoder** [comment]
Created:

https://github.com/FasterXML/jackson-databind/issues/1803

**Comment by cowtowncoder** [comment]
Also: extending on why simple attach is not safe in general -- context is not only used for "current value" storage, but for actual decoding of context (whether we are in Object, Array, or root sequence, as well as current index/name). It is likely that these parts of context need to be copied (to some degree).
