### ISSUE TITLE
API changes in Jackson Core

### ISSUE THREAD

**Issue by lvc** [FasterXML/jackson-core#421]
Hi,

I'd like to share report on API changes and backward binary compatibility for the Jackson Core library: https://abi-laboratory.pro/java/tracker/timeline/jackson-core/

The report is generated by the https://github.com/lvc/japi-tracker tool for jars found at http://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/ according to the article https://wiki.eclipse.org/Evolving_Java-based_APIs_2.

The tool checks all public API methods and classes by default.

Please let me know if you'd like to see reports for any other Jackson modules in the tracker.

Thank you.

![jackson-core-2](https://user-images.githubusercontent.com/1517837/31849842-e75c157e-b651-11e7-8916-2391911a8d1f.png)

![jackson-core-1](https://user-images.githubusercontent.com/1517837/31849843-e77edb5e-b651-11e7-8708-98242771559e.png)

**Comment by cowtowncoder** [comment]
@lvc Hi there! If you want, perhaps you could add a Wiki page under this repo:

https://github.com/FasterXML/jackson-core/wiki

to contain snapshots of these reports? I think they are useful, but issue tracker may not be the best place.

I think reports on `jackson-databind` would be useful as well.

**Comment by lvc** [comment]
Report for `jackson-databind`: https://abi-laboratory.pro/java/tracker/timeline/jackson-databind/

Wiki: https://github.com/FasterXML/jackson-core/wiki/API-changes

Thank you.

![jackson-databind-1](https://user-images.githubusercontent.com/1517837/32439033-e6d9af22-c2fd-11e7-9887-1f00fe0a3dc9.png)

![jackson-databind-2](https://user-images.githubusercontent.com/1517837/32439032-e6be336e-c2fd-11e7-8fd3-5191dba49ebe.png)

**Comment by lvc** [comment]
Added daily-updated report for snapshot of a library (3.0.0): https://abi-laboratory.pro/java/tracker/timeline/jackson-core/

Snapshot: https://oss.sonatype.org/content/repositories/snapshots/com/fasterxml/jackson/core/jackson-core/

![jackson-core-3](https://user-images.githubusercontent.com/1517837/32442306-020d2982-c30c-11e7-8ab2-26c3222ae903.png)
