### ISSUE TITLE
Add option to handle invalid case (e.g., array of objects not contained in array delimiters)

### ISSUE THREAD

**Issue by wbuchanan** [FasterXML/jackson-core#423]
I've come across several cases where users receive incorrectly formatted JSON.  More specifically, users will get payloads that should be formatted as an array of objects as a set of line delimited objects : 

```JSON
{"reviewerID": "A2IBPI20UZIR0U", "asin": "1384719342", "reviewerName": "cassandra tu \"Yeah, well, that's just like, u...", "helpful": [0, 0], "reviewText": "Not much to write about here, but it does exactly what it's supposed to. filters out the pop sounds. now my recordings are much more crisp. it is one of the lowest prices pop filters on amazon so might as well buy it, they honestly work the same despite their pricing,", "overall": 5.0, "summary": "good", "unixReviewTime": 1393545600, "reviewTime": "02 28, 2014"}
{"reviewerID": "A3M1PLEYNDEYO8", "asin": "B00004Y2UT", "reviewerName": "G. Thomas \"Tom\"", "helpful": [0, 0], "reviewText": "Perfect for my Epiphone Sheraton II.  Monster cables are well constructed.  I have several and never had any problems with any of them over the years.  Got this one because I wanted the 90 degree plug.", "overall": 5.0, "summary": "Great cable", "unixReviewTime": 1215302400, "reviewTime": "07 6, 2008"}
{"reviewerID": "AMNTZU1YQN1TH", "asin": "B00004Y2UT", "reviewerName": "Kurt Robair", "helpful": [0, 0], "reviewText": "Monster makes the best cables and a lifetime warranty doesnt hurt either. This isnt their top of the line series but it works great with my bass guitar rig and has for some time. You cant go wrong with Monster Cables.", "overall": 5.0, "summary": "Best Instrument Cables On The Market", "unixReviewTime": 1389139200, "reviewTime": "01 8, 2014"}
```

Is it possible to add a configuration option to `JsonParser` that could infer the intention in these cases (e.g., something like "\},?\s*\{" to detect the consecutive  closing/opening object delimiters)?

**Comment by cowtowncoder** [comment]
Decoder is not based on regexps so there is no easy way to change low-level rules.

But if what you are looking for is simple sequence of root-level values, that works as-is.
Question is rather how are you trying to read this content? If using databind, `ObjectReader.readValues(input)` gives `MappingIterator`, which allows reading of such sequences.
If using straight streaming API, you will simply get Objects exposed and can handle them the way you want.

**Comment by wbuchanan** [comment]
@cowtowncoder 
The implementation that I am using is [here](https://github.com/wbuchanan/StataJSON/blob/issue2/src/main/java/org/paces/Stata/Input/FlatJSON.java).  Using the Tree to parse the data so I can retain/track lineage of the values as well.

**Comment by cowtowncoder** [comment]
@wbuchanan Ok at this point I am  not sure what'd be missing. You can read trees from sequences too: not just one (because there wouldn't be any legal presentation of such sequence), but multiple ones, and if you want, can re-build an array with contents.
Actually you should be able to read such a sequence too, with something like

    List<JsonNode> l = mapper.readerFor(JsonNode.class).readValues().readAll();

I hope this helps: for more usage questions, please use mailing list at

    https://groups.google.com/forum/#!forum/jackson-user
