### ISSUE TITLE
Add feature to JsonParser to retrieve data for specific path(s)

### ISSUE THREAD

**Issue by ashtonhogan** [FasterXML/jackson-core#424]
It would be really useful if the Streaming API had support for json path retrieval. For example:

**Input Json:**
```
{
  "name":"John",
  "surname":"Doe",
  "addressHistory": [
    "27 House Lane, Earth",
    "31 House Lane, Mars"
  ],
  "employmentHistory": [
    "Freedom Corp",
    "DIY Corp",
    "Simple Corp"
  ]
}
```

**Utility:**
```
public JsonNode retrieve(File file, String... jsonPaths) {
 //Streaming API code here
}
```

**Usage:**
```
public static void main(String[] args) {
    JsonNode jsonNode = retrieve(new File("data.json"), "person.addressHistory", "person.employmentHistory[2]");
}
```

**Output Json:**
```
{
  "addressHistory": [
    "27 House Lane, Earth",
    "31 House Lane, Mars"
  ],
  "employmentHistory": [
    "Simple Corp"
  ]
}
```

**Comment by cowtowncoder** [comment]
That wouldn't really work at streaming level, given that `JsonNode` implementation (and in general, handling of higher level structures) is in `jackson-databind`.

There is however a way to filter by a single path expression using combination of `JsonPointerBasedFilter` as `TokenFilter`, and constructing `FilteringParserDelegate`.
In theory you could combine these pieces for matching multi-matcher.
I would be open to contribution for including such implementation.

On the other hand, `JsonNode` has `at()` method, and `ObjectReader` similarly. So you can read sub-trees, with same limitation of a single path pression.

**Comment by ashtonhogan** [comment]
There is an issue where in many cases systems need data from large json files and reading portions of the file is the only way to get the information without using all available memory

I had a look around but could not find any documentation on the classes you mentioned to read json by json path in a large json file. Can you please provide a link to where people might find this?

**Comment by cowtowncoder** [comment]
What I wrote above should be enough to look at API, wrt use of `JsonPointer`. In streaming, you can construct `JsonPointerBasedFilter`, or, perhaps implement `TokenFilter`. Applying multiple filters may not be trivial, I had hell of a time to make single-filter work reliably. Or maybe it's easier based on existing  work.

And on databind package there's `ObjectReader.at()` which essentially attaches such filter to `JsonParser`, and then uses regular binding.
Finally, `JsonNode` also has `at()` method to find sub-tree if one exists (or return `MissingNode` if not).

I hope this helps.

**Comment by ashtonhogan** [comment]
This is as far as I could get with the above advice

```
File file = new File("example.json");
JsonFactory jsonFactory = new JsonFactory();
try (JsonParser jsonParser = jsonFactory.createParser(file)) {
    while (jsonParser.nextToken() != JsonToken.END_OBJECT) {
        JsonPointer jsonPointer = jsonParser.getParsingContext().pathAsPointer();
        if (jsonPath.equalsIgnoreCase(jsonPointer.toString())) {
            JsonPointerBasedFilter jsonPointerBasedFilter = new JsonPointerBasedFilter(jsonPointer);
            return jsonPointerBasedFilter.getJsonNode(); 
        }
    }
}
```

Unfortunately for me, `jsonPointerBasedFilter.getJsonNode();` does not exist and I'm not sure I'm the best person to be implementing it either

**Comment by cowtowncoder** [comment]
There is no method like `getJsonNode` because this is all still part of streaming API so no object model exists. Only state. So you would need to access current event that parser points to, and get relevant content (text, number and such).
This could be done by passing parser instance to `ObjectMapper` or `ObjectReader` as source, however, so you could use `readTree()` to build node.
