### ISSUE TITLE
JsonIdentityInfo fails to resolve references with Access.READ_ONLY properties

### ISSUE THREAD

**Issue by kmorozov** [FasterXML/jackson-core#426]
Imagine the following java class:
```Java
@JsonIdentityInfo(
  generator = ObjectIdGenerators.PropertyGenerator.class,
  property = "name",
  scope = Person.class
)
public class Person {
  String name;
  @JsonProperty(access = JsonProperty.Access.READ_ONLY)
  Person father;
  Person mother;
  // getters + setters omitted
}
```
When I serialize a person object, I might get something like this:
```json
{
  "name" : "Clone of Bob",
  "father" : {
    "name" : "Bob"
  },
  "mother" : "Bob"
}
```
However, when I try to read this with the same mapper the deserialization will fail because Jackson will ignore the `father` property and then throw an `UnresolvedForwardReference` exception when it tries to read the `mother` property.

**Comment by cowtowncoder** [comment]
Could you please refile this at `jackson-databind`: support for Object Id is implemented there and not here (only streaming parser/generator is)?

**Comment by kmorozov** [comment]
Sure thing. Thanks for pointing me in the right direction.
