### ISSUE TITLE
JsonToken.VALUE_NUMBER_FLOAT - documentation is a copy of VALUE_NUMBER_INT

### ISSUE THREAD

**Issue by grooverdan** [FasterXML/jackson-core#428]
At https://github.com/FasterXML/jackson-core/blob/master/src/main/java/com/fasterxml/jackson/core/JsonToken.java#L91

The comments are for VALUE_NUMBER_INT

sorry for the nit, just happened to see it.

**Comment by cowtowncoder** [comment]
Au contraire, thank you for reporting it. I'd rather have correct javadoc than incorrect one.

Thanks!

**Comment by cowtowncoder** [comment]
Fixed.

**Comment by grooverdan** [comment]
96633b7f3715788e608273117a3831ac5ab972f6 - works for me. Thanks.
