### ISSUE TITLE
Jackson-Core newest release - Does it update struts to version 2.5.14.1? 

### ISSUE THREAD

**Issue by strutyourstuff** [FasterXML/jackson-core#429]
Is there any documentation on the newest release of the newest Jackson-Core also updating Struts (by The Apache Software Foundation) to 2? 
You know, because that one time earlier in 2017 where Equifax reported they had that breach and blamed not updating struts and all that.

**Comment by cowtowncoder** [comment]
@strutyourstuff Please ask usage questions on mailing list -- issue tracker is for reporting issues:

https://groups.google.com/forum/#!forum/jackson-user

But release notes for Jackson versions are on `jackson` main portal wiki:

https://github.com/FasterXML/jackson/wiki/Jackson-Releases

I am not sure about connection to Struts as Jackson project is not related to Struts project.
But if Struts library/framework uses Jackson it would seem likely maintainers of that project would have more information on version they use.

**Comment by strutyourstuff** [comment]
Thank you for reaching out. I am trying to verify if struts was embedded (or not embedded) into Jackson.

Yelena Williams

Systems Support Analyst
Application Competency Center | Product Management

Wells Fargo EIT | Ocotillo Center 2600 S. Price Road, Chandler, AZ 85268 |
MAC S3929-045 | Office 480-887-2876 | Cell 520-216-0883

Yelena.Williams@wellsfargo.com<mailto:Yelena.Williams@wellsfargo.com>

**Comment by cowtowncoder** [comment]
@strutyourstuff Ah ok. No, Jackson does not include Struts as a dependency for any component.
