### ISSUE TITLE
Improve error messages during deserialization

### ISSUE THREAD

**Issue by m-titov** [FasterXML/jackson-core#434]
Could you please improve error messages during deserialization?
For example, could this error message
```
org.springframework.http.converter.HttpMessageNotReadableException: Could not read JSON document: Cannot deserialize instance of `com.google.common.collect.ImmutableList` out of START_OBJECT token
 at [Source: (ByteArrayInputStream); line: 1, column: 1]; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `com.google.common.collect.ImmutableList` out of START_OBJECT token
 at [Source: (ByteArrayInputStream); line: 1, column: 1]
```
contain source 

> {"status":404,"message":"Not Found"}

 when we try to deserialize it ? Or could you please provide some way to get source as text from jackson deserialization exception?

**Comment by cowtowncoder** [comment]
No, jackson streaming parser can not really reliably provide full input document. Content is read in chunks, in general. Input may be of indefinite size, and only relatively small amount (8kb) is read at any given time. Larger content chunks may be retained (long String values for example).

But whoever calls it, however, could buffer it -- in this case Spring framework.
So this would be more of a feature request for web framework(s).
They could choose to either fully buffer content (possibly only in debug mode), or some subset to give context.

**Comment by m-titov** [comment]
Ah.. Ok..
