### ISSUE TITLE
Prevent UTF8JsonGenerator#writeString(Reader reader, int len) throw exception

### ISSUE THREAD

**Issue by mehretaban** [FasterXML/jackson-core#435]
It is quite useful, **UTF8JsonGenerator#writeString(Reader reader, int len)** method could write upto len characters regardless how many characters are available in the Readers, in other words  it doesn't throw exception when Reader has less than len characters. 

Same request for binary data in **UTF8JsonGenerator#writeBinary(InputStream data, int dataLength)**.

**Comment by cowtowncoder** [comment]
Unfortunately I am not sure this is possible since some data formats require length information up-front, and encoded and possibly write it in advance. If length is not really known, all content must be fully buffered.

**Comment by cowtowncoder** [comment]
One other thing to note: as per Javadocs, passing length of `0` indicates that all content is to be written, regardless of how much is available.

One possible improvement idea would be to allow passing negative numbers, which would indicate maximum amount, but not require it: so, for example, passing -1 would write at most 1 character (but also allow empty content).

**Comment by mehretaban** [comment]
It's good to know the main reason that I suggested this feature is about truncating large InputStreams/Readers during json streaming, then  I thought, perhaps it's better not introducing this feature into Jackson and only implement truncating InputStream/Reader by extending FilterInputStream/FilterReader and passing those instances to the above methods.
(or using **org.apache.commons.io.input.BoundedInputStream/BoundedReader**)

**Comment by cowtowncoder** [comment]
@mehretaban Yes I think that implementing this for `Reader` or `InputStream` is more modular and better approach from design perspective.
