### ISSUE TITLE
It appears I have to specify @JsonTypeInfo and @JsonSubTypes twice.

### ISSUE THREAD

**Issue by rdifalco** [FasterXML/jackson-core#436]
I have a concrete class with a builder. So it uses the `JsonDeserialize(builder=` annotation. Further it has an enum type field and a field that is an interface. It appears that I have to define JsonTypeInfo and JsonSubTypes twice. Both on the value field and then again on the withValue field. 

Since it's only used for deserialization I assumed I could just specify it above the withValue field.

**Comment by cowtowncoder** [comment]
Could you please:

1. Refile at `jackson-databind`: `jackson-core` is for streaming parser/generator
2. Explain with an example what you would like to see instead (or what is not working). Textual explanation is useful in addition, but without example not as easy to follow.
