### ISSUE TITLE
Way to turn off parsing of incorrect dates?

### ISSUE THREAD

**Issue by jonchamplin** [FasterXML/jackson-core#441]
I am reading dates from a yaml file using the YAMLFactory() object mapper which is working fine.  However, in the YAML file if I enter 2017-13-01 it is automatically translated to Jan 1st 2018.  Can I set a property on the YAMLFactory or ObjectMapper so that an exception is thrown when an invalid date is encountered instead of changing it into a different valid date?

**Comment by cowtowncoder** [comment]
Please use mailing list for usage questions: 

https://groups.google.com/forum/#!forum/jackson-user
