### ISSUE TITLE
Custom minimal UUID Serializer

### ISSUE THREAD

**Issue by efenderbosch** [FasterXML/jackson-core#442]
The databind project has a ``UUIDSerializer`` that writes out UUIDs with type info like this:

``["java.util.UUID","tb4ea2ea3-591d-45cf-8846-93550c0d5894"]`` (58 characters)

I'd like to use a short type name and use base64 encoding of the msb/lsb, which gets me down to:

``[“uuid”,”tOouo1kdRc-IRpNVDA1YlA"]`` (33 characters)

I've written my custom Serializer (extending ``StdScalarSerializer``):
```java
public void serialize(UUID value, JsonGenerator gen, SerializerProvider provider) throws IOException {
    ByteBuffer buffer = ByteBuffer.allocate(16);
    buffer.putLong(value.getMostSignificantBits());
    buffer.putLong(value.getLeastSignificantBits());
    byte[] bytes = buffer.array();
    String base64 = Base64.getUrlEncoder().encodeToString(bytes).substring(0, 22);
    gen.writeString(base64);
}
```

And custom Deserializer (extending ``FromStringDeserializer``):
```java
protected UUID _deserialize(String value, DeserializationContext ctxt) {
    byte[] bytes = Base64.getUrlDecoder().decode(value);
    ByteBuffer buffer = ByteBuffer.wrap(bytes);
    long msb = buffer.getLong();
    long lsb = buffer.getLong();
    return new UUID(msb, lsb);
}
```

I've attempted to register a MixIn:
```java
private static final SimpleModule MODULE = new SimpleModule().
        addSerializer(new UUIDSerializer()).
        addDeserializer(UUID.class, new UUIDDeserializer()).
        registerSubtypes(new NamedType(UUID.class, "uuid")).
        setMixInAnnotation(UUID.class, UUIDMixIn.class);

private static final ObjectMapper MAPPER = new ObjectMapper().
        registerModule(MODULE).
        registerModule(new JavaTimeModule()).
        enableDefaultTyping();
```

```java
@JsonTypeName("uuid")
@JsonTypeInfo(use = NAME)
@JsonTypeIdResolver(TypeNameIdResolver.class)
public interface UUIDMixIn { }
```

No matter what I've tried the type info still gets written as ``java.util.UUID`` instead of ``uuid``.

Am I missing something simple? Apologies if this isn't the correct sub-project.

Using Jackson 2.8.10 since 2.9.x breaks some dependencies for us.

**Comment by cowtowncoder** [comment]
Code seems legit, so there may be a bug somewhere. It could be useful to further see if simple (non-polymorphic) usage of `UUID` field would work with custom (de)serializer (I assume it would).
A simple unit test would be helpful too, just to make sure I do not miss something obvious, although explanation is clear and straight-forward. But I have noticed I am good at making unintentional changes that change test not to fail :)

This does indeed belong under `jackson-databind`, if you could re-file there (I wish github had some kind of Transfer functionality but no...).

**Comment by efenderbosch** [comment]
It works w/ top level objects, but not for things like a Map w a UUID as the key. I'm going to change how it is working, so this isn't really relevant anymore. Thanks.

**Comment by cowtowncoder** [comment]
@efenderbosch Ah -- do note that key serializers, deserializers are separate from value (de)serializers, and must be registered separately. This is because in JSON keys can only be strings, and are exposed as different token in stream. But if you register key (de)serializer, that definitely should work.
