### ISSUE TITLE
Please update the release notes for 2.9.2, 2.9.3, and 2.9.4 in https://github.com/FasterXML/jackson-core/blob/master/release-notes/VERSION-2.x

### ISSUE THREAD

**Issue by garydgregory** [FasterXML/jackson-core#443]
Please update the release notes for 2.9.2, 2.9.3, and 2.9.4 in https://github.com/FasterXML/jackson-core/blob/master/release-notes/VERSION-2.x

**Comment by cowtowncoder** [comment]
Git merge bothced wrt renaming, fixed.
