### ISSUE TITLE
Can Jackson automatically create a getter class from an interface ?

### ISSUE THREAD

**Issue by samfrach** [FasterXML/jackson-core#445]
I would like to deserialize a web service that returns for example Vehicle.

interface Vehicle {
     String getProp2();
     String getProp1()
}

I have the feeling I have to create a VehicleImpl class that implements Vehicle.
Is there not a way that jackson do it automatically ? It is just a matter of getters...

thank you

**Comment by cowtowncoder** [comment]
https://groups.google.com/forum/#!forum/jackson-user
