### ISSUE TITLE
jackson-core-2.5.4 + Centos 7 + Tomcat 8.x- startup error

### ISSUE THREAD

**Issue by RohitGupta31** [FasterXML/jackson-core#446]
Hi,

I have upgraded tomcat to 8 from 7 and started getting the following error while starting tomcat

Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonParser.setCurrentValue(Ljava/lang/Object;)V
com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:230com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25)
com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:523)
com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeWithErrorWrapping(BeanDeserializer.java:461)

It used to work fine when using tomcat 7 the jackson-core dependency is 2.5.4 & that method exists in the class JsonParser. Weirdly if I deploy the same code in a windows box in tomcat 8 i don't see that startup error. I don't see any other jar which is clashing and it used to work before on the centos box in tomcat 7.
Any ideas?

**Comment by cowtowncoder** [comment]
You have a version incompatibility: most likely older minor version of `jackson-core`, newer version of `jackson-databind`. Sometimes it is possible to accidentally have multiple jars of same library, in which case one is arbitrarilly used (or, worse, some classes from within more than one of them is...).

**Comment by RohitGupta31** [comment]
actually I did verify the version for jackson-core & databind they both are 2.5.4. There are also no multiple jars of the same library. Strangely, when I deploy the code on tomcat8- windows box it works(the same dependencies). Any other ideas?

**Comment by cowtowncoder** [comment]
@RohitGupta31 Nonetheless this is what the problem is: classes deployed, for `jackson-core`, are not the same or compatible with ones used for compiling version of another component (most likely `jackson-databind`) as deployed. Also make sure to know all parts of classpath, and perhaps embedded jars in containers (war / ear files). Something somewhere has incompatible version.
