### ISSUE TITLE
BeanPropertyWriter performance improvement

### ISSUE THREAD

**Issue by testn** [FasterXML/jackson-core#449]
Affected version: all

Relevant code (BeanPropertyWriter.java):
```        
final Object value = (_accessorMethod == null) ? _field.get(bean)
                : _accessorMethod.invoke(bean);
```

the above code looks benign. However, `_accessorMethod.invoke(bean)` is actually calling `public Object invoke(Object obj, Object... args)
        throws IllegalAccessException, IllegalArgumentException,
           InvocationTargetException`. It will be much more efficient to create a static empty `Object[]` and pass to `_accessorMethod.invoke` call. This helps reducing the garbage significantly when we need to serialize a lot of beans with multiple getters/setters

**Comment by cowtowncoder** [comment]
@testn Where do you see that code? 2.9 branch (and `master`) have bit different code; I think change was done few months back, based on similar comments.

**Comment by testn** [comment]
@cowtowncoder you're right. It's actually in jackson-databind

**Comment by testn** [comment]
I found the commit in 2.9 branch.
https://github.com/FasterXML/jackson-databind/commit/50e4de4a2e839a004bf4654d0ef4de753d55c31c
