### ISSUE TITLE
Jackson reports wrong locations for JsonEOFException

### ISSUE THREAD

**Issue by wastevenson** [FasterXML/jackson-core#455]
I noticed the the locations reported for JsonEOFException are wrong for both InputStream and Reader based parsers. The values are about 2x higher than they should be. It looks like the problem is that in _loadMore for UTF8StreamJsonParser and in ReaderBasedJsonParser the value for _currInputRowStart is adjusted even if the read fails but _inputPtr is set to 0 only if the read succeeds. When the location is calculated for the exception the count from the last buffer is included in both from _inputPtr and in _currInputRowStart doubling the value.

**Comment by cowtowncoder** [comment]
Sounds plausible. Would it be possible to get a simple reproduction with test input stream and/or reader that would exhibit the problem?

**Comment by DiggidyDale** [comment]
Is there any update on this, as I am currently having an issue and I can't pinpoint the issue as my JSON string of 173 characters is reporting an EOF issue at column 345

**Comment by cowtowncoder** [comment]
At this pointI will not have time to work on this any time soon. So any progress would likely be from contributions.

**Comment by toddobryan** [comment]
With current master, here's a test case that's probably related to this:
```

**Comment by cowtowncoder** [comment]
Thank you @toddobryan!

**Comment by cowtowncoder** [comment]
Added a failing unit test -- definitely seems to double up counts; I wonder if that is due to special handling of root-level values. Hope to look into this again soon; problem affects both `Reader` (char-based) and `InputStream` (byte-based) parsers, via this trivial test.

**Comment by toddobryan** [comment]
Sending a pull request that includes tests for `getTokenLocation()` and `getCurrentLocation()` at the end of the stream.

**Comment by cowtowncoder** [comment]
Thanks, but I already added tests (based on snippet above).

**Comment by toddobryan** [comment]
Oh, my PR includes a fix.

**Comment by cowtowncoder** [comment]
ahhh! Excellent.

So, just one process thing in that case: unless I have asked for and received CLA, that would be needed before the first contribution. It can be found here:

    https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf

and the usual mechanism is to print it, fill, sign & scan, email to `info` at fasterxml dot com.
Only needs to be done once and good from that point on for all Jackson projects.

**Comment by toddobryan** [comment]
https://github.com/FasterXML/jackson-core/pull/557

I'll deal with the CLA later today.

**Comment by cowtowncoder** [comment]
Thank you!

**Comment by cowtowncoder** [comment]
@toddobryan Hi there! Sorry to bother you but I was wondering if you might be able to do this next week? Was hoping to get this in 2.10.0. 
Not a big deal if not, will then go in 2.10.1, but it's a good improvement.
