### ISSUE TITLE
Mixin not working with class level annotations (to be precise, @JsonSubTypes)

### ISSUE THREAD

**Issue by duckladydinh** [FasterXML/jackson-core#465]
[jacksonsample.zip](https://github.com/FasterXML/jackson-core/files/2130338/jacksonsample.zip)
Dear community,

I have a class called Human and I want to add @JsonSubTypes annotation to it via Mixin. I created an empty class HumanMixin with the annotation I want as follows and adds to object mapper via objectMapper.addMixin(Human.class, HumanMixin.class). The ridiculous thing is that the @JsonSubTypes annotation is completely ignored while the @JsonIgnore and @JsonAutoDetect works as normal. Did I do something wrong, or is this a bug? I am using version 2.8.4 of Jackson from Springfox. Thank you.

```java
abstract public class Human extends Creature {
	private String name;
	private String socialSecurityNumber;
	protected Human() {}
	public Human(String name, Integer id, String socialSecurityNumber) {
		super(id);
		this.name = name;
		this.socialSecurityNumber = socialSecurityNumber;
	}
}
```

```java
@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.ANY)
@JsonIdentityInfo(generator=ClassNameWithIntSequenceGenerator.class)
@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, property = "@class")
@JsonSubTypes({
		@JsonSubTypes.Type(value = Teacher.class),
		@JsonSubTypes.Type(value = Student.class)
})
public class HumanMixin extends Human {
	@JsonIgnore  String name;
}
```

**Comment by cowtowncoder** [comment]
Please include reproduction: class declarations are not enough to reproduce the issue you see.

Also:

1. Version 2.8.4 is not the latest patch from 2.8 -- please try later one (2.8.11 I think) , as patch version are binary compatible
2. To isolate the issue it makes sense to try stand-alone test, outside of framework -- a VERY common mistake is that framework is not using `ObjectMapper` you are configuring.

**Comment by duckladydinh** [comment]
What else class definitions would you like to see? Please tell me and I will make it.

This is a standalone test. I also test the that the object mapper I configured was being used since as I said, the @JsonAutoDetect and @JsonIgnore are still working as expected. Only the @JsonSubTypes does not work not.

In addition, I have tested it with versions 2.9.5 and 2.9.6 and got the same results.

**Comment by duckladydinh** [comment]
I have added a simple project. As you see. @JsonSubTypes in the mixinhas no influence (no inheritance allOf...) in the generated swagger api (localhost:8080/swagger.json), while the @jsonautodetect is still working. The jackson version used is 2.9.6.

**Comment by duckladydinh** [comment]
Is there anyway to do it backwards? Like @JsonParent(value = SuperClass.class)

**Comment by cowtowncoder** [comment]
@duckladydinh Jackson has no control over what Swagger does, so what I really need is a Jackson-only reproduction, showing what is wrong -- ideally not by printing out something to look at, but by testing.
But if it's print out, please include expected and actual output here on issue. I can and do look at projects but anything that can make understanding problem quicker and simpler helps.

As to Swagger: Swagger uses its own introspection it is possible that it does not apply mix-ins, for example. This is why it is important to isolate components: if problem is on Swagger side, then Swagger team would need to be notified. If not, we can work on it from Jackson side without worrying about how Swagger is using the information.
