### ISSUE TITLE
Build failure for source code v2.8.9

### ISSUE THREAD

**Issue by jayanth-ganganahalli** [FasterXML/jackson-core#471]
Hi,
I am not able to build the source code. I took a fresh pull from "https://github.com/FasterXML/jackson-core/tree/jackson-core-2.8.9" and trying to build the source code using "mvn clean install -U" in command prompt.
Below is the error message:
"[ERROR] Plugin org.apache.maven.plugins:maven-install-plugin:2.3.1 or one of its
 dependencies could not be resolved"

While trying to add the dependency jar files into my local repository, I got the below error message:
"[ERROR] Failed to execute goal com.google.code.maven-replacer-plugin:replacer:1.
5.2:replace (process-packageVersion) on project jackson-core: File 
'..\..\src\main\java\com\fasterxml\jackson\core\json\PackageVersion.java
.in' does not exist -> [Help 1]"

Please help me in building the source code on my windows 10 machine which is using the maven version 3.3.

**Comment by cowtowncoder** [comment]
`PackageVersion.java` is generated by maven-replacer-plugin so I don't know what the problem here is.

**Comment by harsha-99** [comment]
Hi, I am facing the same issue moreover maven-replacer-plugin is being highlighted red in IDE

**Comment by cowtowncoder** [comment]
@harsha-99 Err why should we care? version 2.8.9 is ancient.

**Comment by harsha-99** [comment]
I was facing this with 2.16, but never mind I was able to resolve

**Comment by cowtowncoder** [comment]
@harsha-99 Going forward it is good idea to indicate diff from original issue/title. Glad you were able to resolve it.
