### ISSUE TITLE
Allow CDATA tags when Feature.ALLOW_COMMENTS (or similar) is enabled

### ISSUE THREAD

**Issue by HansBrende** [FasterXML/jackson-core#472]
Currently enabling `JsonParser.Feature.ALLOW_COMMENTS` allows the C-style comments beginning with `//` and `/*`. However, it's also possible to see JSON (e.g. JSON-LD) containing CDATA markers embedded in webpages.

Here's an example of something you could see inside, e.g., a `<script type="application/ld+json">` html element:
```
<![CDATA[ {"@context":"http://schema.org", "@type":"Event", "name":"My Cool Event", ]]>
<![CDATA["startDate":"2018-08-05T15:30:00+00:00", 
"endDate":"2018-08-05T16:30:00+00:00"}]]>
```
which should be treated the same as:
```
{"@context":"http://schema.org", "@type":"Event", "name":"My Cool Event", 
"startDate":"2018-08-05T15:30:00+00:00", 
"endDate":"2018-08-05T16:30:00+00:00"}
```

when `JsonParser.Feature.ALLOWS_COMMENTS` (or something similar, e.g., `JsonParser.Feature.ALLOWS_CDATA_SECTIONS`) is enabled. 

(Note: in most cases, the CDATA markers are commented out, e.g., `/* <![CDATA[ */ {"some" : "json"} /* ]]> */`, so in these cases, the existing `ALLOWS_COMMENTS` feature is sufficient.)

**Comment by cowtowncoder** [comment]
This is not legal JSON content in any way, but I am curious as to what specification allows such constructs? I don't think this is something I'd like to support directly, but perhaps it would be worth considering if it was possible to allow attaching of handlers for all kinds of non-conforming content.
And if so, what should interface look like, then implement.
