### ISSUE TITLE
Using @JsonUnwrapped together with @JsonAnySetter

### ISSUE THREAD

**Issue by Megamiun** [FasterXML/jackson-core#487]
Jackson version: 2.9.6(with jackson-module-kotlin)

Hello, I'm trying to make a generic class that would capture extra non declared fields from another class to a json using a JsonUnwrapped annotation, but it seems it is impossible in the current form of the library, as in the example:

```kotlin
class CommonExtra {
    val test: String? = null

    @get:JsonAnyGetter
    var extraFields: MutableMap<String, Any?> = mutableMapOf()

    @JsonAnySetter
    fun setField(key: String, value: Any) { extraFields[key] = value }
}

class NonGenericExtra {
    @JsonUnwrapped
    var data: Data? = null

    @get:JsonAnyGetter
    var extraFields: MutableMap<String, Any?> = mutableMapOf()

    @JsonAnySetter
    fun setField(key: String, value: Any) { extraFields[key] = value }
}

class GenericExtra<T> {
    @JsonUnwrapped
    var data: T? = null

    @get:JsonAnyGetter
    var extraFields: MutableMap<String, Any?> = mutableMapOf()

    @JsonAnySetter
    fun setField(key: String, value: Any) { extraFields[key] = value }
}

data class Data(val test: String)

fun main(args: Array<String>) {
    val mapper = ObjectMapper()
    mapper.registerKotlinModule()

    val json = """{"test":"test", "extra":"extra"}"""
    
    println("Non Generic: ${mapper.readValue<NonGenericExtra>(json).extraFields}")
    println("Generic: ${mapper.readValue<GenericExtra<Data>>(json).extraFields}")
    println("Common: ${mapper.readValue<CommonExtra>(json).extraFields}")
}

```

That give me the output:

```
Non Generic: {test=test, extra=extra}
Generic: {test=test, extra=extra}
Common: {extra=extra}
```

It seems a little sad to me that the two annotations don't work together, as they would allow us to simplify the declaration of asking for the extra fields

**Comment by cowtowncoder** [comment]
It is bit hard to comment as example is not in plain Java, so  it may be that another module (Kotlin?) could have its issues. But you are right, combination of any-setter and unwrapped is unlikely to work due to the way `@JsonUnwapped` handling is implemented: main deserializer has no way of knowing which would be handled via unwrapped, and which should instead be directed to any-setter. So either too few or too many would be passed.
This is not something that would be impossible to support but a limitation specifically of implementation of `@JsonUnwrapped` support. I hope it can be fixed for Jackson 3.0, in some way.

**Comment by Megamiun** [comment]
Interesting, is there any work in version 3.0 today?

I would love to know if there is any prevision for when it will launch or to try to help to implement this.

**Comment by cowtowncoder** [comment]
@Megamiun yes, `master` is for 3.0. But it is long ways off, unfortunately, and moving rapidly at times (that is, occasional major api changes, still trying to figure out some aspects of configuration bia builders).

**Comment by Megamiun** [comment]
Oh, ok. Can I try to submit some PRs related to this feature in the future?

(I don't know when I would be prepared to submit it, but if possible, I would like to help)

**Comment by cowtowncoder** [comment]
@Megamiun sure, PRs are always welcome. My main concern with 3.0 (`master`) is simply that it will still be changing rapidly, meaning that it may be frustrating to try to keep up with changes when working in parallel.

But yes, if you happen to have time and interest, I would definitely appreciate help. I haven't had time to look into this at all, only have some ideas. Main thing it seems to me is that "unwrapping" handlers (esp. deserializer) need to be able to pass information about embedded properties, so there has to be some way for "regular" `BeanDeserializer` and unwrapping variant to communicate, for former to know which properties are to be delegated and which not.

**Comment by cowtowncoder** [comment]
Quick note: this belongs in `jackson-databind`; `jackson-core` is just for low-level streaming API.
May be refiled there.
