### ISSUE TITLE
JsonParser should have option to separate parsed data from rest of input

### ISSUE THREAD

**Issue by GotoFinal** [FasterXML/jackson-core#490]
Currently there is no way to find where jackson finished reading their data:
```java
StringReader stringReader = new StringReader("{\"name\": \"some name\"} some other data");

JsonFactory jsonFactory = new JsonFactory();
jsonFactory.setCodec(new ObjectMapper());
JsonParser jsonParser = jsonFactory.createParser(stringReader);
Map value = jsonParser.readValueAs(HashMap.class);

String restOfInput = ???; // " some other data"
```
StringReader will be already fully consumed due to internal buffering, so there is no way to get rest of data and pass it somewhere else, it would be great to be able to control that, like ability to get the position of JsonParser, or some option to disable that buffering, or just `.mark` before buffering and `.reset` at the and + skip amount of bytes that were sill part of parsed data - as this will not reduce performance or expose any fields.

**Comment by GotoFinal** [comment]
Oh... after a bit of debugging as I wanted to check if this can be implemented I found out that this is already here: `jsonParser.getCurrentLocation();` sorry ;)

**Comment by cowtowncoder** [comment]
Actually there is another method (well, 2 methods) that was specifically designed to help here:

    public int releaseBuffered(Writer w);
    public int releaseBuffered(OutputStream out);

where content may be accessed. Location can also be used like that, of course.
