### ISSUE TITLE
Stricly name module for JPMS

### ISSUE THREAD

**Issue by GedMarc** [FasterXML/jackson-core#498]
Please can you strictly name the jackson modules so that automatic naming is not used in JPMS

This will enable the following functionality in module-info.java

```
	requires transitive com.fasterxml.jackson.annotation;
	requires transitive com.fasterxml.jackson.core;
	requires transitive com.fasterxml.jackson.databind;
```
etc..
This way boot/base modules do not need to explicitly define the automatic module name in the libraries

The moditect plugin can perform this function for JDK 7 and JDK 8 builds via the following
https://github.com/moditect/moditect

I haven't created a PR because it would be needed across all the projects, but it is very simple to implement.

```
	<plugin>
				<groupId>org.moditect</groupId>
				<artifactId>moditect-maven-plugin</artifactId>
				<version>1.0.0.Beta1</version>
				<executions>
					<execution>
						<id>add-module-infos</id>
						<phase>package</phase>
						<goals>
							<goal>add-module-info</goal>
						</goals>
						<configuration>
							<overwriteExistingFiles>true</overwriteExistingFiles>
							<module>
								<moduleInfoFile>
									src/moditect/module-info.java
								</moduleInfoFile>
							</module>
						</configuration>
					</execution>
				</executions>
			</plugin>
```

**Comment by cowtowncoder** [comment]
Thank you for suggesting this -- I am not yet familiar with this plug-in, and have been hoping to figure out improved handling beyond Automatic Module Names.
I'll have to read bit more about this, but it sounds reasonable.

**Comment by GedMarc** [comment]
I'll prepare some pull requests for you in the morning, 
I'll do them across as many as I can with the same PR title :)

Thank you for considering this.

**Comment by cowtowncoder** [comment]
@GedMarc that'd be great. I was thinking that it'd be nice to get it in `2.9` branch of `jackson-core`, `jackson-annotations` and `jackson-databind` first, as I am planning 2.9.8 release.

**Comment by GedMarc** [comment]
I See 👍 
I have the same structure for jwebmp actually, but I haven't thought of abstracting it upward, 

Let's see what happens

**Comment by GedMarc** [comment]
Hmm Can't fork parent, i'll attach the pom with the PR

**Comment by GedMarc** [comment]
Sorry, is there a gitter channel?

**Comment by cowtowncoder** [comment]
Actually there is. May nor may not be faster channel but:

https://gitter.im/FasterXML/jackson-databind

**Comment by GedMarc** [comment]
Ok, here is the JPMS Build with all exports and everything in place, the versioning in the pom's is very erratic so i had to level them out, the pull request won't have these :
Simply open the pom in the root, 
Moving it all into moditect now.

[fasterxml-jpms.zip](https://github.com/FasterXML/jackson-core/files/2612065/fasterxml-jpms.zip)

**Comment by GedMarc** [comment]
Please review and let me know :) 

Thanx

**Comment by GedMarc** [comment]
The travis failures look to be caused from parent version ref's, updating each one will fix it

**Comment by GedMarc** [comment]
@cowtowncoder I've finished with the modules and have updated the documentation, Please can you review them all.

The travis build is simply because the JDK 7 is running after the JDK 8, I've run them all on https://jwebmp.com/teamcity successfully.  Guest user is enabled for this CI.

- Update the versions in the POMS to make sense for the 2.9 branch across the board
- Added new profile "JDK11", to assist in dev on the JPMS framework
- Added moditect to the lower versions, pulling it up doesn't work
- Updated the src and target, compile and release mechanism in the pom to allow quick switch to jdk 11
- Created all the module-info files

Thanks!!

**Comment by cowtowncoder** [comment]
@GedMarc Ok, I dropped the ball here. Where are we at again? :)

**Comment by GedMarc** [comment]
@cowtowncoder I'm pretty much finished and ready to hand over to you - 

I'm gonna kill these pull requests, and recreate them without so many pom changes -
Only thing is you have to build in JDK 8 (you can compile backwards to jdk 7 with source.target property?) so the module-info file can be created.

The rest are optional and nice-to-haves (develop in jdk 11 e.g.), will include them in on request, but main goal for me here is to keep the pom changes as small as possible for minimal impact.

**Comment by cowtowncoder** [comment]
Yes, JDK 8 for build is fine. Minimal impact sounds like a good starting point, to get 2.10 out with what I hope is functional module info bundle. And then we can iterate.

For 2.10, what I really want to get done (in addition to JPMS here) before just releasing it can be found from https://github.com/FasterXML/jackson-future-ideas/wiki/Jackson-Work-in-Progress and only one thing is a must-have for me -- abstraction for `ClassNameValidator`, to allow better handling of that one source of CVEs (polymorphic type handling with `Object` as base type, usually via "default typing").
How long that'll take is hard to say; I might get it done in next week, or might take a month altogether. But I am motivated to get 2.10 out of the way to focus fully on 3.0.

**Comment by cowtowncoder** [comment]
Oh, forgot to mention: I do plan on making at least one RC or PR for 2.10, so we can get some beta-testing for module aspects (that is, can release non-snapshot to be available via Maven Central, before official 2.10.0)

**Comment by GedMarc** [comment]
Can't find the one you mentioned me in earlier xD

**Comment by GedMarc** [comment]
@cowtowncoder 

For the JAXB Item, a few things 

JAXB - Module-info
```
// Manually composed on 14-Mar-2019 -- Moditect maven plugin failed to generate

module com.fasterxml.jackson.module.jaxb {
    requires java.logging;

    // This is for `BeanIntrospector`... should do away with (only need "Introspector.decapitalize")
    requires java.desktop;
    // Needed for JDK9+, but optionally only
    //Need for JDK8, JDK 9 and up ships with its own activation library, must not include custom activation for JDK 9 and up!
    //requires static javax.activation;
    requires java.xml.bind;
    //requires java.validation;

    requires com.fasterxml.jackson.core;
    requires com.fasterxml.jackson.databind;
    requires com.fasterxml.jackson.annotation;

    // expose main level, but leave out "ser", "deser" impl
    exports com.fasterxml.jackson.module.jaxb;

    provides com.fasterxml.jackson.databind.Module with
        com.fasterxml.jackson.module.jaxb.JaxbAnnotationModule;
}

```

Annotations module-info Needs a fix:
```

module com.fasterxml.jackson.annotation {
    exports  com.fasterxml.jackson.annotation;
    opens com.fasterxml.jackson.annotation;
}
```

Pom updates file for JAXB  (So that activations library does NOT get included with JDK 9)
```

    <!--  and actual JAXB annotations... -->  <dependency>
    <groupId>javax.xml.bind</groupId>
    <artifactId>jaxb-api</artifactId>
    <version>2.3.1</version>
    <scope>provided</scope>
    <exclusions>
      <exclusion>
        <artifactId>javax.activation-api</artifactId>
        <groupId>javax.activation</groupId>
      </exclusion>
    </exclusions>
  </dependency>
  </dependencies>

  <profiles>
    <profile>
      <id>jdk8</id>
      <activation>
        <jdk>1.8</jdk>
      </activation>
      <dependencies>
        <!-- 14-Mar-2019, tatu: Looks like this is needed for JDK11 and later
    - marc : No this is needed for jdk 8 and lower, JDK 11 ships with its own activation library and this will cause multi-package exposure
     -->
        <dependency>
          <groupId>javax.activation</groupId>
          <artifactId>javax.activation-api</artifactId>
          <version>1.2.0</version>
          <scope>provided</scope>
        </dependency>
        <dependency>
          <groupId>javax.xml.bind</groupId>
          <artifactId>jaxb-api</artifactId>
          <version>2.3.1</version>
          <scope>provided</scope>
        </dependency>
      </dependencies>
    </profile>
    <profile>
      <id>jdk11</id>
      <activation>
        <jdk>1.11</jdk>
      </activation>
      <properties>
        <jdk.version>1.11</jdk.version>
        <maven.compiler.source>1.11</maven.compiler.source>
        <maven.compiler.target>1.11</maven.compiler.target>
        <maven.compiler.release>11</maven.compiler.release>
      </properties>
      <dependencies>
        <dependency>
          <groupId>javax.xml.bind</groupId>
          <artifactId>jaxb-api</artifactId>
          <version>2.3.1</version>
          <scope>provided</scope>
          <exclusions>
            <exclusion>
              <artifactId>javax.activation-api</artifactId>
              <groupId>javax.activation</groupId>
            </exclusion>
          </exclusions>
        </dependency>
      </dependencies>


      <build>
        <plugins>
          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>build-helper-maven-plugin</artifactId>
            <executions>
              <execution>
                <id>add-source</id>
                <phase>generate-sources</phase>
                <goals>
                  <goal>add-source</goal>
                </goals>
                <configuration>
                  <sources>
                    <source>src/main/java</source>
                    <!--<source>src/jre10/java</source>-->
                    <source>src/moditect</source>
                  </sources>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>


    </profile>
  </profiles>
```

**Comment by GedMarc** [comment]
actually I think its the jaxb version, use 2.3.0 instead of 2.3.1,

I get a module cross reference with java.activation in 2.3.1,
