### ISSUE TITLE
Add a String Array write method in the Streaming API

### ISSUE THREAD

**Issue by feinstein** [FasterXML/jackson-core#504]
In version 2.9.7 there are methods for writing `int[]`, `long[]` and `double[]` arrays. I think it would be a nice addition to add a method for writing `String[]` arrays as well.

**Comment by cowtowncoder** [comment]
Forgot to ask: is this just for convenience or for some other reason? Not against addition, just want to double-check.

**Comment by feinstein** [comment]
Just a convenience. If I recall it correctly (as there has been many years already) I saw the docs and asked myself why `String[]` wasn't included.

**Comment by cowtowncoder** [comment]
Ok. Sounds reasonable. Challenge wrt APIs is regarding how much to include in cases like this; but often just a core set of `boolean`, `int`, `long`, `String` are included so I think adding of `String[]` seems reasonable.

**Comment by cowtowncoder** [comment]
Will be included in 2.11.0.
