### ISSUE TITLE
Use Ryu for Float/Double to String conversions

### ISSUE THREAD

**Issue by re-thc** [FasterXML/jackson-core#514]
Hi, see https://github.com/ulfjack/ryu and the paper / benchmarks / information. Might help a lot in JSON output from Float / Double.

Cheers!

**Comment by cowtowncoder** [comment]
@hc-codersatlas Thank you for the link! Looks potentially interesting. I don't have much time to look into this right now, but maybe someone else has, so it's good to have an issue filed.

**Comment by hc-codersatlas** [comment]
Sounds good. Hopefully it gets picked up. Jsoniter adopted this and is 1 of the reasons it's faster.

**Comment by vy** [comment]
For the records, [jsoniter](/plokhotnyuk/jsoniter-scala) fame @plokhotnyuk kindly shared the following links in [a Reddit comment](https://www.reddit.com/r/java/comments/darehu/jackson_release_210/f1ysf1e):

1. [Fast & medium paths for parsing of doubles](/plokhotnyuk/jsoniter-scala/blob/db689583dc35cd3dd457e9edb0b7fbcc10a5d508/jsoniter-scala-core/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/core/JsonReader.scala#L1243-L1303)
2. [Fast & medium paths for parsing of floats](/plokhotnyuk/jsoniter-scala/blob/db689583dc35cd3dd457e9edb0b7fbcc10a5d508/jsoniter-scala-core/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/core/JsonReader.scala#L1388-L1441)
3. [Fast parsing of BigDecimals and using them to parse BigIntegers](/plokhotnyuk/jsoniter-scala/blob/db689583dc35cd3dd457e9edb0b7fbcc10a5d508/jsoniter-scala-core/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/core/JsonReader.scala#L1611-L1724)
4. [Fast parsing of ISO-8601 representation of java.time.* instances](/plokhotnyuk/jsoniter-scala/blob/db689583dc35cd3dd457e9edb0b7fbcc10a5d508/jsoniter-scala-core/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/core/JsonReader.scala#L1747-L2240)
5. [Fast parsing of UUIDs](/plokhotnyuk/jsoniter-scala/blob/db689583dc35cd3dd457e9edb0b7fbcc10a5d508/jsoniter-scala-core/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/core/JsonReader.scala#L2308-L2369)
6. [Fast serialization of UUIDs](/plokhotnyuk/jsoniter-scala/blob/db689583dc35cd3dd457e9edb0b7fbcc10a5d508/jsoniter-scala-core/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/core/JsonWriter.scala#L660-L723)
7. [Fast serialization of ISO-8601 representation of java.time.* instances](/plokhotnyuk/jsoniter-scala/blob/db689583dc35cd3dd457e9edb0b7fbcc10a5d508/jsoniter-scala-core/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/core/JsonWriter.scala#L1018-L1506)
8. [Fast serialization of floats](/plokhotnyuk/jsoniter-scala/blob/db689583dc35cd3dd457e9edb0b7fbcc10a5d508/jsoniter-scala-core/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/core/JsonWriter.scala#L1641-L1834)
9. [Fast serialization of doubles](/plokhotnyuk/jsoniter-scala/blob/db689583dc35cd3dd457e9edb0b7fbcc10a5d508/jsoniter-scala-core/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/core/JsonWriter.scala#L1836-L2053)

**Comment by plokhotnyuk** [comment]
I switched jsoniter-scala from Ryu to Schubfach algorithm ~1 year ago. It gave a better throughput and minimized a tail latency.

[Here](https://github.com/c4f7fcce9cb06515/Schubfach/) is an original repo of the algorithm author.
[Here](https://github.com/plokhotnyuk/jsoniter-scala/blob/cec04d80f5d653fff5313a7228796e140790412f/jsoniter-scala-core/jvm/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/core/JsonWriter.scala#L1710-L2055) is its adoption in jsoniter-scala.

**Comment by cowtowncoder** [comment]
Will closed, replaced by above-mentioned PRs for fast floating-point reads and writes, nominally #577 for reads and #749 for writes.

**Comment by cowtowncoder** [comment]
@pjfanning Feel free to improve titles and descriptions of relevant issues/PRs with references to algorithm(s) used. I am trying to figure out best ways to quickly indicate how improvements are achieved. I changed #577 title a bit.
