### ISSUE TITLE
Use JDK Base64 to Replace Base64Variant

### ISSUE THREAD

**Issue by belugabehr** [FasterXML/jackson-core#515]
https://docs.oracle.com/javase/8/docs/api/java/util/Base64.html

**Comment by cowtowncoder** [comment]
Why?

**Comment by BELUGABEHR** [comment]
Getting it into 3.x is fine.

Really the biggest benefit would be smaller library size and also if the JVM at some point does native-calculations instead of pure Java, Jackson will get the benefit.

P.S. Great library.  Thanks so much.

**Comment by hc-codersatlas** [comment]
@cowtowncoder Intel (I think?) contributed SSE/AVX intrinsic to the Base64 code in OpenJDK. Might be 9 onwards that this happens but it's definitely a lot faster.

**Comment by cowtowncoder** [comment]
My problem with default Base64 implementation was, I think, that there is/was no way to feed things incrementally, so although it may be efficient for case where one decodes and reads all content into a String, problem is that doing this negates benefits of directly decoding from a fixed-size byte buffer into output container.

Secondary challenge is that existing configurability, wrt alphabet used, would need to be preserved.

I do agree that the goal of removing code that others provide make sense. So I'll leave this open and we could consider if at least some usage could be replaced.

**Comment by cowtowncoder** [comment]
I do not have current plans to do this, but would not be against it if:

1. This is for versions of Jackson that require Java 8 (`jackson-core` is unlikely to move there before 3.0, and existing Base64 functionality is mostly at that level)
2. Can support existing encoding modes (i.e. can replace existing codec) for most of ideally all usage
3. Basic performance benchmarking shows improved performance on newer JDKs

that is, while removing of unnecessary code is a good thing in general, I don't think amount of code for base64 handing is a problem now, nor has there been enough issues there to cause significant maintenance burden.
But if there are performance improvements via intrinsic use (and similar) I would not say no to such improvements, and in that case reduced code would be small but additional plus too.

**Comment by GedMarc** [comment]
Gotta be super careful with this one, maybe even go multi-release jar

Base64Decoder and Base64Encoder that is in JDK 8 does not exist in JDK 9 and up

**Comment by cowtowncoder** [comment]
That's good information. Since 2.x is not JAva 9 (and quite possibly never will), this would suggest use only for Jackson 3.0 or later. Will tag appropriately.

Also, I think that anyone who wants to optimize this can also just register custom (de)serializers and/or this could be separate module (or, maybe, add to Afterburner).

**Comment by plokhotnyuk** [comment]
Currently performance of Jackson is competitive when reading and writing Base64 to/from byte arrays on JDK 8 or GraalVM CE:
![image](https://user-images.githubusercontent.com/890289/82365198-a238b100-9a10-11ea-803b-ab3882bebb08.png)
![image](https://user-images.githubusercontent.com/890289/82365290-c1374300-9a10-11ea-9624-23b6380db807.png)

**Comment by cowtowncoder** [comment]
@plokhotnyuk thank you, this is very useful graph!

**Comment by cowtowncoder** [comment]
No plans to do this currently, will close. If anyone has further interest, I am open to change if a contributor provides

1. a PR for change that passes all unit tests and
2. performance test (jmh-based ideally) that shows that the change is beneficial for performance.
