### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by hborders** [FasterXML/jackson-core#528]
It is conventional for open-source projects to include a top-level `LICENSE` file with the text of their license embedded to guard against dead links. Please add a `LICENSE` file.

**Comment by cowtowncoder** [comment]
LICENSE can already be found from `src/main/resources/META-INF/LICENSE`, needed to be packaged within artifacts.
If there is a way to symlink this or something, I'm open to ideas. Otherwise I don't want to go adding duplicates for all Jackson projects.

**Comment by hborders** [comment]
I believe git supports symlinks on unix platforms, so you could add a symlink.

**Comment by cowtowncoder** [comment]
Ok, symlinked, appears to work.
