### ISSUE TITLE
ObjectMapper.readTree(URL source) ignores gzip compression

### ISSUE THREAD

**Issue by tim-tx** [FasterXML/jackson-core#530]
Tested with jackson-databind-2.9.8. I didn't realize that a server was returning gzipped json, and so ObjectMapper.readTree(URL source) barfed. Instead I have to retrieve the String with an HttpClient, which handles the compression seamlessly (there is a Content-Encoding: gzip header). Requesting that ObjectMapper handle compression seamlessly also, which I think is generally the default for tools consuming web resources.

**Comment by cowtowncoder** [comment]
ObjectMapper simply uses `java.net.URL` and does nothing else, so unless that supports compression  negotiation, I don't think I'll start implementing HTTP client functionality here.
But I could add a note saying that for any of more advanced features users are recommended to use more advanced http client than one provided by JDK, f.ex apache httpclient.
