### ISSUE TITLE
Basic BSON support (feature request)

### ISSUE THREAD

**Issue by LamotheMax** [FasterXML/jackson-core#544]
Hi, would it be possible to add some basic BSON support for the Tree Traversing Parser?

This project: https://github.com/mongojack/mongojack/blob/700f3fd5506e1df8d7786fb16aa0d350515a5b39/src/main/java/org/mongojack/internal/object/BsonObjectTraversingParser.java

https://github.com/mongojack/mongojack/blob/700f3fd5506e1df8d7786fb16aa0d350515a5b39/src/main/java/org/mongojack/internal/object/document/DocumentObjectTraversingParser.java

Is currently using a workaround for your API by copying your classes and adapting it for BSON Objects. Would it be possible to integrate some of this functionality directly into Jacksons API so that everyone could have access to this functionality without using another library like mongojack?

Thank you

**Comment by cowtowncoder** [comment]
Core jackson should not add support for various alternate formats, but BSON-backed streaming api implementation makes sense ("dataformat" module) -- this is what is used to support dozen other formats. And one exists for BSON:

https://github.com/michel-kraemer/bson4jackson

so I would suggest you have a look at that module if you have not already done so? It should be stable and fully-featured, as it was developed quite a while ago and Michel is a good maintainer.
