### ISSUE TITLE
Jackson Deserialization not working for direct use of Concrete class 

### ISSUE THREAD

**Issue by BhavishyaJain** [FasterXML/jackson-core#545]
Consider we have following classes

```
@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        include = JsonTypeInfo.As.EXTERNAL_PROPERTY,
        property = "type")
@JsonSubTypes({
        @JsonSubTypes.Type(value = Cat.class, name = "CAT")
})
abstract class Animal {

  abstract Type getType();

  enum Type {
    CAT("CAT");

    public String type;

    Type(String type) {
      this.type = type;
    }
  }
}

class Cat extends Animal {

  private String name;

  @Override
  Type getType() {
    return Type.CAT;
  }
} 
```

And we try to directly deserialize a json  `{"name": "Meow"}`  by writing `objectMapper.readValue(json, Cat.class)` 

Why should this go to super class and ask for the  value of `type` property . If we want to directly deserialize into subclass, polymorphism should not be checked. 

The error is `Missing type id when trying to resolve subtype of [simple type, class Cat]: missing type id property 'type'`

**Comment by cowtowncoder** [comment]
Your JSON does not have type id property `type` and that's the error. Type id is not some optional thing you can simply omit -- if you say type id is used, it needs to be there.

**Comment by cowtowncoder** [comment]
Also belong under `jackson-databind`, if there is work. But closing for now, as type id handling works as designed (if not the way reporter hopes it did).
