### ISSUE TITLE
Remove `JsonGenerator.setPrettyPrinter()` from 3.0

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-core#551]
Due to change in 3.0, immutability, it should be possible to remove mutability of `PrettyPrinter` setting (as well as in general promote it to textual formats?).

**Comment by jpsla94** [comment]
Since this feature was removed for Jackson 3. Is there an alternative? Or it is no longer required?

**Comment by pjfanning** [comment]
@jpsla94 there are probably nicer ways to do this but have a look at https://github.com/FasterXML/jackson-core/blob/ab0f53b5f7590c21d6ee55fe23ffb47da0f0a8b4/src/test/java/tools/jackson/core/unittest/write/PrettyPrinterTest.java#L368

The createGenerator method now takes ObjectWriteContext as input and the link above shows one way to create context instance that returns a PrettyPrinter instance that you can control.

**Comment by jpsla94** [comment]
In Jackson 2, I could setup a pretty printer with the JsonGenerator.

`public static JsonGenerator toSingleLineJsonGenerator(JsonGenerator jsonGenerator){
jsonGenerator.setPrettyPrinter(singleLinePrettyPrinter);
return jsonGenerator;
}`

 Can I achieve this in Jackson 3 during the creation of the JsonGenerator?

**Comment by pjfanning** [comment]
> In Jackson 2, I could setup a pretty printer with the JsonGenerator.
> 
> `public static JsonGenerator toSingleLineJsonGenerator(JsonGenerator jsonGenerator){ jsonGenerator.setPrettyPrinter(singleLinePrettyPrinter); return jsonGenerator; }`
> 
> Can I achieve this in Jackson 3 during the creation of the JsonGenerator?

I'm not near a computer right now. The API has changed. Gen AI suggested this.

```
import tools.jackson.databind.ObjectMapper;
import tools.jackson.databind.ObjectWriter;
import tools.jackson.core.PrettyPrinter;
import tools.jackson.core.util.DefaultPrettyPrinter;

// ...

ObjectMapper mapper = new ObjectMapper();

// Option A: Use default pretty printer
ObjectWriter writer = mapper.writerWithDefaultPrettyPrinter();

// Option B: Use a custom PrettyPrinter instance
PrettyPrinter customPrinter = new DefaultPrettyPrinter();  // or your subclass
ObjectWriter writerWithCustom = mapper.writer().withPrettyPrinter(customPrinter);

// Then create the generator from the writer (recommended)
JsonGenerator gen = writerWithCustom.createGenerator(outputStream);  // or StringWriter, etc.

// Write your content
// gen.writeStartObject(); ... etc.
gen.close();
```

**Comment by jpsla94** [comment]
Thanks, @pjfanning. This has been very helpful.

**Comment by cowtowncoder** [comment]
What @pjfanning said: go via `ObjectWriter`. While it is possible to implement `ObjectWriteContext` that's more work (without benefits).
