### ISSUE TITLE
'com.fasterxml.jackson.core:jackson-core:2.10.0.pr1' conflicts with firebase:firebase-perf l

### ISSUE THREAD

**Issue by Yonkokilasi** [FasterXML/jackson-core#555]
Version affected : `'com.fasterxml.jackson.core:jackson-core:2.10.0.pr1'`
I have noticed that when i add the library above to my android project, it conflicts with the Firebase Perfomance library (com.google.firebase:firebase-perf:19.0.0). Removal of jackson library resolves the issue. 
The error I get is : 
```
app/build/intermediates/transforms/FirebasePerformancePlugin/debug/101/module-info.class 
Illegal class file: Class module-info is missing a super type. Class file version 53. 
```
I have informed Firebase support of the issue as well.

**Comment by cowtowncoder** [comment]
That sounds like possible issue with some other parts of tooling in Android build systems? Every jar would fundamentally have their own `module-info.class`. But maybe build tooling predates Java 9 and is not aware of this possibility (it need not use Java 9, but just be aware of this metadata class).
I recall similar challenges with some other things, mostly under `META-INF`.

**Comment by kb-1000** [comment]
As far as I know, you can hide module-info.class in a subdirectory of META-INF though, using a feature called multi-release JARs.

**Comment by GedMarc** [comment]
@kb-1000 Yes, it is possible, and easy to implement.

For my curiosity and surprises sake though, which JDK are you on? is this 1.5?

**Comment by kb-1000** [comment]
I'm pretty sure that newer versions of com.android.tools.build:gradle have already fixed this by ignoring module-info.class, though
