### ISSUE TITLE
JsonParser: add "getTextAsBytes()" that will return text as UTF-8 encoded bytes

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-core#56]
(moved from http://jira.codehaus.org/browse/JACKSON-447)

(request by David Yu, via mailing list)

---

Feature request:
byte[] raw = JsonParser.getRawString();

Kinda like the raw getBinaryValue() except that the value was never b64 encoded (e.g a utf8 string)

---

(Tatu's comments)

I think a good name would be "getTextAsBytes()", to follow existing naming convention. I think it is ok to only expose UTF-8 encoded Strings, given that JSON itself only supports Unicode encodings.

One open question is whether there should be complementary method(s) that would take a byte array (or buffer) to append/write string into. But maybe it's best to start simple and improve things over time.

...

Sounds like David was hoping to get contents before replacing escaped codes (probably to pass through JSON output with minimal changes). This is unfortunately very difficult to do in general case, so I will not consider this for inclusion with 1.7.0. Perhaps a solution can be found in future; leaving this issue open still.

**Comment by terziele** [comment]
Hey, can you explain a bit more?

I don't know Jackson as much as you do, and I don't get this problem completely. If we need an array of UTF-8 bytes we can just call `string.getBytes("UTF-8");`, isn't?

**Comment by cowtowncoder** [comment]
@terziele Of course, but that is very inefficient compared to simply asking for bytes that have been extracted, without having to decode into UTF-8 and then re-encode back as UTF-8. So the original request was to allow access to "raw" bytes, if available, for purpose of copying textual content from input document, as already encoded. Target could be another document, file, cache, or whatever.

**Comment by terziele** [comment]
@cowtowncoder Oh, okay, now I get it. Thanks for your explanation!

**Comment by marcbowes** [comment]
:+1:

**Comment by rockwotj** [comment]
Has there been any progress on this?

**Comment by cowtowncoder** [comment]
Not that I am aware of. I have no plans to work on this.

**Comment by x700700** [comment]
So what is the current solution to deserialize utf8 string property on http request?
the following (inside a Deserializer extend) -

byte[] utf8 = jsonparser.getBinaryValue();

returns the wrong bytes, and not those sent from the frontend.
My string is annotated pointing to this Deserializer - 

    @JsonDeserialize(using = DeserializerUtf8.class)
    private String name;

**Comment by cowtowncoder** [comment]
@x700700 No. `getBinaryValue()` expects Base64 encoding, and if so, decoded base64-encoded String into binary value it represents. Binary value does not refer to original incoming encoded json document or fragment.

Jackson does not expose underlying bytes because it does not retain them: there's rarely any need and doing that would add significant performance and memory overhead, as it would prevent one-pass character AND token decoding.

You are given text as decoded. If you want you can re-encode them as UTF-8 using JDK methods, but this is not commonly needed since processing within Java uses Strings and `character`, and byte serialization is only used for storage and transfer purposes.

**Comment by x700700** [comment]
And indeed I'm dealing with transfer:
frontend sends a request includng utf8 string in the body.

Doing nothing special, it's received into Java string not properly.
And the only solution I found to get it properly is the following ugly one:

BTW - annotating with: consumes = "application/json; charset=UTF-8"
also doesn't work.


public class DeserializerUtf8 extends StdDeserializer<String> {
    ... ctors

    @Override
    public String deserialize(
            JsonParser jsonparser, DeserializationContext context)
            throws IOException {

        String str = "";
        char[] chars = jsonparser.getTextCharacters();
        int len = jsonparser.getTextLength();
        if (len > 0) {
            byte[] bytes = new byte[len];
            for (int i = 0; i < len; i++) {
                bytes[i] = (byte) chars[i];
            }
            try {
                str = new String(bytes, "UTF8");
            } catch (UnsupportedEncodingException e) {
                str = "???";
                throw new RuntimeException(e);
            }
        }
        return str;
    }
}


I know, it's terrible, I would love to do it more elegantly if there's a way....

**Comment by cowtowncoder** [comment]
@x700700 Don't do that. If front-end is sending broken data, make them fix it. It is not up to you "fix" broken things -- it's theirs to encode it correctly. Above is not only ugly, it is wrong. Don't do it.

Also: this issue is not related to your encoding problems; that is, implementing this feature would not fix (or even allow fixing) your problem.

You DO however need to make sure you understand how character encodings work. Without that it is not possible to know exactly how things go work; what is or is not being done correctly.
Jackson will assume content is UTF-8 encoded -- as per JSON specification, which only allows UTF-8, UTF-16 and UTF-32. If not, caller MUST somehow indicated it is not, and code getting request MUST then handle decoding, providing jackson `Reader` for decoded characters, instead of `InputStream` of encoded.
Or, better yet, caller should actually use UTF-8 encoding. If your textual content is broken it is very likely they are not doing that. If they are, then it is your web framework that is breaking encoding.

**Comment by x700700** [comment]
I totally see your point, and trying to get rid of this code,
However when I remove it, 
then non-English strings are set improperly inside the java object String.

Checking with Wireshark, the POST is indeed unicoded with UTF8 as expected. So it's received as should inside Spring Boot.
However Spring loads it improperly into the utf16 Java String - "×××"

(With the code enabled the string is loaded properly)
What am I doing wrong?

**Comment by cowtowncoder** [comment]
@x700700 If they are correctly encoded, then Spring Boot may be somehow assuming incorrect encoding; often Latin-1 (ISO-8859-1)... but UTF-16 is unusual.

One thing you can usually do with JAX-RS based (and similar) frameworks is to indicate you want `InputStream` (or sometimes `byte[]`) payload, without processing. If so you can call `ObjectMapper.readValue()` to let decoding be done as expected. That would at least help pin-point the problem.

**Comment by cowtowncoder** [comment]
No plans to work on this, closing for now: if someone wants to work on it, may refile.
