### ISSUE TITLE
JVM (java 13) crashed when `ByteQuadsCanonicalizer.calcHash()`

### ISSUE THREAD

**Issue by bruceauyeung** [FasterXML/jackson-core#564]
json data size: over 4MB
doesn't happen every time, even when dealing with exactly same json data.
https://gist.github.com/bruceauyeung/8e1674844e5da9ed3f1e2ca65fc082ff#file-hs_err_pid32196-log

version: jackson-core-2.9.9

**Comment by cowtowncoder** [comment]
That seems very odd. I have not received similar error reports before.

Unfortunately I have no idea what could cause that, nor how to help, other than suggesting that use of a later JVM/JDK patch could solve the problem. To me this seems like possible JVM bug.

**Comment by bruceauyeung** [comment]
i recompiled my program with latest java 13 and tested again, and unfortunately there is still a failure ( i am running a batch script which invokes my java program multiple times).

https://pastebin.com/raw/uxfAWLgi

**Comment by cowtowncoder** [comment]
At this point I can not reproduce the issue so will need to close; may be opened with a reproduction.
