### ISSUE TITLE
Add support for non-blocking ("async") JSON parsing

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-core#57]
(migrated from http://jira.codehaus.org/browse/JACKSON-39 -- note, high vote count)

---

(suggested by Dimitri M on user list)

There are use cases where it'd be good to be able to feed input to parser, instead of trying to provide an input stream for parser to read from. This would cover use cases where input comes in chunks; for example, part of logical document in one chunk, then after a delay (perhaps in a separate request) another one and so forth. In these cases it may be difficult to implement InputStream (Reader etc) abstraction; instead, it would be better if application could feed (push) data to parser.
But if so, parser must be able to indicate cases where no data is YET available (but may become available).

This is similar to how Aalto Xml processor (http://www.cowtowncoder.com/hatchery/aalto/index.html) operatesd in its async mode. However, since Json is much simple format than xml, implementation might be simpler.

Based on my experiences with Aalto, implementation is a non-trivial thing however. One problem is that even UTF-8 decoding needs to be somewhat aware of chunk boundaries, so in the end a separate parser may be required: this because current parser uses blocking to handle these split cases. A smaller problem is that of indicating "not-yet-available" case – this can probably be handled by introducing a new member in JsonToken enumeration.

**Comment by testn** [comment]
Is there a way to get this supported? I saw something implemented in jackson-smile.

**Comment by cowtowncoder** [comment]
@testn Yes, by someone with lots of time to spend on implementing and testing it. Smile unfortunately only has skeleton (or, scaffolding), not full implementation. I know how it can be done (see `aalto-xml` for earlier implementation I did for xml), but at this point do not have time or personal need, nor a customer willing to pay for development costs. But anyone else is free to have a stab with it, it is definitely doable.

**Comment by testn** [comment]
Can you describe a bit how it should be done? Maybe I will take a stab at it.

**Comment by cowtowncoder** [comment]
The way I did it with Aalto:

https://github.com/FasterXML/aalto-xml

was to basically do two things:

1. Provide non-blocking content feeder interface, to use instead of blocking `InputStream` or `Reader`
2. Implement state-machine driven parser/decoder to keep byte-accurate state of things; and return `NOT_AVAILABLE` token if there isn't enough content to FULLY decode the event (unlike with blocking, there is no option of lazily decoding things)

Of these, (1) is trivially simple, although I had to rewrite it a bit to support alternatives like feeding `byte[]` vs feeding `ByteBuffer`. Still, it just needs to be accessible by caller (code that instantiates `JsonParser`), and allow doing three things: checking whether decoder has more data to work on, and if not, either feeding more data, or indicating that no more data is available (end of input).

Second part is the complicated part: there needs to be state associated with all possible different state throughout decoding, at byte accurate level. Not just within tokens, but since this has to assume multi-byte UTF-8 decoding as well, within UTF-8 characters. An alternative could be to separate UTF-8 decoding, and this might simplify things a bit, but with some performance overhead. If so, parser would work with `char`s, which is slightly easier (but not a whole lot, due to surrogate characters).

Regardless, amount of state to track with JSON is less than with XML, so that's a slight simplification.
In addition whereas in XML you can return partial text segments, in JSON String values are atomic (at least via Jackson tokens).
For state itself, it is not enough to just have a state (or, some sort of state/sub-state, main state being current token, sub-state within that context), but also there's need to track some of accumulated content, such as partially decoded UTF-8 character (if any). And possibly decoded value; although here existing components like `TextBuffer` may work with no modifications.

So... yeah, it is bit involved. I'm sure there are other approaches too, but in general state machine approach should work well. Others would probably use a state machine library or compiler; it could simplify the task. I am not sure whether it would, but since you'd be starting from the scratch it might make sense.

**Comment by wtracy** [comment]
Hello,

I'm interested in asynchronous I/O too, but from a different angle. I still want the traditional synchronous Jackson API, but internally I want Jackson to do something conceptually like this:

```java
Token getNextToken() {
  startReadingDataIntoBuffer();
  blockUntilWeCanReadAToken();
  //data continues streaming into buffer in the background
  //until buffer is full or EOF is reached
  return parseAToken();
}
```

I guess my big question is: Could this pattern make Jackson faster by better saturating whatever I/O connection I'm using? I'm trying to stream some fairly large JSON files, and my gut feeling is that I'm not saturating my data connection because of the time the CPU spends on parsing between read() calls.

Is there anyone around more knowledgeable than me who can comment on both whether my hunch is correct, and, if so, whether any possible performance gains are likely to be worth the engineering effort? If anyone has any ideas for resources I could look at (I already spent half an hour with Google without luck) or benchmarks I could write to answer my own question, I'm all ears.

William Tracy

**Comment by rfqu** [comment]
@wtracy as far I understand, you want to continue to load data while parsing. That is, to load data and parse them in parallel. If so, the simplest way is to start a separate thread for data loading, and to use a circular buffer to connect loading and parsing threads. Probably, loading thread should do also token recognition and fill the buffer with tokens, not characters.

**Comment by cowtowncoder** [comment]
@wtracy isn't that just like existing regular blocking parser? This is how `InputStream` works: they block until some content is available, and always return at least one byte. `JsonParser`, in turn, reads enough content to decode one token (although possibly buffer more) and decode that.
So I am not sure what actual change you would be suggesting.

Now, I am guessing like @rfqu that you may be wishing to continue loading in the background. If so, I think that multi-threaded background reading should reside outside Jackson core, and abstracted out behind `InputStream`. Synchronization could be handled by usual blocking behavior. I would not count on this actually helping a lot, unless you have significant parallelism (thousands of threads); my experience (and also what I have read over time) has been that blocking I/O is pretty efficient at what it does for low to medium concurrency, at least to low hundreds of threads. Non-blocking or pipelined I/O starts to make sense when there are thousands of connections with long(er) lifetime but with bursty/low-average throughput at any given point.

**Comment by wtracy** [comment]
@cowtowncoder you've convinced me that I probably based this whole idea on
an incorrect concept of how BufferedInputStream (or whatever Jackson uses
internally) works. I was concerned that it was loading a burst of data on
the first read() call, then letting the hardware sit idle until another
read() call requested more data than was left in the buffer.

I think I should at least spend some more time understanding the internals
of InputStream and friends before I try to pursue this any farther. Thanks
for taking the time to talk to me, everybody.

William

**Comment by cowtowncoder** [comment]
Quick note: I am working on non-blocking parsing for Smile format, and hope to follow it up here for JSON, to be included in 2.9.0.

**Comment by aduchate** [comment]
Actson: https://github.com/michel-kraemer/actson is an async implementation of a JSON parser

**Comment by cowtowncoder** [comment]
Thank you for sharing this. API looks similar, probably due to common roots via Aalto xml parser.
Makes sense to me.

**Comment by cowtowncoder** [comment]
Fwtw, Smile codec has fully functioning non-blocking implementation; `JsonParser` now exposes necessary methods (for byte array -backed input).

**Comment by sdeleuze** [comment]
Hi Tatu,

Nice to know, I will leverage this in Spring WebFlux support for Smile
expected for Spring Framework 5.0 RC3 [1].

Do you have more visibility about similar support for JSON which is
critical for our approaching GA? Do you plan to make it part of Jackson 2.9
RC for example?

Best regards,
Sébastien Deleuze

[1] https://jira.spring.io/browse/SPR-15424

**Comment by cowtowncoder** [comment]
@sdeleuze I am working on JSON async right now, and one thing I have to decide is whether to release one more pr (2.9.0.pr4), or take my chances with 2.9.0 final. If I get to push pr4 within a week or so (hopefully next weekend; probably no sooner), with json non-blocking, would that allow you to test it? Ideally I would have last pr as close as possible to eventual release, with only smaller fixes and new features. But there is some to releasing too.

**Comment by sdeleuze** [comment]
Awesome thanks! Yes sure, that would enable us to test it asap and
hopefully to leverage it in our RC3.

**Comment by cowtowncoder** [comment]
And with latest commit, non-blocking parser now works well enough to pass `jackson-benchmarks` test, which suggests speed is actually within 5% of blocking-parser's speed!

I still need to work a bit on non-standard features (comments, various quoting alternatives), as well as just porting more tests. But things are looking good.

**Comment by cowtowncoder** [comment]
@sdeleuze Finally got pr4 out (should be at Maven Central now)

**Comment by sdeleuze** [comment]
Awesome thanks, we are going to try to use the JSON non-blocking feature
next week, we will keep you informed.

**Comment by cowtowncoder** [comment]
@sdeleuze Sounds good -- I tried to add reasonable testing, but that'd only help verify it works the way I want to, not that it is good or fit :)

**Comment by sdeleuze** [comment]
@cowtowncoder We are going to try to leverage this during the week and send you feedbacks cc @poutsma.

**Comment by mmimica** [comment]
Using [actson](https://github.com/michel-kraemer/actson) to provide async parsing for jackson: https://github.com/mmimica/async-jackson

**Comment by PawanDalal** [comment]
Where can I see sample code for this?
