### ISSUE TITLE
InputStream should be allowed to return 0 bytes read

### ISSUE THREAD

**Issue by jbalint** [FasterXML/jackson-core#574]
`_loadMore()` should handle read() returning 0 bytes here https://github.com/FasterXML/jackson-core/blob/master/src/main/java/com/fasterxml/jackson/core/json/UTF8StreamJsonParser.java#L193

read() method doesn't guarantee a non-zero number of bytes are read https://docs.oracle.com/javase/7/docs/api/java/io/InputStream.html#read(byte[],%20int,%20int)

**Comment by cowtowncoder** [comment]
I know it is allowed, but I can not think of any legal reason to do that -- and without further input, what would action then be?

Perhaps you have specific use case in mind?

**Comment by jbalint** [comment]
you can call it repeatedly until either:

1. read() returns -1, which means the connection was closed, or another error condition was encountered, or
1. the requested number of bytes have been read

as there is no specific protocol which would determine the size of the read, (1) is the only option here.

**Comment by cowtowncoder** [comment]
No, calling it repeatedly makes very little sense: potentially leading to infinite looping.

At this point I see no compelling reason to change the behavior: if an actual use case -- where accepting 0 read with defined behavior can be safely handled in better -- is presented I can reconsider but for now I will close this issue.

**Comment by plokhotnyuk** [comment]
@jbalint please, do not waste our time - nobody will burn CPUs on returned zeroes!

**Comment by jbalint** [comment]
I checked the docs for `InputStream` and see this:
> If len is zero, then no bytes are read and 0 is returned; otherwise, there is an attempt to read at least one byte. If no byte is available because the stream is at end of file, the value -1 is returned; otherwise, at least one byte is read and stored into b.

However, this is not the behavior exhibited by a channel input stream returned from Undertow. I will follow up with them. As a workaround, retrying until some bytes are read is working fine.

**Comment by plokhotnyuk** [comment]
@jbalint before calling of `read(byte b[], int off, int len)` just make sure that the `b` buffer is not full and do not provide a zero value for `len` - it will be the best workaround

**Comment by cowtowncoder** [comment]
@jbalint Thank you for following up with Undertow if it returns 0 even if buffer would have space. That does not sound like correct behavior, given practical difficults in taking other actions.
