### ISSUE TITLE
Improve performance of floating-point number parsing

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-core#577]
Jsoniter project (https://github.com/plokhotnyuk/jsoniter-scala) has many impressive performance optimizations; linked f.ex from here:

https://www.reddit.com/r/java/comments/darehu/jackson_release_210/f1ysf1e/

Of ones included, number-parsing would be relevant for this repo.

EDIT: also see (from the comment below)

"Unrelated to jsoniter but this recent port of Lemire's Double parser:

https://github.com/wrandelshofer/FastDoubleParser

and the original paper https://arxiv.org/abs/2101.11408 also relevant"

**Comment by cowtowncoder** [comment]
And specifically, for `BigDecimal` case:

https://github.com/plokhotnyuk/jsoniter-scala/blob/b51f90b87923305b6fa177a4da909ff43da3c7b7/jsoniter-scala-core/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/core/JsonReader.scala#L1477-L1591

**Comment by anneloreegger** [comment]
I'd like to work on this issue, is it still available?

**Comment by cowtowncoder** [comment]
@anneloreegger Yes, this is available! I'll assign it to you (no obligation to work, just a marker so others know you are considering it).

**Comment by anneloreegger** [comment]
Just to be sure I understand the issue correctly. Shall I especially improve the parsingMethods inside the NumberInput-class? (especially parseBigDecimal)
And should this be done on 2.12 or master branch?
Thanks for the answers :)

**Comment by cowtowncoder** [comment]
@anneloreegger Yes, I think `NumberInput` has stubs that would allow for this. On 2.12 vs master -- ideally 2.12, if this seems doable on short term with well contained changes. But `master` if there were need to change API or internal interfaces.
I have not really investigated jsoniter's approach enough to know how involved this gets unfortunately.

**Comment by cowtowncoder** [comment]
NOTE: `BigDecimal` use case covered by #677 (for 2.13), will edit title

**Comment by LifeIsStrange** [comment]
Unrelated to jsoniter but this recent port of Lemire's Double parser is 5.5X faster than the default double parser:
(if the microbenchmark generalize)
https://github.com/wrandelshofer/FastDoubleParser

**Comment by cowtowncoder** [comment]
@LifeIsStrange thank you for sharing this! I hope someone might have time to maybe investigate possibility of PR for improvements here.

**Comment by abc12345678912345** [comment]
I'd like to work on this issue, could you assign it to me?

**Comment by cowtowncoder** [comment]
I think @anneloreegger is not working on this, so will change assignee to @abc12345678912345.

If anyone else wants to try to do it instead, please simple add a note here as courtesy; assignments are about intentions but with OSS things come and go.

**Comment by pjfanning** [comment]
@cowtowncoder if [FastDoubleParser](https://github.com/wrandelshofer/FastDoubleParser) was to be used in jacakson-core - would you accept it as dependency or would the code need to be inlined in jackson-core?

jackson-core is still java6 bound - is this going to change? FastDoubleParser 0.2.0 is Java 8 and 0.3.0 is Java 11 bound.

**Comment by pjfanning** [comment]
com.fasterxml.jackson.core.io.ContentReferenece uses java.lang.Objects and that class only arrived in Java 7.

My IDE won't compile jackson-core because of this. Only command line maven build seems to work.

**Comment by cowtowncoder** [comment]
Ok, that is a good example of accidental inclusion of Java 7 things that default tooling (compilation is already with JDK 8) cannot detect, and that we haven't added anything to guard.
Earlier when JDK 6 was available on CI platforms this was easier to guard against.

So I am not against proposing to raise Jackson 2.14 (for example) baseline officially to Java 8.

**Comment by pjfanning** [comment]
one extra question - FastDoubleParser has a copyright and is generally MIT licensed - how would you handle this if the classes were copied to jackson-core - a special notice file? - could I keep the license headers in the source files too?

example: https://github.com/wrandelshofer/FastDoubleParser/blob/java8/src/main/java/ch/randelshofer/fastdoubleparser/FastDoubleParser.java#L3

**Comment by cowtowncoder** [comment]
I think a combination might make sense: definitely keep the license headers in sources  but probably some addition needed. I could try asking others for advice too.
MIT license itself should be fine, but I would want us to do proper acknowledgments, whatever those are.

**Comment by wrandelshofer** [comment]
> Friendly ping of @wrandelshofer for his opinion on copyright aknowledgment.

Well, I usually put a reference in the JavaDoc of derived code. Maybe something like this (that's just a suggestion, you can do it differently of course).

```
 * References:
 * <dl>
 *     <dt>This class has been derived from "FastDoubleParser".</dt>
 *     <dd>Copyright (c) Werner Randelshofer. MIT License.
 *         <a href="https://github.com/wrandelshofer/FastDoubleParser">github.com</a>.</dd>
 * </dl>
```

The MIT License also requests that the License file should be included. 
Hm. Do you already have a directory in this project where you put all third-party license files? 

Alternatively, I hereby license you the FastDoubleParser code under the Apache 2.0 License - which coincidentally is the license that this project uses ;-).

```
 * References:
 * <dl>
 *     <dt>This class has been derived from "FastDoubleParser".</dt>
 *     <dd>Copyright (c) Werner Randelshofer. Apache 2.0 License.
 *         <a href="https://github.com/wrandelshofer/FastDoubleParser">github.com</a>.</dd>
 * </dl>
``` 

How's that? :-)

**Comment by cowtowncoder** [comment]
Thank you @wrandelshofer! That's perfect! We do not have too many inclusion and hence not yet separate licenses-for-3rd-party directory. But this header looks perfect.

**Comment by pjfanning** [comment]
@cowtowncoder I have some benchmarks on https://github.com/pjfanning/double-reader-writer.

Perf testing is not an area of expertise for me but results look like the proposed changes are useful.

One weird issue is Ryu algorithm seems bad with writing whole numbers - is there any way the jackson-core code that writes numbers could use Long.toString for whole numbers and the Ryu code for non-intergers?

**Comment by cowtowncoder** [comment]
@pjfanning Looks good. Just one question: are references to "ints" in this context still `double` values (like, `1.0` and `25.0`), or do they relate to actual Java integer numbers?

**Comment by pjfanning** [comment]
@cowtowncoder this issue is more about parsing and the FastDoubleParser can handle numbers with and without decimal points. When looking at serializing numbers, we can look whether the suggested alternatives like Schubfach output different values from Double.toString. Ultimately, I think any changes will be hidden behind config settings that are documented to warn users about potential diffs.

**Comment by re-thc** [comment]
Note that a similar but likely faster version has already been integrated into the JDK. See this [PR](https://github.com/openjdk/jdk/pull/3402) for reference. A summary exists in this [reddit post](https://www.reddit.com/r/java/comments/v5ptpx/improvements_to_floattostringfloat_and/).

**Comment by cowtowncoder** [comment]
Thank you for sharing @plokhotnyuk. Good to know JDK is improving as well.

**Comment by cowtowncoder** [comment]
Ok. Thanks to @pjfanning we now have improved floating-point parsing functionality; merges are scattered (alas) through a few merges, purpose of which was to make it easier to merge to 3.0.

PRs include #747 and #766 for anyone interested in details.
