### ISSUE TITLE
FilteringGeneratorDelegate does not override writeStartArray(Object forValue, int size) or writeStartObject(Object forValue, int size)

### ISSUE THREAD

**Issue by arakelian** [FasterXML/jackson-core#583]
Since 2.10, this issue has essentially resurfaced (causes NPE):
https://github.com/FasterXML/jackson-core/issues/359

Caused by addition of these methods in JsonGeneratorDelegate which are not overridden:
- writeStartArray(Object forValue, int size)
- writeStartObject(Object forValue, int size)

**Comment by cowtowncoder** [comment]
Dup of #582 I think (fix to be included in 2.10.2)
