### ISSUE TITLE
writeRawValue() corrupts state in FilteringGeneratorDelegate

### ISSUE THREAD

**Issue by vy** [FasterXML/jackson-core#588]
Below snippet causes a `JsonGenerationException` with *Can not write a field name, expecting a value* message. When `FilteringGeneratorDelegate` is removed, code works as expected against `JsonGenerator`. (Using jackson-core version 2.9.10.)

```java
private static class NullExcludingTokenFilter extends TokenFilter {

    private static final NullExcludingTokenFilter INSTANCE = new NullExcludingTokenFilter();

    @Override
    public boolean includeNull() {
        return false;
    }

}

@Test
public void repro() throws IOException {
    try (ByteArrayOutputStream outputStream = new ByteArrayOutputStream(1_024);
         JsonGenerator jsonGeneratorDelegate = new ObjectMapper().getFactory().createGenerator(outputStream);
         FilteringGeneratorDelegate jsonGenerator = new FilteringGeneratorDelegate(
                 jsonGeneratorDelegate,
                 NullExcludingTokenFilter.INSTANCE,
                 true,
                 true)) {
        jsonGenerator.writeStartObject();
        jsonGenerator.writeNumberField("f1", 1);
        jsonGenerator.writeFieldName("f2");
        jsonGenerator.writeRawValue(new char[]{'1', '2', '.', '3', '-'}, 0, 4);
        jsonGenerator.writeNumberField("f3", 3); // BOOM!
        jsonGenerator.writeEndObject();
        jsonGenerator.flush();
        String json = outputStream.toString(StandardCharsets.UTF_8.name());
        System.out.println(json);
    }
}
```

**Comment by cowtowncoder** [comment]
Ah. You are probably hitting either #580 or #582, both fixed for 2.10.2, not yet released.

If it is easy enough for you to check 2.10.2-SNAPSHOT (either built locally, or from Sonatype OSS repo), it'd be good to verify just to be sure.

**Comment by vy** [comment]
Sorry, it still fails on the same line with the same message.

**Comment by cowtowncoder** [comment]
I can not reproduce: this passes for me as expected (wrt fixes mentioned above), with build from 2.10 branch. Maybe snapshot builds have not been updated? I'll do explicit maven deploy just in case, but I do think one of (or both) those issues was what you saw.
Note that issue would occur with 2.10.1 as the fix was after that was released.

**Comment by vy** [comment]
Sorry for the noise, you are right. I've cloned the repo to local, ran the above snippet against master, and it worked. Probably I used an older SNAPSHOT version in my previous check. I've created PR #589, of which I actually should have done in the first place, adding the above check to the tests. Closing this issue. Thanks for your prompt help.

**Comment by cowtowncoder** [comment]
No problem -- better safe than sorry! 2.10.2 now released.

**Comment by vy** [comment]
Thanks so much @cowtowncoder! :pray: I have never witnessed such a prompt and responsible support for such a popular F/OSS project. Keep up the great job!
