### ISSUE TITLE
DataFormatMatcher#getMatchedFormatName throws NPE when no match exists

### ISSUE THREAD

**Issue by sleberknight** [FasterXML/jackson-core#592]
When there is not a match in DataFormatMatcher, the _match field is null, which causes DataFormatMatcher#getMatchedFormatName to throw a NPE.

Submitted pull request #591 for your consideration, which just updates the code to match what the javadoc says, and added tests.

**Comment by cowtowncoder** [comment]
Thank you for reporting this & contributing possible fix! I hope to look into this soon; sounds like legit improvement.
