### ISSUE TITLE
include license information in pom.xml file

### ISSUE THREAD

**Issue by radai-rosenblatt** [FasterXML/jackson-core#594]
Hi

Jackson is distributed under the APL-2.0 (at least thats what is says so here - https://github.com/FasterXML/jackson-core/blob/master/LICENSE)
Yet no licensing information is included in the pom.xml files that are published to maven central.

Maven central guidelines require a license be stated (in theory at least...) - see https://central.sonatype.org/pages/requirements.html#sufficient-metadata

would it be possible to add a license element to jackson pom files?

**Comment by cowtowncoder** [comment]
So, LICENSE information is included in 2 places within artifacts:

1. Via parent pom (I'd have to check which one, but it is there)
2. Inclusion under META_INF

and I would ideally try not to add it in each leaf pom.xml, just to try to reduce boilerplate.

Is there some specific problem wrt tooling here? I am not dead set against inclusion for at least small set of pom.xml's if there is clear benefit, but want to keep fluff to minimum.

**Comment by radai-rosenblatt** [comment]
the organization i work for relies on automated license scanning of libraries - if the tooling cant pick up a license im forced to go through manual hoops to use the artifact. having the license straight in the pom is the clearest signal:

1. picking up license information from parent POMs may be a weaker signal - I'm not a lawyer, but is it possible for a project to use a parent POM yet use a different license? since jackson is picked up by maven central without specifying a license maybe there's an official legal opinion on this I can show the lawyers on my side to convince them?
2. inclusion in the artifact is (in my opinion) an even weaker signal since people do publish fat/uber jars and most mechanism of creating such jars may by default end up with multiple such license files in the artifact.

**Comment by cowtowncoder** [comment]
I disagree on (2): inclusion of LICENSE in artifact should be at least as strong indicator as any indirect indicator in build files (and possibly easier to access). But anyone repackaging jars with shading or uber-jars is responsible for following licensing information, including retaining information if they are publishing software further.

Anyway. I do not offer free legal guidance on licensing tho, so you may want to take this up with lawyers who have concerns, and figure out specific concerns there are: not just things that might be problematic.
With specific concerns I can consider if it makes sense to add more boilerplate in `pom.xml`; but I do not make changes just in case there might be some concern somewhere for somebody.

**Comment by GedMarc** [comment]
```
but I do not make changes just in case there might be some concern somewhere for somebody.
```
^^^
This. I need to learn this.

**Comment by radai-rosenblatt** [comment]
I agree people who shade are responsible for the results being correct. I was just saying that in my experience they dont :-)

I also agree my problems are not yours. i was just hoping the change would be acceptable.

**Comment by cowtowncoder** [comment]
Fair enough.

I think inclusion of license info for just 3 core projects might make sense. Will think about this.

**Comment by cowtowncoder** [comment]
Ok. After further contemplation, I added asl reference from 3 pom.xml's (jackson-core, jackson-annotations, jackson-databind), for 2.11 branch, master.
