### ISSUE TITLE
Polymorphic type with custom deserializer

### ISSUE THREAD

**Issue by alexkazancew** [FasterXML/jackson-core#600]
Hi!!!
I have the following JSON:

```json
{
    "type":"concrete",
    "poly":"{\"value\":\"CONCRETE VALUE\"}"
 }
```
As you see "poly" field is a JSON string. And its a polymorph

And I have that POJO`s.

```kotlin
class Data(
        @JsonTypeId
        val type: String,
        @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.EXTERNAL_PROPERTY, property = "type", visible = true)
        val poly: Base
)

@JsonSubTypes(
        JsonSubTypes.Type(value = Concrete::class, name = "concrete"),
        JsonSubTypes.Type(value = AnotherConcrete::class, name = "another")
)
interface Base

@JsonTypeName("concrete")
data class Concrete(val value: String) : Base


@JsonTypeName("another")
data class AnotherConcrete(val anotherValue: String) : Base
```
But when I try read value through object mapper, throws error

`InvalidDefinitionException: Cannot construct instance of Base`

And if I add @JsonDeserialize to "poly" field, it not calls that deserializer.

How I can solve this issue?

**Comment by cowtowncoder** [comment]
Please do not use issue tracker for asking usage questions: this is what mailing lists:

https://groups.google.com/forum/#!forum/jackson-user

and chat rooms

https://gitter.im/FasterXML/jackson-databind

are for. If you ask there, make sure to add piece of code you use to read value (that seems to be missing).
