### ISSUE TITLE
Optimizing ByteQuadsCanonicalizer when there are many unique keys

### ISSUE THREAD

**Issue by scottcarey** [FasterXML/jackson-core#613]
ByteQuadsCanonicalizer is causing trouble for me.   My documents are typically 1k to 6k in size, and each one of them contains at least one nearly unique identifier as a key.  So I have about 100 keys that are seen nearly every request,  about 2000 that are occasionally seen (about 5% of requests)  and a hundred million that are close to unique -- maybe each is seen once or twice a day over a hundred million parses.

The symbol table int[] grows past ~ 256k and it appears that every document parsed ends up copying the base int[] leading to heavy allocation pressure on the GC.  About 80% of the garbage in the app is this one source of allocation.

I did discover that I can turn this off, but then it switches to the Reader based parsing which is quite a bit slower (at that point, switching to other libraries becomes quite a bit faster).

I see a few possible fixes / suggestions:

1.  I can't control the MAX_ENTRIES_FOR_REUSE, unless I'm blind and there is a setting.  This could help, the first 500 or so entries are going to be the ones that are repeated, I'd love to bump this down from 6000 and try again.

2.  If the symbol table is large then its likely that many of these keys are unique and will never be seen again, or are very infrequently seen, and something a bit more LRU or LFU like would help avoid this problem.  I'm betting that 99.9% of situations where 'large symbol tables' happen that the table is filled up with items that are either never, or very rarely re-used.   So some mechanism that can remove infrequently used entries efficiently will win here.  It may also provide a mechanism to allow caching of string and numeric common values if it is efficient enough.

Some ideas -- a 'true' LRU or LFU is going to be way too expensive, there is not a need to know the perfect item to discard.  Something that takes a table with 1024 entries and turns it into one with 512 entries where the half that are dropped are approximately the least important would be fine -- if a frequently used key is dropped by accident, re-generating it every so often is not very expensive.  Think about it this way:  if the hit-rate for a commonly used string goes from 100% to 99.9%, we are still avoiding 999 out of 1000 string allocations and parses. 

I am imagining something like this after the table size crosses a threshold (no need for extra work if it is small enough):  An individual parse tracks a bitmap of touched keys, and the total number of keys found (so perhaps it touched 100 distinct keys across 250 key lookups).  If the ratio of touched keys to total table size is small enough (25%) then this is merged into the parent table.  Once the parent table has merged enough data -- crossing 50% of distinct keys in its bitmap or enough total lookups) it will have an approximate idea of the 'hot' keys and can discard the rest.

EDIT:
Here is something even simpler:  After crossing a size threshold, have the next X individual parses (perhaps as low as 1, mabe up to 16) note what keys were touched, and after those X parses, create a new base table that has only the keys touched by those.   The appropriate table size trigger and number of samples can be heiruistic based and adaptive.  Its almost a min-GC for the symbol table. 

EDIT (again, another idea):
The simplest GC mechanism would be to clear the table after it reaches a size threshold or a parse count threshold and make that threshold user configurable.  If I know that my table grows to size 3000 after 2000 parses, I know its going to be pretty efficient to drop it at about that size.  Yeah, it would be better to identify the common items and retain them, but its possible that it is cheaper to drop and re-generate than to try and identify those.  The table size growth curve + hit rate could be enough to identify when its time to discard without any user parameters. 

3.  Is it really required to copy the int[] on each parse?  My heap is filled with near-clones of the one held onto by the ObjectMapper plus any modifications made by the local parse.  I didn't dig too far into the code here, but what I'm observing is definitely copying of this array on each parse, when it is  about 70x larger than the source bytes being parsed.  Could the lookups be made thread-safe and individual parsers read from the common pool without a copy as well as use their own local writable one, when the table is large?  Cuckoo hash tables can be made so that concurrent reads are non-blocking, for example (see https://github.com/efficient/libcuckoo and the papers linked there, its good stuff, but non-trivial).  

Obviously, how big is too big is actually dependent on the average document size.  6000 distinct keys might not be enough for a large 1GB parse, and the 256k table copy is a drop in the bucket as well in that case.

4.  My document form is `{ "UNIQUE_IDENTIFIER": { ... }}`  There are other possible unique things in the document, but the most common entry in the table is for the root document.  If I could turn off this behavior for just that one element...   I'm actually considering manually parsing the start of the document and only passing the bytes of the inner object to Jackson.  But this seems like are fairly ridiculous work-around.  

Lastly, if I'm using ObjectMapper, and its mapping to a bean, the key names are obviously highly conserved.  But if inside that bean I've got a `Map<String, Foo>` or `Map<UUID, User>` then that is a big hint that maybe that map key might not be worth caching.   I realize that the code here doesn't have enough context to know if the JSON key corresponds to something like a map in the source code, but if there was a contextual hint, it would also help here.

**Comment by scottcarey** [comment]
After some more reflection, I think I'll be able to manually re-use parser instances to avoid generating one each time.   That will help the garbage issue, even if the symbol table is constantly bloated.

**Comment by cowtowncoder** [comment]
Yes, I think your analysis is valid, and unfortunately use case as described is not a good match for the way symbol canonicalization works.

Unfortunately design is heavily geared towards ability to reuse symbol tables, and is then essentially append-only method where new copy is only created when new symbol needs to be added. Trying to add LRU functionality or similar would be very difficult, and even simplest attempt (right now new entries become head in case of collision; conceptually might consider it more optimal to add at end... but that would require copying linked list, leading to copying of everything else).
I haven't been able to think of much improvements to now relatively old design (beyond some work trying to figure out limits for infinite expansion), although to be honest this is not an area I have spend a lot of time in recently.

I am always interested in ways to improve things of course.

Now... of things mentioned, making `MAX_ENTRIES_FOR_REUSE` configurable would probably be easy with newish (2.10) builder-style construction. Not sure if that would be valuable or not.

On copying of `int[]`: that is copy-on-write for hash area(s) and would not occur if all symbols needed were seen. However, with unique symbols, this does happen... and if it's really just one symbol (root), that is sort of worst case scenario.
Jackson 3.x has some improvements wrt databind/core interaction, avoiding many lookups (in a way generating smaller lookups per POJO), but whether that would help significantly in your case is not certain. Plus 3.x is still ways out, in the sense that while it works (`master` is where it lives), there will still be major changes making it unstable wrt compatibility.

One last thought: I think your suggestions would, in a way, require quite different symbol table approach: one that either does no reusing across reds at all, geared for large documents, or, at most, tries to generate small shareable core set (things referenced more than once, top N), and then on per-read (JsonParser instance / lifecycle) basis adds and uses temporary entries, but 
only ever promotes heavily used ones.
Implementing this would be sizable undertaking, and it would likely not (I think) replace default one but rather be an optional, manually enabled alternative. But as long as it would expose same API (I think it'd be possible to extract current class as abstract base class) it would likely be doable.

**Comment by scottcarey** [comment]
(version 2.9.9 FWIW)

Some more info: wrapping the input stream in a Reader for each record was about 10x faster, and also faster than disabling name canonicalization  (which only helped a little, and I'm not sure why, its possible I didn't disable it right -- should disabling name canonicalization stop the allocation of int[] here?  The heap was still dominated by them.).


If I construct a test over ~ 1GB of this data concatenated together one record per line, and use `reader.mapValues` and iterate over the entire set of data with one parser over raw utf8 bytes, its about 1.8x faster than using a BufferedReader and manually calling readLine() and passing the string to `reader.readValue` -- one parser per decode on strings.   If I pass that same data one byte[] at a time to decode individually, the heap explodes with large int[] allocations and I get the 10x slowdown (~20x worse than the single MappingIterator parse over raw bytes).

So its clear that for now I'm just going to wrap it in a Reader and not do anything crazy.

If there are any sane tricks for re-using a parser instance, that would help a lot.   Maybe an async style variation could accept byte[] chunks thrown at it incrementally?

I'll close this; it doesn't seem there is any quick way out and something more optimized for a large number of unique keys is a feature on its own.

**Comment by cowtowncoder** [comment]
Ok. Thank you for sharing these details. Part of performance benefit for this case, using char-backed over byte, is that the whole quad-based decoding adds significant overhead for the first time processing of a new name; whereas char-backed decoder is simpler and has less initial overhead (but no speed up for secondary cases, where byte[] based alternative is faster).
Symbol table implementation too is simpler for char case... although I am surprised by order of magnitude difference. That could perhaps be related to thresholds being used for "too large symbol table".

I think going with `Reader` version makes sense for now.

Async style parser should be able to actually take a sequence of `byte[]` chunks, as long as you separate root level content by white space. So maybe it's just a matter of adding one virtual space between content chunks?

**Comment by scottcarey** [comment]
Perhaps I'll be , I should be able to inject the boundaries needed for async.   I haven't used the Async style parser before, but I'm taking notes in case I have to come back for further optimizations beyond the Reader.   The reader change buys me a lot of time for now.  

I may also be able to convert some of the higher volume aspects of this project to SMILE or MsgPack or something similar if that is a lot faster to parse.  That will be an experiment for another day. 

Thanks for the feedback and info @cowtowncoder!

**Comment by cowtowncoder** [comment]
@scottcarey Sounds good. And I appreciate your taking time to explain the situation: these are kinds of challenges I am interested in and hope to address. I also realize that you have more pressing issues of actually getting work, as opposed to spending time help improve tools. :)

Just one more thought: I realized that wrt `int[]`: while there is just one main hash area, and it is instances of that that get discarded, expansion is not quite symmetric: in absence of high number of hash collisions, primary and secondary areas get packed quite efficiently. But if hashing produces lots of collisions, spill-over section is likely to lead to both inefficient lookups (for new unseen keys in particular) AND inefficient expansion of spill-over area (since that is considered to be rare case and is sub-optimal if it occurs commonly).

I would actually be interested in knowing distribution of symbols, since I could perhaps have a look if their hashing results in unusually high collision rate. Hashing algorithm used here by Jackson has not been defined (or refined) rigorously, but there are tests for some reported edge cases, and if names can be generated easily enough, I could add some more.

So, if at any point you had time and interest to maybe show how names are generated (if they area), or share a data file (like typical largeish file that contains field names), that could help see what exactly happens with hashing and symbol table updates.
Essentially, if distribution of primary/secondary/tertiary/spill-over leans over latter parts, there is a problem. Lookups from spill-over area are linear, and extension is done by linear allocation, with small increments.
