### ISSUE TITLE
wiki.fasterxml.com is dead

### ISSUE THREAD

**Issue by jeff303** [FasterXML/jackson-core#614]
The https://github.com/FasterXML/jackson-core/wiki page links to http://wiki.fasterxml.com/JacksonFAQ, but the latter no longer works (archive.org snapshot [here](https://web.archive.org/web/20170809231731/http://wiki.fasterxml.com/JacksonFAQ)).  I was unable to find the new source of this page, or else I would update the wiki myself.

**Comment by cowtowncoder** [comment]
Right, that Wiki (site that powered it) is unfortunately gone. I don't think that FAQ had much valid content for better or worse.

But I think I just removed the link yesterday? Can you still see it there?

**Comment by jeff303** [comment]
Yes it's still there, on the GitHub.com wiki link I posted. (The first URL). Ctrl+F for FAQ. There was something I found linked from StackOverflow so was trying to find the corresponding new link.

**Comment by cowtowncoder** [comment]
I do not see the link to FAQ (maybe you have cached copy of the page on browser?), but did notice a link to `fasterxml.com` home. Removed that as well.

**Comment by jeff303** [comment]
Yes, it was deleted in this revision: https://github.com/FasterXML/jackson-core/wiki/Home/_compare/f362b0bf29b72c3f126f1fe2a98796b742c0e50e...f05562c39b2753c545de19512b1ea69f4ff9e844

I was specifically thinking of the "Ext JS" handling section that was in the old FAQ.  Copied the relevant content to the aforementioned StackOverflow answer, but it occurs to me that people might be linking to this and following said links still, and yes, even though they are on older versions.  If it could simply be copied to the new wiki structure, I think it would be valuable.

**Comment by cowtowncoder** [comment]
New FAQ is here:

https://github.com/FasterXML/jackson/wiki/FAQ

and I added you to `wiki` team which should give you access to modify it (but you may need to approve a request).
I'd prefer incremental additions from old source since much of content is outdated at this point; and some of other things probably belong to other wiki pages instead of general FAQ.
