### ISSUE TITLE
Allow serialization with Single Quotes \' in stead of Standard Double Quotes \"

### ISSUE THREAD

**Issue by anismek** [FasterXML/jackson-core#617]
Adding something like this feature `JsonWriteFeature.USE_SINGLE_QUOTE`. Permitting to serialize:
`{"name": "value"}` to `{'name': 'value'}` and if also `JsonWriteFeature.QUOTE_FIELD_NAMES` is disabled to `{name: 'value'}`.
I know this is not standard JSON, but might be really helpful to get TypeScript-formatted JSON.

**Comment by anismek** [comment]
@cowtowncoder thanks !

**Comment by srgg** [comment]
Any chance to get this merged into the base line?

**Comment by cowtowncoder** [comment]
I am hoping to get this merged to be included in 2.12.0, but unfortunately there is lots of work and this is not one of priority items.

**Comment by srgg** [comment]
@cowtowncoder np, thank you for your work

**Comment by cowtowncoder** [comment]
Thank you! Let's hope it makes it in -- it is included on my long todo list:

https://github.com/FasterXML/jackson-future-ideas/wiki/Jackson-Work-in-Progress

**Comment by harsh201** [comment]
@cowtowncoder I am new here and would like to pick this one.

**Comment by cowtowncoder** [comment]
@harsh201 excellent! Make sure to start with 2.12 branch. Also PR #235 is pretty good; I'd make only couple of small changes.

**Comment by angelyan** [comment]
@cowtowncoder is this not possible already in 2.12 with `new JsonFactoryBuilder().quoteChar('\'').build()`?

**Comment by cowtowncoder** [comment]
@angelyan ... and you are absolutely right, it is.

Sometimes I surprise myself by rediscovering something I already implemented... and not all that long ago. :-D

**Comment by angelyan** [comment]
@cowtowncoder I think there's something missing, though. Shouldn't singles quotes be escaped and double quotes be left as is here?

https://github.com/FasterXML/jackson-core/blob/2e11f0cfc6a60172c3fbb971977809ed22d763e9/src/test/java/com/fasterxml/jackson/core/json/CustomQuoteCharTest.java#L78

**Comment by cowtowncoder** [comment]
I am sure there are different preferences; some might prefer minimal escaping, others keeping both.

If there is some follow-up improvements needed, filing a new issue is always possible.

**Comment by flowt-au** [comment]
Hi. 
In case someone else is going round in circles trying to work out how to do this here is what worked for me. 

The use-case is generating persistance "json" strings for RedisGraph database creates from a bean.
eg `{name: 'value', num: 23}` ie no quotes around property names and single quoted string values.

```java
// Use single quotes
JsonFactory builder = new JsonFactoryBuilder().quoteChar('\'').build();

ObjectMapper objectMapper = new ObjectMapper(builder);

// Do not surround property names with quotes. ie { firstName : "Mike" }
objectMapper.configure(JsonWriteFeature.QUOTE_FIELD_NAMES.mappedFeature(), false);

// Make a Person
Person person = new Person("Mike", "harvey", 34, true);

// Make the "json" for RedisGraph
String json = objectMapper.writeValueAsString(person);
System.out.println(json);
```
yields:
```
{ firstName : 'Mike', lastName : 'harvey', age : 34, ok : true }
```
Cool! :-)
Murray
