### ISSUE TITLE
Remove " Stupid eclipse.." comment from file JsonProcessingException.java

### ISSUE THREAD

**Issue by gauravdeshmukh612** [FasterXML/jackson-core#628]
Remove " Stupid eclipse.." from https://github.com/FasterXML/jackson-core/blob/master/src/main/java/com/fasterxml/jackson/core/JsonProcessingException.java. 
It not look good

**Comment by GedMarc** [comment]
Accurate tho xD all of my code hmm... 
Didn't think a cosmetic would bother, but I feel they're important to note for IDE short comings

**Comment by cowtowncoder** [comment]
@gauravdeshmukh612 As soon as I want someone to review my comments, I'll let you know.

Until then you can fuck off.
