### ISSUE TITLE
I want to understand why the DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES is true for default

### ISSUE THREAD

**Issue by farsunset** [FasterXML/jackson-core#629]
Why ?
Why ? 
Why ?

Usually we hope to igonre unkown properties when deseriallzation a json to java bean,
But your forget disable FAIL_ON_UNKNOWN_PROPERTIES ,this  is a big bug , i think!
When in the prod mode , the bean remove proterties , no one hope has fail , but your get crash~

**Comment by cowtowncoder** [comment]
@farsunset This  is NOT A FUCKING THING TO REPORT ON ISSUE TRACKER!!!!!!

**Comment by cowtowncoder** [comment]
Especially impressive that there is template saying this is kind of thing not to create issue for; issue would be for different repo, and that there is actually an issue wrt changing default if users feel that way.
