### ISSUE TITLE
JsonParser.getText() truncates field value to 10000 characters

### ISSUE THREAD

**Issue by laukus** [FasterXML/jackson-core#641]
**Describe the bug**
When attempting to parse a JSON that contains a field with a value of more than 10K characters, the parsed value is truncated to 10K characters when calling parser.getText() or parser.getValueAsString().

I observe that the whole value is present in the protected _inputbuffer variable of the JsonParser.

**Version information**
2.11.2

**To Reproduce**
https://github.com/laukus/jackson-troubleshoot

**Additional context**
Wrote a minimal test to reproduce. The large value in the test is a json in itself, which is the reason why I bumped into the issue. Truncated json won't parse.

**Comment by cowtowncoder** [comment]
I can reproduce this with 2.10.5 as well, and also with other input modes (byte-based, DataInput at least; will see about async too). Looking at content it looks like there is a boundary condition somewhere; escape sequence nicely at buffer boundary: this would explain why this has not been reported before (i.e. it's rare and nastiest kind).

**Comment by cowtowncoder** [comment]
@laukus D'oh. After wasting a bit of time here, not finding anything wrong, went back to looking at input data provided: as far as I can see, the escaped input data itself is truncated:

```
+ ".jar\\\",\\\"digest\\\":\\\"323964c36556eb0e\\\",\\\"size\\\":2097},{\\\"name\\\":\\\"reac\","
```

note that what is contained input buffer does not actually contradict this: there is indeed more input that follows (next field is `_serial` etc).

So it seems to me that this is a false alarm.

**Comment by laukus** [comment]
Bugger, sorry for wasting your time.
 
I must have fooled myself when I found a valid JSON i the input buffer, but that is  of course the entire input json, and not the token that is currently being processed.

**Comment by cowtowncoder** [comment]
@laukus hehe. That happens, no worries. It took me a while to realize this too; and since potential impact would be significant I'd rather err on side of caution. :)
