### ISSUE TITLE
Add Jackson handles extra commas in json and array

### ISSUE THREAD

**Issue by vampireslove** [FasterXML/jackson-core#643]
@Test
	public void testJackson() throws JsonMappingException, JsonProcessingException {
		String str ="{\"name\":\"jackson\",}";
		ObjectMapper mapper = new ObjectMapper();
		JsonNode node= mapper.readTree(str);
		System.out.println(node);
	}

I hope Jackson can ignore the extra comma at the end and don’t report an error when deserializing。

![image](https://user-images.githubusercontent.com/7031286/95569291-f263ee80-0a57-11eb-8895-233cd7966049.png)

**Comment by cowtowncoder** [comment]
Have you looked at `JsonParser.Feature` (or in 2.10 and later `JsonReadeFeature`)? There are couple of settings one of which might do what you want.

**Comment by cowtowncoder** [comment]
Specifically, enable

* `JsonReadFeature.ALLOW_TRAILING_COMMA` (if using Jackson 2.10 or later), OR
* `JsonParser.Feature.ALLOW_TRAILING_COMMA` (if using Jackson 2.9 or earlier -- also work on 2.10+ but is deprecated)

and parser should ignore optional trailing comma.

**Comment by vampireslove** [comment]
> Specifically, enable
> 
> * `JsonReadFeature.ALLOW_TRAILING_COMMA` (if using Jackson 2.10 or later), OR
> * `JsonParser.Feature.ALLOW_TRAILING_COMMA` (if using Jackson 2.9 or earlier -- also work on 2.10+ but is deprecated)
> 
> and parser should ignore optional trailing comma.

Thank you !
