### ISSUE TITLE
Add jackson ignores multiple escape characters

### ISSUE THREAD

**Issue by vampireslove** [FasterXML/jackson-core#644]
@Test
	public void testJackson() throws JsonMappingException, JsonProcessingException {
		String str = "{\\\\\"name\\\\\":\\\\\"jackson\\\\\"}";
		ObjectMapper mapper = new ObjectMapper();	
		mapper.configure(JsonReadFeature.ALLOW_TRAILING_COMMA.mappedFeature(), true);
		mapper.configure(JsonReadFeature.ALLOW_BACKSLASH_ESCAPING_ANY_CHARACTER.mappedFeature(), true);
		mapper.configure(JsonReadFeature.ALLOW_UNESCAPED_CONTROL_CHARS.mappedFeature(), true);
		mapper.configure(JsonGenerator.Feature.ESCAPE_NON_ASCII, true);
		JsonNode node= mapper.readTree(str);
		System.out.println(node);
	}
I hope Jackson can ignore the escape characters and don’t report an error when deserializing。
![image](https://user-images.githubusercontent.com/7031286/95645044-d579fa80-0aed-11eb-8496-7ea5292d5ff6.png)

**Comment by cowtowncoder** [comment]
That is invalid JSON, and can not be accepted.
