### ISSUE TITLE
[Feature] add additional more generic annotations

### ISSUE THREAD

**Issue by xenoterracide** [FasterXML/jackson-core#657]
this is probably more of a consideration for 3, but could be implemented for 2 as well. I'm using the 

```
com.fasterxml.jackson.dataformat:jackson-dataformat-yaml
```

but honestly this could apply to any format that's not json, it seems really odd to use `@Json*` annotations. I'd think that these could all just be changed to exlude the `@Json` so, e.g `@JsonCreator` would become `@Creator`. It might be worth making [like spring](https://github.com/spring-projects/spring-framework/wiki/Spring-Annotation-Programming-Model) and making these annotations composable, so `@JsonCreator` would then just "extend" `@Creator` for backwards compatability.

**Comment by cowtowncoder** [comment]
While I agree that it would have been nice to avoid use of "Json" in names back in the day, I am not sure it is worth all the hassle to try to start replacing them at this point, even for Jackson 3. And introducing another level of complexity with composability seems particularly problematic in context of both hierarchy-following annotations (Jackson annotation inheritance works for members, not just classes) and mixins.

I will leave this open just just in case it leads to improvement ideas (note: might belong to another repo as this repo is just for streaming API and not related to annotation definitions or handling).

**Comment by xenoterracide** [comment]
migrated https://github.com/FasterXML/jackson-annotations/issues/183
