### ISSUE TITLE
when using JsonGenerator method writeRawValue(String var1), output is not Pretty even when setting PrettyPrinter to DefaultPrettyPrinter

### ISSUE THREAD

**Issue by profmoh** [FasterXML/jackson-core#667]
Hello,

let me give an code example

```
JsonFactory jsonFactory = new JsonFactory();
JsonGenerator jsonGenerator = jsonFactory.createGenerator(any Writer), JsonEncoding.UTF8);

jsonGenerator.setCodec(new ObjectMapper());
jsonGenerator.setPrettyPrinter(new DefaultPrettyPrinter());

Person person = new Person();
person.setId(1);
person.setName("Jackson1");

jsonGenerator.writeStartArray();
jsonGenerator.writeObject(person );
jsonGenerator.writeRawValue("{\"id\":2,\"name\":\"Jackson2\"}");
jsonGenerator.writeEndArray();

jg.close();
```

I am expecting the output to be something like
[ {
  "id" : 1,
  "name" : "Jackson1"
}, {
  "id" : 2,
  "name" : "Jackson2"
} ]

but actually I am getting it
[ {
  "id" : 1,
  "name" : "Jackson1"
}, { "id" : 2, "name" : "Jackson2" } ]

as you can see the first one is prettified but the second one with is printed using writeRawValue is not.

thanks a lot.

**Comment by cowtowncoder** [comment]
It seems to be this might be expected -- "raw" in `writeRawValue()` specifically means "include EXACTLY AS-IS in output", and thereby nothing within value would be changed in any way. Writer has to assume this acts similar to a scalar value like number or boolean.

**Comment by cowtowncoder** [comment]
I don't see anything working different from expected (as per my explanation above), closing.
