### ISSUE TITLE
Problem when converting String after saving child Map object to parent Map object.

### ISSUE THREAD

**Issue by JangCool** [FasterXML/jackson-core#675]
Hi~

I use jackson-core, bind, version 2.11.4.

But there's a problem.
Problem when converting String after saving child Map object to parent Map object.

When added to a child Map multiple times, it is not converted to a string when a certain number is reached.

I'd appreciate your help.

When output is normal : 
START ####################################### 
size : 80
{"AA42":{"AGENT9":"1000","AGENT18":"1000","AGENT5":"1000","AGENT16":"100 ... ...
END   ####################################### 

When the output is not working.
START ####################################### 
size : 80

END   ####################################### 

```
		ObjectMapper mapper = new ObjectMapper();
		try {
		Map<String, Object> realtimeData = new HashMap<>();		
		for (int i = 0; i < 80; i++) {
			Map<String,Object> instanceData = new HashMap<>(200);
			instanceData.put("AGENT1", "1000");
			instanceData.put("AGENT2", "1000");
			instanceData.put("AGENT3", "1000");
			instanceData.put("AGENT4", "1000");
			instanceData.put("AGENT5", "1000");
			instanceData.put("AGENT6", "1000");
			instanceData.put("AGENT7", "1000");
			instanceData.put("AGENT8", "1000");
			instanceData.put("AGENT9", "1000");
			instanceData.put("AGENT10", "1000");
			instanceData.put("AGENT11", "1000");
			instanceData.put("AGENT12", "1000");
			instanceData.put("AGENT13", "1000");
			instanceData.put("AGENT14", "1000");
			instanceData.put("AGENT15", "1000");
			instanceData.put("AGENT16", "1000");
			instanceData.put("AGENT17", "1000");
			instanceData.put("AGENT18", "1000");
			instanceData.put("AGENTgf", "1000");
			instanceData.put("AGENTab", "1000");
			instanceData.put("AGENTcd", "1000");
			instanceData.put("AGENTef", "1000");
			instanceData.put("AGENTgh", "1000");
//			instanceData.put("AGfffNT", "1000");

                       realtimeData.put("AA"+i, instanceData);
		}
		
		System.out.println("START ####################################### ");
		System.out.println("size : " +realtimeData.size());
		System.out.println(mapper.writeValueAsString(realtimeData));
		System.out.println("END   ####################################### ");

		} catch (Exception e) {
			e.printStackTrace();
		}
```

**Comment by cowtowncoder** [comment]
I am not sure I understand: `instanceData` is not assigned to `realtimeData` anywhere?

**Comment by JangCool** [comment]
@cowtowncoder sorry..

When many elements are added using the PUT function, they are not converted to the json string and the blank value is output.

Do I need to increase the buffer size? Do you provide those options separately?

**Comment by cowtowncoder** [comment]
@JangCool no, there shouldn't be any need for anything unusual. Code as shown should produce output.
So this exact code produces no output? How about if you print out String length instead of content?

**Comment by JangCool** [comment]
@cowtowncoder 
Oh... I'm sorry. It's my mistake.
It seems that there is no output after a certain length in the IDE console window. The string length is output correctly. Thank you.

**Comment by cowtowncoder** [comment]
@JangCool that makes more sense, was wondering about that. Thanks!
