### ISSUE TITLE
Eliding sensitive data during deserialization

### ISSUE THREAD

**Issue by pr0ton** [FasterXML/jackson-core#681]
**Use case**
When we deserialize payloads that contain sensitive information, on failure the exception can contain the entire payload. This gets logged to our logging system and includes sensitive info and PII. 

**Describe the solution you'd like**
* Control over encrypting or eliding sensitive payloads

**Describe alternatives you've considered**
* Catching all exceptions at every source and transforming exceptions to remove sensitive information

**Additional context**

**Comment by cowtowncoder** [comment]
Not sure what else to do -- may be re-filed with bit more info on how the payload was to be hidden. Also note that whoever catches exception has full control over what to do with it, including not dumping it all, and/or hiding information.
