### ISSUE TITLE
OSS-Fuzz integration

### ISSUE THREAD

**Issue by fmeum** [FasterXML/jackson-core#685]
As a follow-up to https://github.com/FasterXML/jackson-dataformats-binary/issues/254, I have drafted a commit that integrates `jackson-core` into OSS-Fuzz: https://github.com/CodeIntelligenceTesting/oss-fuzz/commit/fdfcb8a664e06ba531d3056e3348f77c6f79de57

This integration will be very similar to the one for `jackson-dataformats-binary`, but additionally uses an existing corpus of difficult to parse/broken JSON documents as well as a slightly more complicated fuzz target that randomly enables parser features.

@cowtowncoder If you agree, I will also submit this commit as a PR to OSS-Fuzz.

**Comment by cowtowncoder** [comment]
@fmeum Thank you for checking: yes, that is a good addition too, given that the JSON backend is the most widely used. Finally, there is `jackson-dataformat-xml` that could benefit from this, and maybe even `jackson-dataformats-text` (csv, .properties, yaml).
