### ISSUE TITLE
UTF8StreamJsonParser _inputStream.read() == 0 is treated as a bad stream

### ISSUE THREAD

**Issue by netikras** [FasterXML/jackson-core#691]
Hello,

[here](https://github.com/FasterXML/jackson-core/blob/master/src/main/java/com/fasterxml/jackson/core/json/UTF8StreamJsonParser.java#L208) I see code:

```
count = _inputStream.read(_inputBuffer, 0, space);
if (count > 0) {
  // do stuff
  return true;
}

_closeInputStream();
if (count == 0) {
  _reportBadInputStream(_inputBuffer.length);
}

```

However, this is somewhat of a problem IMO. I'm trying to read multiple JSONs from a gzipped TCP input stream over a slow connection. More often than not `inputStream.available()` returns 0, but the channel is still alive and kicking. Consequently, inputStream.read(...) returns 0 quite often too.

Problem is, If I'm lucky, I can read only one or two jsons from the stream of 50 or 500, because as soon as the is.read() returns 0 (the RcvQ buffer is empty, but the connection is still alive), ObjectMapper kills the JsonParser by nulling the inputStream. And subsequent calls to read the next token fail, because... the inputStream is no more.

I propose to change this

```
            // End of input
            _closeInput();
            // Should never return 0, so let's fail
            if (count == 0) {
                _reportBadInputStream(_inputBuffer.length);
            }
```

into this

```
            // End of input
            if (count == -1) {
                _closeInput();
            }
```

Frankly, I couldn't find any reference saying that is.read(...) == 0 is a sign of a bad stream. If a stream is bad it's supposed to return -1 or throw an IOE.

Also, [JDK docs](https://docs.oracle.com/en/java/javase/15/docs/api/java.base/java/util/zip/Inflater.html#inflate(byte%5B%5D,int,int)) claim that it's perfectly fine for an Inflater (an entity GZIPInputStream uses underneath) to return 0 in read(...) calls. It's not an error - it's just a state in which it requires more data from the stream.

> Uncompresses bytes into specified buffer. Returns actual number of bytes uncompressed. A return value of 0 indicates that needsInput() or needsDictionary() should be called in order to determine if more input data or a preset dictionary is required. In the latter case, getAdler() can be used to get the Adler-32 value of the dictionary required.

EDIT:
It works quite well if I insert a Thread.sleep(100) before each MappingIterator.hasNext(). This way I can read all the jsons in the stream, be it hundreds or thousands (tested!). Which confirms this theory. However, such an approach slows down my application beyond tolerable levels and it's not a workaround I'd like to leave there.

**Comment by cowtowncoder** [comment]
Here's the Javadoc:

https://docs.oracle.com/javase/8/docs/api/java/io/InputStream.html#read-byte:A-

```
Reads some number of bytes from the input stream and stores them into the buffer array b. The number of bytes actually read is returned as an integer. This method blocks until input data is available, end of file is detected, or an exception is thrown.

If the length of b is zero, then no bytes are read and 0 is returned; otherwise, there is an attempt to read at least one byte. If no byte is available because the stream is at the end of the file, the value -1 is returned; otherwise, at least one byte is read and stored into b.
```

And so as far as I know, blocking streams are definitely not allowed not to read anything, unless:

1. Asked to not read anything (`0` passed as length), or
2. End-of-input: must return `-1`
3. There is an error condition : throw `IOException`

I would suggest you first check why the stream you have does not follow this definition.

**Comment by netikras** [comment]
While it doesn't say that returning 0 is an error, you're right about fixing the InputStream. The original inputstream is PipedInputStream and, apparently, writer is falling behind. As a result the reading thread (part of java's PipedInputStream) drains the buffer and leaves 0 bytes available. 

My solution was to proxy PipedInputStream through a custom InputStream that has methods

```
                private void waitUntilAvailable(InputStream is) throws IOException {
                        int retriesLeft = 500;
                        while (is.available() <= 0 && retriesLeft-- > 0) {
                            synchronized (is) {
                                is.notifyAll();
                            }
                            quietly(() -> sleep(10L));
                        }
                    }

                    @Override public int available() throws IOException {
                        InputStream is = io.getStdout();
                        waitUntilAvailable(is);
                        return is.available();
                    }
```

and read(): int calls waitUntilAvailable() before calling the actual is.read().

This slows down the implementation, but also makes it reliable enough. And faster than just Thread.sleep(200) before each json read (not to mentions a single json could be 2x RcvQ buffers, which means the json reading can fail mid-way).

Thank you @cowtowncoder for your time.

For anyone reading this - be careful when using GZIPInputStream with PipedInputStream (or any is) that could be slow and/or (mis)use locking primitives

**Comment by cowtowncoder** [comment]
One thing I forgot to mention is this: the real problem returning `0` is that if that is allowed, caller can very easily get into infinite busy loop because there is no other way to generally block on input: read() abstraction is intended to be THE blocking mechanism.
Otherwise every reader would basically have to use arbitrary `Thread.sleep()` calls or something.
Use of `available()` would not solve this either, both since it is not required to return anything but 0 ever (it simply must guarantee that whatever it returns truly is available; but need not offer complete picture).

So accepting 0 answer would complicate life without much benefits; and this is exactly why the check is made.
