### ISSUE TITLE
Templating engine for JSON tree

### ISSUE THREAD

**Issue by achatterjee104** [FasterXML/jackson-core#693]
It might be required to generate a projected version of the given JSON where some of the fields of original JSON might be omitted. This projection works based on a template version of the original JSON. A template JSON is a JSON that is structurally same with the original JSON but all the leaf nodes holds only boolean values (denoting if this node will be present in projection).
In summary, it would be nice to have some kind of utility to create the template and generate the projection based on the template and original JSON. 
Also for array type elements, template JSON will have single element (any of the existing elements) as representation of all elements and the templatization of this single element will be applicable for all elements in the projected JSON. 
For example,

> Original JSON: {"field1":"value1", "field2": {"field3":"value3", "field4":"value4"}, "field5":[{"field6":"value60", "field7":"value70"}, {"field6":"value61", "field7":"value71"}, {"field6":"value62", "field7":"value72"}]}

> Template JSON: {"field1":"true", "field2": {"field3":"true", "field4":"true"}, "field5":{"field6":"true", "field7":"true"}}     //note: array is reduced to single element

> Edited template: {"field1":"true", "field2": {"field3":"**false**", "field4":"true"}, "field5":{"field6":"true", "field7":"**false**"}}        //dont need "field3" and "field7" in array elements

> Projection: {"field1":"value1", "field2": {"field4":"value4"}, "field5":[{"field6":"value60"}, {"field6":"value61"}, {"field6":"value62"}]}

**Comment by achatterjee104** [comment]
Created in this repo by mistake, need to move to databind repo.

**Comment by gabrieljones** [comment]
Is there a link to the moved issue?
