### ISSUE TITLE
`ArrayOutOfBoundException` at `WriterBasedJsonGenerator.writeString(Reader, int)`

### ISSUE THREAD

**Issue by jeffreye** [FasterXML/jackson-core#702]
I am invoking `writeString(myReader, -1)` on a JsonGenerator and get this error sometimes.

```
java.lang.ArrayIndexOutOfBoundsException: Index 4000 out of bounds for length 4000
	at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator.writeString(WriterBasedJsonGenerator.java:466) ~[jackson-core-2.12.0.jar:2.12.0]
```

https://github.com/FasterXML/jackson-core/blob/3c386bfcb6dfbbc06a4cfe4e2693eef70b76a43e/src/main/java/com/fasterxml/jackson/core/json/WriterBasedJsonGenerator.java#L462-L470

Basically, we need to add this case to the line 
```
(_outputTail + len) >= _outputEnd
```

**Comment by cowtowncoder** [comment]
Sounds like a flaw to fix, yes.

Do you happen to have a reproduction to use as a unit test? It would be great to verify the fix.

**Comment by jeffreye** [comment]
```
        final ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
        final JsonFactory factory = new ObjectMapper().getFactory();
        final JsonGenerator generator = factory.createGenerator(new PrintWriter(byteArrayOutputStream));

        generator.writeStartArray();
        
        // create a relative big string to fill the _outputBuffer
        for (int i = 0; i < 799; i++) {
            generator.writeString(new StringReader("ab"), -1);

        }

        // throws java.lang.ArrayIndexOutOfBoundsException: 4000
        generator.writeString(new StringReader("abc"), -1);

        generator.writeEndArray();
        generator.flush();
        System.out.println(byteArrayOutputStream.toString());
```

it's a little bit tricky to get the error

**Comment by cowtowncoder** [comment]
Thank you @jeffreye! Yes, buffer edge conditions like this likely is are tricky to reproduce. I appreciate your help.

I'll add this to my TODO list: it may take a while to get there but definitely want to fix the issue.

**Comment by cowtowncoder** [comment]
Oh my. That method is.... all kinds of wrong. Bounds checks are incorrect in multiple places.
Thank you for reporting this, will try to see how to best address.
