### ISSUE TITLE
@JsonIgnoreProperties isn't respected when used as a meta-annotation

### ISSUE THREAD

**Issue by efenderbosch** [FasterXML/jackson-core#703]
version: 2.12.3

This Kotlin annotation:
```kotlin
@Target(CLASS)
@JsonIgnoreProperties(value = ["page", "limit", "sort"])
annotation class IgnorePageableProperties
```

Or equivalent Java annotation:
```java
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@JsonIgnoreProperties(value = {"page", "limit", "sort"})
public @interface IgnorePageableProperties {
}
```

Does not seem to be respected during deserialization.

```kotlin
@IgnorePageableProperties
data class OrganizationQuery(
  // ...
)
```

If `sort`, `limit`, or `page` are present in the JSON, then deserialization throws `UnrecognizedPropertyException`

Using `JsonIgnoreProperties` directly does work as expected, though:
```kotlin
@JsonIgnoreProperties(value = ["page", "limit", "sort"])
data class OrganizationQuery(
  // ...
)
```

I can probably solve this with a `DeserializationProblemHandler` but it seems like the meta-annoation should work.

**Comment by cowtowncoder** [comment]
Jackson requires use of `@JacksonAnnotationsInside` on meta-annotations; it does not expand/traverse annotation types without it (although if you want to change that, I think `AnnotationIntrospector` has a way to change that check).
So you should be able to add `@JacksonAnnotationsInside` to `IgnorePageableProperties` and things should work as expected.

**Comment by efenderbosch** [comment]
Ahhh... I tried `@JacksonAnnotations`

Thanks!
