### ISSUE TITLE
why  user ArrayNode `s asText() method will return an empty String ""?

### ISSUE THREAD

**Issue by YongMingMao** [FasterXML/jackson-core#706]
version: 2.9.9
After I parse an json String to ArrayNode,then I want to get this json String back by using arratNode.asText()，the result is an empty String.
How can I get json String back by using arrayNode.I did try toString(),But it doesn't return an proper json String.
help me and thank you.

**Comment by cowtowncoder** [comment]
2.9.9 is a very old version, please use newer one: `toString()` in 2.9 was not designed to produce valid JSON but this was added in 2.10 I think (I would recommend just using 2.12.4, the latest, but 2.10.4 should work).

`asText()` is designed to return String value, if one exists, or coerce scalar value like number or boolean. But not to serialize structured values like Arrays or Objects.

**Comment by YongMingMao** [comment]
Thank you very much,your answer is really helpful.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tatu ***@***.***&gt;; 
发送时间: 2021年7月7日(星期三) 晚上11:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FasterXML/jackson-core] why  user ArrayNode `s asText() method will return an empty String &quot;&quot;? (#706)





 
2.9.9 is a very old version, please use newer one: toString() in 2.9 was not designed to produce valid JSON but this was added in 2.10 I think (I would recommend just using 2.12.4, the latest, but 2.10.4 should work).
 
asText() is designed to return String value, if one exists, or coerce scalar value like number or boolean. But not to serialize structured values like Arrays or Objects.
