### ISSUE TITLE
Unexcepted json format when use "SNAKE_CASE"

### ISSUE THREAD

**Issue by mark4z** [FasterXML/jackson-core#724]
when use ObjectMapper.setPropertyNamingStrategy(PropertyNamingStrategies.SNAKE_CASE) ,the filed like 'sth2' will be format to 'sth2', not 'sth_2', it's normal?

**Comment by cowtowncoder** [comment]
This is not a support forum for asking questions: in future please use either:

1. Mailing list: https://groups.google.com/g/jackson-user
2. Gitter chat: https://gitter.im/FasterXML/jackson-databind

But as to this behavior, yes, I think that is as expected as numbers are considered to be similar to lower-case characters. Word boundary is only found at upper/capital-case boundary.
I can see why someone might prefer alternative interpretation but currently there is no configurability.

You can probably sub-class implementation to change it tho.
