### ISSUE TITLE
CXF problems after upgrading to 2.2.0 from 2.1.4

### ISSUE THREAD

**Issue by gmatadh** [FasterXML/jackson-core#74]
Now I'm seeing the following warning message:

15:34:18.035 [WARN] org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor:: - No message body writer has been found for response class ArrayList.

**Comment by reda-alaoui** [comment]
Hi,

I was having the same issue while using `jackson-jaxrs-json-provider 2.4.0` with `apache-cxf 2.7.3`.
Moving to `apache-cxf 2.7.14` solved my issue.
Hope it will help.
