### ISSUE TITLE
java.lang.IllegalArgumentException: No serializer found for class XXX.YYY.ZZZ and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)

### ISSUE THREAD

**Issue by yamin8000** [FasterXML/jackson-core#741]
I'm using Jackson `2.13.1`, suppose `XXX.YYY.ZZZ` is a class in a library or a jar that I don't have access to modify.
When running the project in JVM there's no problem but if I build project using GraalVM native image tool I will encounter this error:

> java.lang.IllegalArgumentException: No serializer found for class XXX.YYY.ZZZ and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)

What am I missing here?

**Comment by cowtowncoder** [comment]
I don't know a ton about GraalVM but I think it will only ever include and expose reflection information on things you explicitly indicate. So you must tell it somehow to expose information (methods at least) of POJO types you use.
If not, Jackson will not find any properties and you would get exception like that.
