### ISSUE TITLE
JSON deserialization exception, may be there is Annotation transform?

### ISSUE THREAD

**Issue by herywang** [FasterXML/jackson-core#743]
1. In httprequest body:
<img width="865" alt="image" src="https://user-images.githubusercontent.com/28130163/160086878-04e455d3-5b6c-4f82-b8ca-f4b643288d5c.png">
2. subclass: StorageHiveRequest
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/28130163/160087349-07e52b8c-3e82-4d42-aecc-61778790c07a.png">
3. StorageHiveFieldDTO is a sub class of StorageFieldDTO:
<img width="852" alt="image" src="https://user-images.githubusercontent.com/28130163/160087474-2c56d3a5-a89d-4a52-8cd1-7705ad895c42.png">
4. actually, I write a sub-class in StorageHiveRequest, and not write storageType parameter in http request. 
I still get the error:
<img width="1506" alt="image" src="https://user-images.githubusercontent.com/28130163/160087914-84d3f984-bdab-45cd-80f9-442e36d88c62.png">

**Comment by cowtowncoder** [comment]
Wrong repo, but in general, wrong place. Usage questions are not Issues to report but should be asked on mailing lists:

https://groups.google.com/g/jackson-user

or gitter chat:

[gitt
](https://gitter.im/FasterXML/jackson-databind)


Closing as not-a-bug.
