### ISSUE TITLE
Annotation on abstract class are ignored

### ISSUE THREAD

**Issue by Elikill58** [FasterXML/jackson-core#756]
I have an abstract class like this:
```java
@JsonIgnoreProperties(ignoreUnknown = true)
public class AbstractItem {

   @JsonProperty(access = JsonProperty.Access.READ_ONLY)
   public int order;

   public AbstractItem(int order) {
      this.order = order;
   }
}
```
I have a class like :
```java
public class ColoredItem extends AbstractItem {
   
   public ColoredItem(int order) {
      this.order = order;
   }
}
```
Then, I have a more global class that declare the item such as:
```java
public class Items {
   public ColoredItem itemA = new ColoredItem(1);
}
```
If I serialize `Items` with empty Json (or with other things), the order will be set as 0. It also don't use getter even with `allowGetters = true`. The only way to have `order` as the given value (1) is to set it after the Jackson mapping or set into the json. Both things are NOT what I want.

Can you fix it ?

**Comment by cowtowncoder** [comment]
Please use mailing lists for usage questions:

https://groups.google.com/g/jackson-user

This is not a general support forum: issue tracker is for reporting issues and requesting new features.
