### ISSUE TITLE
Issue with write an object larger than 2GB

### ISSUE THREAD

**Issue by 1zg12** [FasterXML/jackson-core#760]
* Include version information for Jackson version you use
Jackson-databind-2.13.2
Jackson-core-2.13.2

When write an object of a large size (more than 2GB), it would throw out an `OutOfMemory` Exception

https://github.com/FasterXML/jackson-databind/blob/3be614716f4736867379345c6febbc0c3898050f/src/main/java/com/fasterxml/jackson/databind/ObjectMapper.java#L3850

![image](https://user-images.githubusercontent.com/52658745/170166962-e03b8c3d-f3d3-4190-a4f2-16f4219f1557.png)

**Comment by cowtowncoder** [comment]
This is not a bug: for large content, please use `OutputStream`. `writeValueAsBytes()` is not really meant for serializing humongous output.
