### ISSUE TITLE
issue with parsing negative numbers with no digit before the decimal point

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-core#782]
An example is '-.125'. This is not valid in standard JSON but jackson has JsonReadFeature.ALLOW_LEADING_DECIMAL_POINT_FOR_NUMBERS to allow it. The feature works for positive numbers but not for negative numbers.

See #777 and #781 for failing tests

**Comment by cowtowncoder** [comment]
Was able to solve the case for `UTF8StreamJsonParser`, code differs a bit with others but hope to do the same.
This will also include `+` in `getText()` (at least for the case I fixed).

**Comment by cowtowncoder** [comment]
`UTF8DataInputJsonParser` similar to `UTF8StreamJsonParser` so fixing that easy too.
Tricky case is `ReaderBasedJsonParser` since it tries to optimize things, trying to reuse input buffer (that is, avoid use of `TextBuffer`) and then has to worry about buffer boundary conditions.

**Comment by cowtowncoder** [comment]
Was able to fix reader case easily as well.

But looking at code I am fairly certain that it won't work for all cases, especially with buffer boundary conditions. 
I think I'll try to extend tests to try to catch such cases, although I guess Fuzz-testing would work best for stuff like this.
