### ISSUE TITLE
`class file for com.fasterxml.jackson.core.exc.StreamWriteException not found` when compiling with jackson-databind 2.13.x(Compilation is successful with 2.12.x )

### ISSUE THREAD

**Issue by cliu123** [FasterXML/jackson-core#797]
Issue is described in the title.
Failing compilation: https://github.com/cliu123/security/runs/7334731513?check_suite_focus=true
I do see [the class](https://github.com/FasterXML/jackson-core/blob/2.13/src/main/java/com/fasterxml/jackson/core/exc/StreamWriteException.java) existing in 2.13 branch. Did I miss anything? Is the artifact in Maven repo the latest one?

**Comment by cowtowncoder** [comment]
You have a too old `jackson-core` as dependency. Jackson-databind 2.13 requires jackson-core 2.13 (or newer, once 2.14 is released). That exception is defined in `jackson-core`, likely added in 2.13.

When using Maven and Gradle -- and especially if using `jackson-bom` to help with version set compatibility -- jackson-databind 2.13 would pull in jackson-core 2.13.
But somehow your build definition is forcing an older version (or possibly there is a duplicate).

So you will need to figure out where the old dependency comes from and fix it.
