### ISSUE TITLE
Use `BigDecimalParser` for BigInteger parsing very long numbers

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-core#814]
Maybe something for jackson 2.15. Relates to #813

String to BigInteger support is currently done using `new BigInteger(str)`.

BigDecimalParser has some performance related code for handling numbers with many digits. #813 suggests that we might be able to get improvements in performance and error handling by using some ideas from jsoniter_scala. BigInteger could probably benefit from these too.

@plokhotnyuk fyi

**Comment by pjfanning** [comment]
@cowtowncoder could we consider #826 as a late breaking change for Jackson 2.14.0?

**Comment by cowtowncoder** [comment]
@pjfanning Considering everything else, I think that's safe enough so merged PR to get this improvement in.
I do need to stop merging things of course, but this seemed like non-problematic thing even if last minute.
