### ISSUE TITLE
jackson-core 2.14.0-rc2 requires OSGi bnd artefacts 

### ISSUE THREAD

**Issue by poutsma** [FasterXML/jackson-core#824]
Hi,

The Spring Framework is trying to upgrade to Jackson 2.14.0, so that we can set it as our baseline for the upcoming 6.0.x branch, and use the `ByteBufferFeeder` introduced through #478 (thanks!). Unfortunately, when upgrading from 2.13.4 to 2.14.0-rc2 we run into the following warning: 

```
/Users/arjen/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-core/2.14.0-rc2/16f52b48723470c8e8a7f8f3fe80c5093eb3e9c3/jackson-core-2.14.0-rc2.jar(/com/fasterxml/jackson/core/JsonFactory.class): 
warning: Cannot find annotation method 'value()' in type 'ServiceProvider': class file for aQute.bnd.annotation.spi.ServiceProvider not found
```
(line break added for clarity)

Because we use `-Werror` during compilation, this warning breaks our build. Of course, it can be resolved by adding dependencies to the class path (specifically `biz.aQute.bnd:biz.aQute.bnd.annotation` and `org.osgi:osgi.annotation`), or by changing our build to ignore this specific warning.

I still thought it wise to make you aware of this warning, as I am hoping that there is something that can be done, and users can use Jackson 2.14 without getting warnings about missing OSGi artefacts.

**Comment by cowtowncoder** [comment]
Does #822 solve this?

**Comment by poutsma** [comment]
> Does #822 solve this?

I am not sure.

@sdeleuze, in our meeting today you mentioned a related problem (and potential solution ?) which I cannot recall anymore. Do you have further insights?

**Comment by sdeleuze** [comment]
Yeah this is behavior of `javac` that is lenient for annotation not present in the classpath (no warning in that case) except for enum used in annotation attribute.

We suffered that with [@Nonnull](https://www.javadoc.io/doc/com.google.code.findbugs/jsr305/latest/javax/annotation/Nonnull.html) `when` attribute and I have the feeling this is the same [here](https://github.com/FasterXML/jackson-core/blob/2.14/src/main/java/com/fasterxml/jackson/core/JsonFactory.java#L49) with `aQute.bnd.annotation.Resolution.OPTIONAL`.

Sadly no other workaround than avoiding using such enum in annotation attributes when possible since this kind of warning is super annoying for developers.

**Comment by poutsma** [comment]
To give some further info, the warning is due to the `-Xlint:classfile` argument we use for `javac`. I will disable this warning in the Spring Framework build for now, until this issue is resolved.

**Comment by cowtowncoder** [comment]
The problem here is that addition itself is a feature (#768 and follow-up #822) not bug. Not quite sure if it is possible to do both -- perhaps I will need to revert this, considering that Spring usage is more important than speculative OSGi benefits.

**Comment by cowtowncoder** [comment]
Ok. I will revert these changes; and likely publish `2.14.0-rc3` for verification purposes.

**Comment by cowtowncoder** [comment]
OSGi annotation changes reverted.

**Comment by poutsma** [comment]
I can confirm that this is fixed in 2.14.0-rc3. Thanks!

**Comment by cowtowncoder** [comment]
Good, thank you for verifying @poutsma.

**Comment by kriegfrj** [comment]
> Yeah this is a behavior of `javac` that is lenient for annotation not present in the classpath (no warning in that case) except for enum used in annotation attribute.
> 

 That would seem to me to be a bug in javac. Is there a documented reason anywhere for this enum exception for compile-time retention in javac?

**Comment by sdeleuze** [comment]
Not sure if that's considered as a bug or a feature on OpenJDK side, but that's IMO unlikely to change and past and current versions of OpenJDK all have this behavior, so it look likes we have to live with that.
