### ISSUE TITLE
Cannot access map directly without holding write lock!

### ISSUE THREAD

**Issue by CaoTrongThang** [FasterXML/jackson-core#832]
Hello sir, I keep getting this issue but don't really know why, i just want to convert an object to a json string

**Comment by cowtowncoder** [comment]
What the? This makes no sense as-is. What write-lock? Where? Who is claiming an issue, why, for what?
Please include some information on what the problem is -- I am not a mind-reader.

**Comment by CaoTrongThang** [comment]
Sorry bro, but i fixed it, thanks

**Comment by cowtowncoder** [comment]
Ok good. :)
