### ISSUE TITLE
Allow inclusion of request body for JsonParseException

### ISSUE THREAD

**Issue by cowwoc** [FasterXML/jackson-core#86]
As a follow-up to issue #77, please include the entire request body in the exception's message in case of a parsing error. Users will need this extra context to figure out why the parsing error occurred.

**Comment by cowtowncoder** [comment]
So, as can be seen from above, #258 makes it possible to attach content into exception.
Could perhaps consider automation for simple cases where input comes as `String` or `byte[]`...
