### ISSUE TITLE
consider inlining BigDecimal toDouble and toFloat improvements

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-core#870]
https://github.com/openjdk/jdk/pull/9410

Even if these changes are merged soon, they will only go into Java 20 or 21. If we inline them in jackson-core, even Java 8 users benefit. jackson-core already has fast float and double writing code that is borrowed straight from Raffaello Giulietti's fantastic work speeding up Java number support.

Probably best to wait until the PR above is ready to be merged.

Based on https://github.com/wrandelshofer/FastDoubleParser/issues/32

**Comment by pjfanning** [comment]
Let's close this - the licensing of code in OpenJDK space is problematic (despite the classpath exception).

**Comment by cowtowncoder** [comment]
Agreed.
