### ISSUE TITLE
2.15 release notes: mention that jackson-core is now a multi-release jar

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-core#897]
* this is of interest to anyone who creates fat jars for deployment of their apps (if those fat jars include jackson-core)
* was introduced because the FastDoubleParser code is now a multi-release jar

**Comment by cowtowncoder** [comment]
Ok, is this something you can edit, or do you need access? This would probably belong under "Compatibility" section?

**Comment by pjfanning** [comment]
@cowtowncoder I added a quick mention here - https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.15#jar-changes

I don't think there is much point in going to a lot of detail.

**Comment by cowtowncoder** [comment]
Thank you @pjfanning ! I added bit more context on it being for efficient number parsing.

**Comment by cowtowncoder** [comment]
Too bad we don't have an issue/PR existing... but come to think of that, I'll just list this issue in release note file, as a reference.

**Comment by edward-capriolo-db** [comment]
> @cowtowncoder I added a quick mention here - https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.15#jar-changes
> 
> I don't think there is much point in going to a lot of detail.

I think there is a good point in going into detail. :)

Error creating shaded jar: Problem shading JAR 

/.m2/com/fasterxml/jackson/core/jackson-core/2.15.2/jackson-core-2.15.2.jar entry META-INF/versions/19/com/fasterxml/jackson/core/io/doubleparser/FastDoubleSwar.class: java.lang.IllegalArgumentException: Unsupported class file major version 63

My shade plugin that has been happily making spark- uber jars breaks and it is very confusing to sort this out.

**Comment by pjfanning** [comment]
> > @cowtowncoder I added a quick mention here - https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.15#jar-changes
> > I don't think there is much point in going to a lot of detail.
> 
> I think there is a good point in going into detail. :)
> 
> Error creating shaded jar: Problem shading JAR
> 
> /.m2/com/fasterxml/jackson/core/jackson-core/2.15.2/jackson-core-2.15.2.jar entry META-INF/versions/19/com/fasterxml/jackson/core/io/doubleparser/FastDoubleSwar.class: java.lang.IllegalArgumentException: Unsupported class file major version 63
> 
> My shade plugin that has been happily making spark- uber jars breaks and it is very confusing to sort this out. Like why is my spark 3.5.1 which claims to work work with java 8 to java 19, failing at build and shade plugin complaining about java 19 jars? Am I supposed to exclude this and how?

@edward-capriolo-db [Multi Release Jar support](https://openjdk.org/jeps/238) is an important feature of Java. If your shade plugin does not support it then you should report it to the maintainers of the plugin - or find a new plugin that supports it.

**Comment by cowtowncoder** [comment]
As per earlier, https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.15 does briefly mention `jackson-core` 2.15 being multi-release jar.

It might make sense to note that issues have been reported with various things, including older (?) versions of Maven shade plugin.

**Comment by edward-capriolo-db** [comment]
> > > @cowtowncoder I added a quick mention here - https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.15#jar-changes
> > > I don't think there is much point in going to a lot of detail.
> > 
> > 
> > I think there is a good point in going into detail. :)
> > Error creating shaded jar: Problem shading JAR
> > /.m2/com/fasterxml/jackson/core/jackson-core/2.15.2/jackson-core-2.15.2.jar entry META-INF/versions/19/com/fasterxml/jackson/core/io/doubleparser/FastDoubleSwar.class: java.lang.IllegalArgumentException: Unsupported class file major version 63
> > My shade plugin that has been happily making spark- uber jars breaks and it is very confusing to sort this out. Like why is my spark 3.5.1 which claims to work work with java 8 to java 19, failing at build and shade plugin complaining about java 19 jars? Am I supposed to exclude this and how?
> 
> @edward-capriolo-db [Multi Release Jar support](https://openjdk.org/jeps/238) is an important feature of Java. If your shade plugin does not support it then you should report it to the maintainers of the plugin - or find a new plugin that supports it.

I agree that ultimately the issue is an issue with a shade plugin. That being said multi-release jars are a new thing to me. I would assume other people have not seen them as well and are not in the loop.  As we know Jackson is baked into lots of things  so someone like me has been updating without any extra steps for years, suddenly the process breaks/changes. shade/assemblies are very common and most people aren't following the "shade plugin issue tracker" for cool new features.

**Comment by GedMarc** [comment]
Hmm, it's a shade configuration to specify the movement of the META-INF/versions directories to where they must go, not really an error unless just configured wrong. 

Another thing to note is the use of Moditect placed in which version folder, depending on what you want it to do, placing it in the incorrect version folder can also give everyone a looooot of headaches. 

Big change in JDK23, the native JDK version of "ASM", and the removal of ASM from the JDK internals module - this will also have a direct effect on Multi-Release jars as well, and modularization enhancement capabilities that need to be backwards compatible (y)
