### ISSUE TITLE
consider splitting out a jackson-number-parser jar

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-core#900]
jackson-core 2.15 is now over 800k while jackson 2.14 is 460k (2.13 is more like 360k). Most of the increase comes from the fastparser package.

We could use a [ServiceLoader](https://docs.oracle.com/javase/8/docs/api/java/util/ServiceLoader.html) implementation for the NumberInput class. We could have a default implementation that ignores the fastparser flags. Users then wouldn't need the jackson-number-parser jar.

The jackson-number-parser jar would have a different implementation of the NumberInput class (basically the existing 2.15 version of the code) and this would be automatically used if the jackson-number-parser jar was on the classpath.

This approach makes life a bit more complicated but it might be useful for users who want to use Jackson on devices with limited memory/storage.

**Comment by cowtowncoder** [comment]
Hmmh. Yes, I can see potential benefits. I'd hesitate using `ServiceLoader` since it at least in the past it has had significant performance problems. But then again automatically configuring components gets tricky otherwise.

I'll leave this open as potential future thing to tackle (post-2.15 for sure).

**Comment by wrandelshofer** [comment]
I have reduced the size of the multi-release jar file from 401 KB to 121 KB in version **0.8.0** of FastDoubleParser. 
https://github.com/wrandelshofer/FastDoubleParser/releases/tag/v0.8.0

This reduces the size of jackson-core-3.0.0-SNAPSHOT.jar in the main branch rev 810051d3 from 837 KB to **546 KB**.

I hope that helps. 😅

**Comment by pjfanning** [comment]
Great - thanks very much @wrandelshofer

**Comment by cowtowncoder** [comment]
Excellent, thank you very much @wrandelshofer !

**Comment by pjfanning** [comment]
closing due to #942
