### ISSUE TITLE
Auto module name in manifest file

### ISSUE THREAD

**Issue by debjitk** [FasterXML/jackson-core#982]
Please add `MANIFEST.MF` with `Auto-Module-Name`. It would be nice for projects/libraries importing `jackson` as a dependency, building with the new `JAVA 9` modules feature.

**Comment by pjfanning** [comment]
look in the jar - it comes a module-info.class - this Auto-Module-Name will break that - module-info.class is the right solution

please provide proof of an actual issue if you think something is broken - our understanding is that Java 9+ modules are properly supported as is

**Comment by cowtowncoder** [comment]
@debjitk Jackson has had module-info via Moditect for years now.
