### ISSUE TITLE
BigInteger parsing in NumberInput can only support '1e10' format when fast parser mode is not used

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/jackson-core#986]
NumberInput.parseBigInteger uses BigDecimalParser when the string is large (over 1250 chars). BigDecimalParser can parse nums in '1e10' format and you can convert the BigDecimal to a BigInteger.

When the string size is less than 1250 chars, `new BigInteger` is used. This will fail for strings in '1e10' format. BigInteger does not support e notation directly.

If you enable FastDoubleParser support, we use its JavaBigIntegerParser regardless of string size. This rejects '1e10' format in order to match the behaviour of `BigInteger` class.

We should decide whether we want to ban '1e10' format for BigInteger in all cases (which is probably the case in jackson v2.14 and earlier) or if we want to press on and support '1e10' format in all cases. Might be better to ban the format - meaning we could remove the new StreamReadConstraints support for big int scale control.

**Comment by pjfanning** [comment]
@cowtowncoder apologies to be a pain but on further investigation, maybe we should rework the BigInteger support and not allow the parsing of any string that contains an 'e'/'E'.

**Comment by pjfanning** [comment]
The issue is that we inadvertently started supporting '1e10' format for BigInteger when I introduced a performance enhancement that allows numbers with strings of more than 1250 chars to be first parsed as BigDecimalParser (which has enhancements to speed up parsing of large strings). But BigDecimal allows '1e10' format. The recent issues we've had we `toBigInteger` stem from this perf change. The '1e10' format support was never intended - it was an unfortunate side effect of the perf change.

**Comment by cowtowncoder** [comment]
@pjfanning I am also thinking that since limit of 1250 characters is used on using `BigDecimalParser` -- basically, never, not just by defaults but since few would increase limit I think -- we could simplify codebase by just completely removing that use case?
Not a big win but still.

**Comment by pjfanning** [comment]
The change that led to this is https://github.com/FasterXML/jackson-core/pull/826 - my preference is not so much to remove this but that if we have more than 1250 chars, that we also then check for 'e' or 'E' in the string and fail if they appear - before parsing as BigDecimal. Is this ok?

I have definitely found that using BigDecimal parsing for large strings is better than using `new BigInteger`. I know that 1250 > 1000 (the default limit for chars in numbers). It could be argued that the 1250 optimisation is no longer that useful.

So I'm not dead set against removing this code path altogether - just I have a preference to keep it but add the extra check to disallow 'e' notation for BigIntegers.

**Comment by pjfanning** [comment]
If we go as far as removing the 1250 code path, do we also remove the `validateBigIntegerScale` code too? It seems less useful if we do remove the 150 code path.

**Comment by cowtowncoder** [comment]
@pjfanning No I think that check is needed for pretty much everything, where `1e99999` is decoded as FP number but then coerced into `BigInteger` due to target value in POJO is `BigInteger`. 1250 code path is not really being used by most of tests and reproduction did not rely on it.

**Comment by pjfanning** [comment]
With https://github.com/FasterXML/jackson-core/pull/987, scientific notation ('1e10' format) is no longer supported.
