### ISSUE TITLE
Logging level changed in for Jackson 2.15.0

### ISSUE THREAD

**Issue by papachoco** [FasterXML/jackson-core#997]
While running tests for my application in gradle (7.6.1) I noticed that the LOG level seemed to have changed in 2.15.0. Using 2.14.2 the log level was set to DEBUG, however in 2.15.0 the LOG level seemed have changed to something different (INFO?).

So in my app, statements such as 

```
if (LOG.isDebugEnabled()) {
  ...
}
```

no longer pass (slf4j 1.2.11)

Thank you

Carlos

**Comment by pjfanning** [comment]
Jackson does not log using slf4j (or ani other logging framework) to avoid having lib dependencies. Can you re-evaluate this on your side?

**Comment by cowtowncoder** [comment]
Yeah this does not sound like something `jackson-core` would (be able) to do; it has no logging configuration. Something else is likely going on.
